/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/AnchorDouble.hpp>

#include <yordle/data/meta/bin_defs/AnchorBase.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::AnchorDouble::AnchorDouble(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::AnchorBase(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_anchorLeft = prop->cast_prop<yordle::data::prop::point_prop>(901312053u);
    if(ptr_anchorLeft != nullptr) {
        anchorLeft = ptr_anchorLeft->value;
    }

    auto ptr_anchorRight = prop->cast_prop<yordle::data::prop::point_prop>(3926783566u);
    if(ptr_anchorRight != nullptr) {
        anchorRight = ptr_anchorRight->value;
    }
}
