/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ChangeTurnRadius.hpp>

#include <yordle/data/meta/bin_defs/MissileTriggeredActionSpec.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ChangeTurnRadius::ChangeTurnRadius(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::MissileTriggeredActionSpec(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x84bb076a = prop->cast_prop<yordle::data::prop::set_prop>(2226849642u);
    if(ptr_x84bb076a != nullptr) {
        auto index_x84bb076a = 0;
        for(const auto &set_x84bb076a_entry : ptr_x84bb076a->value) {
            auto ptr_x84bb076a_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(set_x84bb076a_entry);
            if(ptr_x84bb076a_entry != nullptr) {
                x84bb076a[index_x84bb076a] = ptr_x84bb076a_entry->value;
            }
            index_x84bb076a++;
        }
    }
}
