/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ClientStateAudioDataProperties.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ClientStateAudioDataProperties::ClientStateAudioDataProperties(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_BankPaths = prop->cast_prop<yordle::data::prop::set_prop>(3322153993u);
    if(ptr_BankPaths != nullptr) {
        for(const auto &set_BankPaths_entry : ptr_BankPaths->value) {
            auto ptr_BankPaths_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_BankPaths_entry);
            if(ptr_BankPaths_entry != nullptr) {
                BankPaths.emplace_back(ptr_BankPaths_entry->value);
            }
        }
    }

    auto ptr_themeMusic = prop->cast_prop<yordle::data::prop::string_prop>(1403862017u);
    if(ptr_themeMusic != nullptr) {
        themeMusic = ptr_themeMusic->value;
    }
}
