/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ComparisonScriptCondition.hpp>

#include <yordle/data/meta/bin_defs/IScriptValueGet.hpp>
#include <yordle/data/meta/bin_defs/IScriptCondition.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ComparisonScriptCondition::ComparisonScriptCondition(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IScriptCondition(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Value1 = prop->cast_prop<yordle::data::prop::structure_prop>(1984410657u);
    if(ptr_Value1 != nullptr) {
        Value1 = yordle::data::meta::deserialize<yordle::data::meta::IScriptValueGet>(ptr_Value1, 4142338480u);
    }

    auto ptr_Value2 = prop->cast_prop<yordle::data::prop::structure_prop>(1934077800u);
    if(ptr_Value2 != nullptr) {
        Value2 = yordle::data::meta::deserialize<yordle::data::meta::IScriptValueGet>(ptr_Value2, 4142338480u);
    }

    auto ptr_Operation = prop->cast_prop<yordle::data::prop::uint32_prop>(1396605190u);
    if(ptr_Operation != nullptr) {
        Operation = ptr_Operation->value;
    }
}
