/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/CustomReductionMultiplierCalculationPart.hpp>

#include <yordle/data/meta/bin_defs/IGameCalculationPart.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::CustomReductionMultiplierCalculationPart::CustomReductionMultiplierCalculationPart(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IGameCalculationPart(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x6e82b179 = prop->cast_prop<yordle::data::prop::structure_prop>(1854058873u);
    if(ptr_x6e82b179 != nullptr) {
        x6e82b179 = yordle::data::meta::deserialize<yordle::data::meta::IGameCalculationPart>(ptr_x6e82b179, 3053458126u);
    }

    auto ptr_mMaximumReductionPercent = prop->cast_prop<yordle::data::prop::float32_prop>(4038717832u);
    if(ptr_mMaximumReductionPercent != nullptr) {
        mMaximumReductionPercent = ptr_mMaximumReductionPercent->value;
    }
}
