/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/DynamicMaterialParameterDef.hpp>

#include <yordle/data/meta/bin_defs/IDynamicMaterialDriver.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::DynamicMaterialParameterDef::DynamicMaterialParameterDef(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_name = prop->cast_prop<yordle::data::prop::string_prop>(2369371622u);
    if(ptr_name != nullptr) {
        name = ptr_name->value;
    }

    auto ptr_driver = prop->cast_prop<yordle::data::prop::structure_prop>(3847494111u);
    if(ptr_driver != nullptr) {
        driver = yordle::data::meta::deserialize<yordle::data::meta::IDynamicMaterialDriver>(ptr_driver, 1009087838u);
    }

    auto ptr_enabled = prop->cast_prop<yordle::data::prop::bool_prop>(49525662u);
    if(ptr_enabled != nullptr) {
        enabled = ptr_enabled->value;
    }
}
