/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ForEachInCustomTableBlock.hpp>

#include <yordle/data/meta/bin_defs/CustomTableGet.hpp>
#include <yordle/data/meta/bin_defs/ScriptTableSet.hpp>
#include <yordle/data/meta/bin_defs/ScriptSequence.hpp>
#include <yordle/data/meta/bin_defs/IScriptBlock.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ForEachInCustomTableBlock::ForEachInCustomTableBlock(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IScriptBlock(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_CustomTable = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4220587202u);
    if(ptr_CustomTable != nullptr) {
        CustomTable = yordle::data::meta::deserialize<yordle::data::meta::CustomTableGet>(ptr_CustomTable, 2681684398u);
    }

    auto ptr_SortedByKeys = prop->cast_prop<yordle::data::prop::bool_prop>(1055654413u);
    if(ptr_SortedByKeys != nullptr) {
        SortedByKeys = ptr_SortedByKeys->value;
    }

    auto ptr_OutKey = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2482342886u);
    if(ptr_OutKey != nullptr) {
        OutKey = yordle::data::meta::deserialize<yordle::data::meta::ScriptTableSet>(ptr_OutKey, 4139131590u);
    }

    auto ptr_OutValue = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2795494292u);
    if(ptr_OutValue != nullptr) {
        OutValue = yordle::data::meta::deserialize<yordle::data::meta::ScriptTableSet>(ptr_OutValue, 4139131590u);
    }

    auto ptr_Sequence = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1011085160u);
    if(ptr_Sequence != nullptr) {
        Sequence = yordle::data::meta::deserialize<yordle::data::meta::ScriptSequence>(ptr_Sequence, 2793907875u);
    }
}
