/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/FxActionMoveBase.hpp>

#include <yordle/data/meta/bin_defs/x5c086dbd.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::FxActionMoveBase::FxActionMoveBase(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IFxAction(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_TargetObject = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3865339871u);
    if(ptr_TargetObject != nullptr) {
        TargetObject = yordle::data::meta::deserialize<yordle::data::meta::x5c086dbd>(ptr_TargetObject, 1544056253u);
    }

    auto ptr_EasingType = prop->cast_prop<yordle::data::prop::uint8_prop>(1933980160u);
    if(ptr_EasingType != nullptr) {
        EasingType = ptr_EasingType->value;
    }

    auto ptr_OvershootDistance = prop->cast_prop<yordle::data::prop::float32_prop>(1510344961u);
    if(ptr_OvershootDistance != nullptr) {
        OvershootDistance = ptr_OvershootDistance->value;
    }

    auto ptr_FaceVelocity = prop->cast_prop<yordle::data::prop::bool_prop>(2865748087u);
    if(ptr_FaceVelocity != nullptr) {
        FaceVelocity = ptr_FaceVelocity->value;
    }
}
