/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/FxActionAnimate.hpp>

#include <yordle/data/meta/bin_defs/x5c086dbd.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::FxActionAnimate::FxActionAnimate(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IFxAction(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_animName = prop->cast_prop<yordle::data::prop::string_prop>(3932645331u);
    if(ptr_animName != nullptr) {
        animName = ptr_animName->value;
    }

    auto ptr_TargetObject = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3865339871u);
    if(ptr_TargetObject != nullptr) {
        TargetObject = yordle::data::meta::deserialize<yordle::data::meta::x5c086dbd>(ptr_TargetObject, 1544056253u);
    }

    auto ptr_Loop = prop->cast_prop<yordle::data::prop::bool_prop>(3723446379u);
    if(ptr_Loop != nullptr) {
        Loop = ptr_Loop->value;
    }

    auto ptr_xee7cd89a = prop->cast_prop<yordle::data::prop::bool_prop>(4001159322u);
    if(ptr_xee7cd89a != nullptr) {
        xee7cd89a = ptr_xee7cd89a->value;
    }

    auto ptr_PauseOnEnd = prop->cast_prop<yordle::data::prop::bool_prop>(2139202717u);
    if(ptr_PauseOnEnd != nullptr) {
        PauseOnEnd = ptr_PauseOnEnd->value;
    }
}
