/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/GameModeConstantsGroup.hpp>

#include <yordle/data/meta/bin_defs/GameModeConstant.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::GameModeConstantsGroup::GameModeConstantsGroup(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mConstants = prop->cast_prop<yordle::data::prop::map_prop>(125003421u);
    if(ptr_mConstants != nullptr) {
        for(const auto &set_mConstants_pair : ptr_mConstants->value) {
            auto ptr_mConstants_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_mConstants_pair.first);
            auto ptr_mConstants_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_mConstants_pair.second);
            if(ptr_mConstants_key != nullptr && ptr_mConstants_value != nullptr) {
                mConstants.emplace(ptr_mConstants_key->value, yordle::data::meta::deserialize<yordle::data::meta::GameModeConstant>(ptr_mConstants_value, 1670770484u));
            }
        }
    }
}
