/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/GameCalculation.hpp>

#include <yordle/data/meta/bin_defs/IGameCalculationPart.hpp>
#include <yordle/data/meta/bin_defs/IGameCalculation.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::GameCalculation::GameCalculation(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IGameCalculation(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mFormulaParts = prop->cast_prop<yordle::data::prop::set_prop>(1357989312u);
    if(ptr_mFormulaParts != nullptr) {
        for(const auto &set_mFormulaParts_entry : ptr_mFormulaParts->value) {
            auto ptr_mFormulaParts_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_mFormulaParts_entry);
            if(ptr_mFormulaParts_entry != nullptr) {
                mFormulaParts.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::IGameCalculationPart>(ptr_mFormulaParts_entry, 3053458126u));
            }
        }
    }

    auto ptr_mDisplayAsPercent = prop->cast_prop<yordle::data::prop::bool_prop>(1512216531u);
    if(ptr_mDisplayAsPercent != nullptr) {
        mDisplayAsPercent = ptr_mDisplayAsPercent->value;
    }

    auto ptr_mPrecision = prop->cast_prop<yordle::data::prop::int32_prop>(148143844u);
    if(ptr_mPrecision != nullptr) {
        mPrecision = ptr_mPrecision->value;
    }
}
