/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/HudTunables.hpp>

#include <yordle/data/meta/bin_defs/HudElementalSectionUIData.hpp>
#include <yordle/data/meta/bin_defs/HudGearSelectionUIData.hpp>
#include <yordle/data/meta/bin_defs/HudRadialWheelData.hpp>
#include <yordle/data/meta/bin_defs/HudPingData.hpp>
#include <yordle/data/meta/bin_defs/HudMenuTransitionData.hpp>
#include <yordle/data/meta/bin_defs/HudStatPanelStatStoneData.hpp>
#include <yordle/data/meta/bin_defs/HudStatStoneData.hpp>
#include <yordle/data/meta/bin_defs/HudStatStoneDeathRecapData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::HudTunables::HudTunables(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mElementalSelectionAnimationData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2877628373u);
    if(ptr_mElementalSelectionAnimationData != nullptr) {
        mElementalSelectionAnimationData = yordle::data::meta::deserialize<yordle::data::meta::HudElementalSectionUIData>(ptr_mElementalSelectionAnimationData, 3553075624u);
    }

    auto ptr_mGearSelectionData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3357629991u);
    if(ptr_mGearSelectionData != nullptr) {
        mGearSelectionData = yordle::data::meta::deserialize<yordle::data::meta::HudGearSelectionUIData>(ptr_mGearSelectionData, 1288133231u);
    }

    auto ptr_mRadailWheelData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(677840474u);
    if(ptr_mRadailWheelData != nullptr) {
        mRadailWheelData = yordle::data::meta::deserialize<yordle::data::meta::HudRadialWheelData>(ptr_mRadailWheelData, 1493463692u);
    }

    auto ptr_mPingData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2964416024u);
    if(ptr_mPingData != nullptr) {
        mPingData = yordle::data::meta::deserialize<yordle::data::meta::HudPingData>(ptr_mPingData, 3598370238u);
    }

    auto ptr_mGameScoreboardTransitionData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(316400827u);
    if(ptr_mGameScoreboardTransitionData != nullptr) {
        mGameScoreboardTransitionData = yordle::data::meta::deserialize<yordle::data::meta::HudMenuTransitionData>(ptr_mGameScoreboardTransitionData, 3273533950u);
    }

    auto ptr_mReplayScoreboardTransitionData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3348672342u);
    if(ptr_mReplayScoreboardTransitionData != nullptr) {
        mReplayScoreboardTransitionData = yordle::data::meta::deserialize<yordle::data::meta::HudMenuTransitionData>(ptr_mReplayScoreboardTransitionData, 3273533950u);
    }

    auto ptr_mReplayGameStatsTransitionData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2165066103u);
    if(ptr_mReplayGameStatsTransitionData != nullptr) {
        mReplayGameStatsTransitionData = yordle::data::meta::deserialize<yordle::data::meta::HudMenuTransitionData>(ptr_mReplayGameStatsTransitionData, 3273533950u);
    }

    auto ptr_mStatPanelStatStoneData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2076079679u);
    if(ptr_mStatPanelStatStoneData != nullptr) {
        mStatPanelStatStoneData = yordle::data::meta::deserialize<yordle::data::meta::HudStatPanelStatStoneData>(ptr_mStatPanelStatStoneData, 2341739189u);
    }

    auto ptr_mStatStoneData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4210907615u);
    if(ptr_mStatStoneData != nullptr) {
        mStatStoneData = yordle::data::meta::deserialize<yordle::data::meta::HudStatStoneData>(ptr_mStatStoneData, 2137884073u);
    }

    auto ptr_mStatStoneDeathRecapData = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3128315546u);
    if(ptr_mStatStoneDeathRecapData != nullptr) {
        mStatStoneDeathRecapData = yordle::data::meta::deserialize<yordle::data::meta::HudStatStoneDeathRecapData>(ptr_mStatStoneDeathRecapData, 1887734700u);
    }
}
