/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/IShaderDef.hpp>

#include <yordle/data/meta/bin_defs/ShaderPhysicalParameter.hpp>
#include <yordle/data/meta/bin_defs/ShaderStaticSwitch.hpp>
#include <yordle/data/meta/bin_defs/ShaderTexture.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::IShaderDef::IShaderDef(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_parameters = prop->cast_prop<yordle::data::prop::set_prop>(1218784985u);
    if(ptr_parameters != nullptr) {
        for(const auto &set_parameters_entry : ptr_parameters->value) {
            auto ptr_parameters_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_parameters_entry);
            if(ptr_parameters_entry != nullptr) {
                parameters.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ShaderPhysicalParameter>(ptr_parameters_entry, 2171032536u));
            }
        }
    }

    auto ptr_staticSwitches = prop->cast_prop<yordle::data::prop::set_prop>(848380795u);
    if(ptr_staticSwitches != nullptr) {
        for(const auto &set_staticSwitches_entry : ptr_staticSwitches->value) {
            auto ptr_staticSwitches_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_staticSwitches_entry);
            if(ptr_staticSwitches_entry != nullptr) {
                staticSwitches.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ShaderStaticSwitch>(ptr_staticSwitches_entry, 1621267174u));
            }
        }
    }

    auto ptr_textures = prop->cast_prop<yordle::data::prop::set_prop>(2567998597u);
    if(ptr_textures != nullptr) {
        for(const auto &set_textures_entry : ptr_textures->value) {
            auto ptr_textures_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_textures_entry);
            if(ptr_textures_entry != nullptr) {
                textures.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ShaderTexture>(ptr_textures_entry, 835838499u));
            }
        }
    }

    auto ptr_featureDefines = prop->cast_prop<yordle::data::prop::map_prop>(2921932923u);
    if(ptr_featureDefines != nullptr) {
        for(const auto &set_featureDefines_pair : ptr_featureDefines->value) {
            auto ptr_featureDefines_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_featureDefines_pair.first);
            auto ptr_featureDefines_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_featureDefines_pair.second);
            if(ptr_featureDefines_key != nullptr && ptr_featureDefines_value != nullptr) {
                featureDefines.emplace(ptr_featureDefines_key->value, ptr_featureDefines_value->value);
            }
        }
    }

    auto ptr_featureMask = prop->cast_prop<yordle::data::prop::uint32_prop>(632775201u);
    if(ptr_featureMask != nullptr) {
        featureMask = ptr_featureMask->value;
    }

    auto ptr_x9bfe7d81 = prop->cast_prop<yordle::data::prop::uint32_prop>(2617146753u);
    if(ptr_x9bfe7d81 != nullptr) {
        x9bfe7d81 = ptr_x9bfe7d81->value;
    }
}
