/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ItemRecommendationCondition.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ItemRecommendationCondition::ItemRecommendationCondition(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mItem = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1281445127u);
    if(ptr_mItem != nullptr) {
        mItem = ptr_mItem->value;
    }

    auto ptr_mDisplayLimit = prop->cast_prop<yordle::data::prop::uint32_prop>(1383594277u);
    if(ptr_mDisplayLimit != nullptr) {
        mDisplayLimit = ptr_mDisplayLimit->value;
    }

    auto ptr_mGroupId = prop->cast_prop<yordle::data::prop::uint8_prop>(878428694u);
    if(ptr_mGroupId != nullptr) {
        mGroupId = ptr_mGroupId->value;
    }
}
