/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ItemData.hpp>

#include <yordle/data/meta/bin_defs/ItemGroup.hpp>
#include <yordle/data/meta/bin_defs/ItemAdviceAttribute.hpp>
#include <yordle/data/meta/bin_defs/ItemData.hpp>
#include <yordle/data/meta/bin_defs/ItemModifier.hpp>
#include <yordle/data/meta/bin_defs/ItemDataBuild.hpp>
#include <yordle/data/meta/bin_defs/ItemDataAvailability.hpp>
#include <yordle/data/meta/bin_defs/ItemDataValue.hpp>
#include <yordle/data/meta/bin_defs/x61f8c41c.hpp>
#include <yordle/data/meta/bin_defs/IGameCalculation.hpp>
#include <yordle/data/meta/bin_defs/ItemDataClient.hpp>
#include <yordle/data/meta/bin_defs/ResourceResolver.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ItemData::ItemData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mRequiredChampion = prop->cast_prop<yordle::data::prop::string_prop>(243406986u);
    if(ptr_mRequiredChampion != nullptr) {
        mRequiredChampion = ptr_mRequiredChampion->value;
    }

    auto ptr_mRequiredAlly = prop->cast_prop<yordle::data::prop::string_prop>(1076119683u);
    if(ptr_mRequiredAlly != nullptr) {
        mRequiredAlly = ptr_mRequiredAlly->value;
    }

    auto ptr_mRequiredSpellName = prop->cast_prop<yordle::data::prop::string_prop>(3301591302u);
    if(ptr_mRequiredSpellName != nullptr) {
        mRequiredSpellName = ptr_mRequiredSpellName->value;
    }

    auto ptr_mRequiredBuffCurrencyName = prop->cast_prop<yordle::data::prop::string_prop>(2389750688u);
    if(ptr_mRequiredBuffCurrencyName != nullptr) {
        mRequiredBuffCurrencyName = ptr_mRequiredBuffCurrencyName->value;
    }

    auto ptr_mRequiredPurchaseIdentities = prop->cast_prop<yordle::data::prop::set_prop>(2199566952u);
    if(ptr_mRequiredPurchaseIdentities != nullptr) {
        for(const auto &set_mRequiredPurchaseIdentities_entry : ptr_mRequiredPurchaseIdentities->value) {
            auto ptr_mRequiredPurchaseIdentities_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_mRequiredPurchaseIdentities_entry);
            if(ptr_mRequiredPurchaseIdentities_entry != nullptr) {
                mRequiredPurchaseIdentities.emplace_back(ptr_mRequiredPurchaseIdentities_entry->value);
            }
        }
    }

    auto ptr_mDisabledDescriptionOverride = prop->cast_prop<yordle::data::prop::string_prop>(2515646082u);
    if(ptr_mDisabledDescriptionOverride != nullptr) {
        mDisabledDescriptionOverride = ptr_mDisabledDescriptionOverride->value;
    }

    auto ptr_mParentEnchantmentGroup = prop->cast_prop<yordle::data::prop::string_prop>(3911778248u);
    if(ptr_mParentEnchantmentGroup != nullptr) {
        mParentEnchantmentGroup = ptr_mParentEnchantmentGroup->value;
    }

    auto ptr_mDeathRecapName = prop->cast_prop<yordle::data::prop::string_prop>(395849542u);
    if(ptr_mDeathRecapName != nullptr) {
        mDeathRecapName = ptr_mDeathRecapName->value;
    }

    auto ptr_mRequiredLevel = prop->cast_prop<yordle::data::prop::int32_prop>(3143486745u);
    if(ptr_mRequiredLevel != nullptr) {
        mRequiredLevel = ptr_mRequiredLevel->value;
    }

    auto ptr_itemID = prop->cast_prop<yordle::data::prop::int32_prop>(331209851u);
    if(ptr_itemID != nullptr) {
        itemID = ptr_itemID->value;
    }

    auto ptr_maxStack = prop->cast_prop<yordle::data::prop::int32_prop>(2362301363u);
    if(ptr_maxStack != nullptr) {
        maxStack = ptr_maxStack->value;
    }

    auto ptr_mItemGroups = prop->cast_prop<yordle::data::prop::set_prop>(1926246343u);
    if(ptr_mItemGroups != nullptr) {
        for(const auto &set_mItemGroups_entry : ptr_mItemGroups->value) {
            auto ptr_mItemGroups_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_mItemGroups_entry);
            if(ptr_mItemGroups_entry != nullptr) {
                mItemGroups.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemGroup>(992861497u, ptr_mItemGroups_entry->value));
            }
        }
    }

    auto ptr_mItemAdviceAttributes = prop->cast_prop<yordle::data::prop::set_prop>(1527415230u);
    if(ptr_mItemAdviceAttributes != nullptr) {
        for(const auto &set_mItemAdviceAttributes_entry : ptr_mItemAdviceAttributes->value) {
            auto ptr_mItemAdviceAttributes_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_mItemAdviceAttributes_entry);
            if(ptr_mItemAdviceAttributes_entry != nullptr) {
                mItemAdviceAttributes.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemAdviceAttribute>(573358062u, ptr_mItemAdviceAttributes_entry->value));
            }
        }
    }

    auto ptr_itemVOGroup = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(553900340u);
    if(ptr_itemVOGroup != nullptr) {
        itemVOGroup = ptr_itemVOGroup->value;
    }

    auto ptr_price = prop->cast_prop<yordle::data::prop::int32_prop>(189023530u);
    if(ptr_price != nullptr) {
        price = ptr_price->value;
    }

    auto ptr_mRequiredBuffCurrencyCost = prop->cast_prop<yordle::data::prop::int32_prop>(1153225762u);
    if(ptr_mRequiredBuffCurrencyCost != nullptr) {
        mRequiredBuffCurrencyCost = ptr_mRequiredBuffCurrencyCost->value;
    }

    auto ptr_mSidegradeCredit = prop->cast_prop<yordle::data::prop::float32_prop>(340108739u);
    if(ptr_mSidegradeCredit != nullptr) {
        mSidegradeCredit = ptr_mSidegradeCredit->value;
    }

    auto ptr_consumed = prop->cast_prop<yordle::data::prop::bool_prop>(1312195519u);
    if(ptr_consumed != nullptr) {
        consumed = ptr_consumed->value;
    }

    auto ptr_usableInStore = prop->cast_prop<yordle::data::prop::bool_prop>(2403638411u);
    if(ptr_usableInStore != nullptr) {
        usableInStore = ptr_usableInStore->value;
    }

    auto ptr_consumeOnAcquire = prop->cast_prop<yordle::data::prop::bool_prop>(2162312232u);
    if(ptr_consumeOnAcquire != nullptr) {
        consumeOnAcquire = ptr_consumeOnAcquire->value;
    }

    auto ptr_mItemCalloutPlayer = prop->cast_prop<yordle::data::prop::bool_prop>(3776240468u);
    if(ptr_mItemCalloutPlayer != nullptr) {
        mItemCalloutPlayer = ptr_mItemCalloutPlayer->value;
    }

    auto ptr_mItemCalloutSpectator = prop->cast_prop<yordle::data::prop::bool_prop>(1371846774u);
    if(ptr_mItemCalloutSpectator != nullptr) {
        mItemCalloutSpectator = ptr_mItemCalloutSpectator->value;
    }

    auto ptr_clearUndoHistory = prop->cast_prop<yordle::data::prop::uint8_prop>(3517176776u);
    if(ptr_clearUndoHistory != nullptr) {
        clearUndoHistory = ptr_clearUndoHistory->value;
    }

    auto ptr_mCanBeSold = prop->cast_prop<yordle::data::prop::bool_prop>(3520834977u);
    if(ptr_mCanBeSold != nullptr) {
        mCanBeSold = ptr_mCanBeSold->value;
    }

    auto ptr_mHiddenFromOpponents = prop->cast_prop<yordle::data::prop::bool_prop>(1851807742u);
    if(ptr_mHiddenFromOpponents != nullptr) {
        mHiddenFromOpponents = ptr_mHiddenFromOpponents->value;
    }

    auto ptr_mIsEnchantment = prop->cast_prop<yordle::data::prop::bool_prop>(2758140601u);
    if(ptr_mIsEnchantment != nullptr) {
        mIsEnchantment = ptr_mIsEnchantment->value;
    }

    auto ptr_specialRecipe = prop->cast_prop<yordle::data::prop::int32_prop>(119453886u);
    if(ptr_specialRecipe != nullptr) {
        specialRecipe = ptr_specialRecipe->value;
    }

    auto ptr_epicness = prop->cast_prop<yordle::data::prop::uint8_prop>(1591985235u);
    if(ptr_epicness != nullptr) {
        epicness = ptr_epicness->value;
    }

    auto ptr_SecondaryEpicness = prop->cast_prop<yordle::data::prop::uint8_prop>(2413426407u);
    if(ptr_SecondaryEpicness != nullptr) {
        SecondaryEpicness = ptr_SecondaryEpicness->value;
    }

    auto ptr_recipeItemLinks = prop->cast_prop<yordle::data::prop::set_prop>(741707921u);
    if(ptr_recipeItemLinks != nullptr) {
        for(const auto &set_recipeItemLinks_entry : ptr_recipeItemLinks->value) {
            auto ptr_recipeItemLinks_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_recipeItemLinks_entry);
            if(ptr_recipeItemLinks_entry != nullptr) {
                recipeItemLinks.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemData>(608970470u, ptr_recipeItemLinks_entry->value));
            }
        }
    }

    auto ptr_requiredItemLinks = prop->cast_prop<yordle::data::prop::set_prop>(4205694064u);
    if(ptr_requiredItemLinks != nullptr) {
        for(const auto &set_requiredItemLinks_entry : ptr_requiredItemLinks->value) {
            auto ptr_requiredItemLinks_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_requiredItemLinks_entry);
            if(ptr_requiredItemLinks_entry != nullptr) {
                requiredItemLinks.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemData>(608970470u, ptr_requiredItemLinks_entry->value));
            }
        }
    }

    auto ptr_sidegradeItemLinks = prop->cast_prop<yordle::data::prop::set_prop>(1731786979u);
    if(ptr_sidegradeItemLinks != nullptr) {
        for(const auto &set_sidegradeItemLinks_entry : ptr_sidegradeItemLinks->value) {
            auto ptr_sidegradeItemLinks_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_sidegradeItemLinks_entry);
            if(ptr_sidegradeItemLinks_entry != nullptr) {
                sidegradeItemLinks.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemData>(608970470u, ptr_sidegradeItemLinks_entry->value));
            }
        }
    }

    auto ptr_mItemModifiers = prop->cast_prop<yordle::data::prop::set_prop>(3055062855u);
    if(ptr_mItemModifiers != nullptr) {
        for(const auto &set_mItemModifiers_entry : ptr_mItemModifiers->value) {
            auto ptr_mItemModifiers_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_mItemModifiers_entry);
            if(ptr_mItemModifiers_entry != nullptr) {
                mItemModifiers.emplace_back(yordle::data::meta::bin_ref<yordle::data::meta::ItemModifier>(2109319947u, ptr_mItemModifiers_entry->value));
            }
        }
    }

    auto ptr_mScripts = prop->cast_prop<yordle::data::prop::set_prop>(2657988264u);
    if(ptr_mScripts != nullptr) {
        for(const auto &set_mScripts_entry : ptr_mScripts->value) {
            auto ptr_mScripts_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_mScripts_entry);
            if(ptr_mScripts_entry != nullptr) {
                mScripts.emplace_back(ptr_mScripts_entry->value);
            }
        }
    }

    auto ptr_parentEnchantmentLink = prop->cast_prop<yordle::data::prop::reference_prop>(3884213970u);
    if(ptr_parentEnchantmentLink != nullptr) {
        parentEnchantmentLink = yordle::data::meta::bin_ref<yordle::data::meta::ItemData>(608970470u, ptr_parentEnchantmentLink->value);
    }

    auto ptr_parentItemLink = prop->cast_prop<yordle::data::prop::reference_prop>(240928630u);
    if(ptr_parentItemLink != nullptr) {
        parentItemLink = yordle::data::meta::bin_ref<yordle::data::meta::ItemData>(608970470u, ptr_parentItemLink->value);
    }

    auto ptr_mFlatCooldownMod = prop->cast_prop<yordle::data::prop::float32_prop>(383889158u);
    if(ptr_mFlatCooldownMod != nullptr) {
        mFlatCooldownMod = ptr_mFlatCooldownMod->value;
    }

    auto ptr_mPercentCooldownMod = prop->cast_prop<yordle::data::prop::float32_prop>(2668631768u);
    if(ptr_mPercentCooldownMod != nullptr) {
        mPercentCooldownMod = ptr_mPercentCooldownMod->value;
    }

    auto ptr_mAbilityHasteMod = prop->cast_prop<yordle::data::prop::float32_prop>(1536713119u);
    if(ptr_mAbilityHasteMod != nullptr) {
        mAbilityHasteMod = ptr_mAbilityHasteMod->value;
    }

    auto ptr_mFlatHPPoolMod = prop->cast_prop<yordle::data::prop::float32_prop>(114923451u);
    if(ptr_mFlatHPPoolMod != nullptr) {
        mFlatHPPoolMod = ptr_mFlatHPPoolMod->value;
    }

    auto ptr_mPercentHPPoolMod = prop->cast_prop<yordle::data::prop::float32_prop>(2503021533u);
    if(ptr_mPercentHPPoolMod != nullptr) {
        mPercentHPPoolMod = ptr_mPercentHPPoolMod->value;
    }

    auto ptr_mFlatHPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(21500352u);
    if(ptr_mFlatHPRegenMod != nullptr) {
        mFlatHPRegenMod = ptr_mFlatHPRegenMod->value;
    }

    auto ptr_mPercentHPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(1056021178u);
    if(ptr_mPercentHPRegenMod != nullptr) {
        mPercentHPRegenMod = ptr_mPercentHPRegenMod->value;
    }

    auto ptr_mPercentBaseHPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(3251443531u);
    if(ptr_mPercentBaseHPRegenMod != nullptr) {
        mPercentBaseHPRegenMod = ptr_mPercentBaseHPRegenMod->value;
    }

    auto ptr_mPercentTenacityItemMod = prop->cast_prop<yordle::data::prop::float32_prop>(3484183065u);
    if(ptr_mPercentTenacityItemMod != nullptr) {
        mPercentTenacityItemMod = ptr_mPercentTenacityItemMod->value;
    }

    auto ptr_mPercentSlowResistMod = prop->cast_prop<yordle::data::prop::float32_prop>(438843610u);
    if(ptr_mPercentSlowResistMod != nullptr) {
        mPercentSlowResistMod = ptr_mPercentSlowResistMod->value;
    }

    auto ptr_mFlatMovementSpeedMod = prop->cast_prop<yordle::data::prop::float32_prop>(465474815u);
    if(ptr_mFlatMovementSpeedMod != nullptr) {
        mFlatMovementSpeedMod = ptr_mFlatMovementSpeedMod->value;
    }

    auto ptr_mPercentMovementSpeedMod = prop->cast_prop<yordle::data::prop::float32_prop>(3074015573u);
    if(ptr_mPercentMovementSpeedMod != nullptr) {
        mPercentMovementSpeedMod = ptr_mPercentMovementSpeedMod->value;
    }

    auto ptr_mPercentMultiplicativeMovementSpeedMod = prop->cast_prop<yordle::data::prop::float32_prop>(2860471743u);
    if(ptr_mPercentMultiplicativeMovementSpeedMod != nullptr) {
        mPercentMultiplicativeMovementSpeedMod = ptr_mPercentMultiplicativeMovementSpeedMod->value;
    }

    auto ptr_mFlatArmorMod = prop->cast_prop<yordle::data::prop::float32_prop>(3046428930u);
    if(ptr_mFlatArmorMod != nullptr) {
        mFlatArmorMod = ptr_mFlatArmorMod->value;
    }

    auto ptr_mPercentArmorMod = prop->cast_prop<yordle::data::prop::float32_prop>(2481690788u);
    if(ptr_mPercentArmorMod != nullptr) {
        mPercentArmorMod = ptr_mPercentArmorMod->value;
    }

    auto ptr_mFlatArmorPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(1437359509u);
    if(ptr_mFlatArmorPenetrationMod != nullptr) {
        mFlatArmorPenetrationMod = ptr_mFlatArmorPenetrationMod->value;
    }

    auto ptr_mPercentArmorPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(1175202283u);
    if(ptr_mPercentArmorPenetrationMod != nullptr) {
        mPercentArmorPenetrationMod = ptr_mPercentArmorPenetrationMod->value;
    }

    auto ptr_mPercentBonusArmorPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(1696157308u);
    if(ptr_mPercentBonusArmorPenetrationMod != nullptr) {
        mPercentBonusArmorPenetrationMod = ptr_mPercentBonusArmorPenetrationMod->value;
    }

    auto ptr_mFlatMagicPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(3960767193u);
    if(ptr_mFlatMagicPenetrationMod != nullptr) {
        mFlatMagicPenetrationMod = ptr_mFlatMagicPenetrationMod->value;
    }

    auto ptr_mPercentMagicPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(1490206803u);
    if(ptr_mPercentMagicPenetrationMod != nullptr) {
        mPercentMagicPenetrationMod = ptr_mPercentMagicPenetrationMod->value;
    }

    auto ptr_mPercentBonusMagicPenetrationMod = prop->cast_prop<yordle::data::prop::float32_prop>(1771515992u);
    if(ptr_mPercentBonusMagicPenetrationMod != nullptr) {
        mPercentBonusMagicPenetrationMod = ptr_mPercentBonusMagicPenetrationMod->value;
    }

    auto ptr_mFlatSpellBlockMod = prop->cast_prop<yordle::data::prop::float32_prop>(3120132768u);
    if(ptr_mFlatSpellBlockMod != nullptr) {
        mFlatSpellBlockMod = ptr_mFlatSpellBlockMod->value;
    }

    auto ptr_mPercentSpellBlockMod = prop->cast_prop<yordle::data::prop::float32_prop>(2246896526u);
    if(ptr_mPercentSpellBlockMod != nullptr) {
        mPercentSpellBlockMod = ptr_mPercentSpellBlockMod->value;
    }

    auto ptr_mFlatDodgeMod = prop->cast_prop<yordle::data::prop::float32_prop>(3110649810u);
    if(ptr_mFlatDodgeMod != nullptr) {
        mFlatDodgeMod = ptr_mFlatDodgeMod->value;
    }

    auto ptr_mFlatCritChanceMod = prop->cast_prop<yordle::data::prop::float32_prop>(3154445093u);
    if(ptr_mFlatCritChanceMod != nullptr) {
        mFlatCritChanceMod = ptr_mFlatCritChanceMod->value;
    }

    auto ptr_mFlatMissChanceMod = prop->cast_prop<yordle::data::prop::float32_prop>(3340385681u);
    if(ptr_mFlatMissChanceMod != nullptr) {
        mFlatMissChanceMod = ptr_mFlatMissChanceMod->value;
    }

    auto ptr_mFlatCritDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(3520107050u);
    if(ptr_mFlatCritDamageMod != nullptr) {
        mFlatCritDamageMod = ptr_mFlatCritDamageMod->value;
    }

    auto ptr_mPercentCritDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(823330312u);
    if(ptr_mPercentCritDamageMod != nullptr) {
        mPercentCritDamageMod = ptr_mPercentCritDamageMod->value;
    }

    auto ptr_mFlatPhysicalDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(1316651469u);
    if(ptr_mFlatPhysicalDamageMod != nullptr) {
        mFlatPhysicalDamageMod = ptr_mFlatPhysicalDamageMod->value;
    }

    auto ptr_mPercentPhysicalDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(3556259147u);
    if(ptr_mPercentPhysicalDamageMod != nullptr) {
        mPercentPhysicalDamageMod = ptr_mPercentPhysicalDamageMod->value;
    }

    auto ptr_mFlatMagicDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(680171085u);
    if(ptr_mFlatMagicDamageMod != nullptr) {
        mFlatMagicDamageMod = ptr_mFlatMagicDamageMod->value;
    }

    auto ptr_mPercentMagicDamageMod = prop->cast_prop<yordle::data::prop::float32_prop>(107141991u);
    if(ptr_mPercentMagicDamageMod != nullptr) {
        mPercentMagicDamageMod = ptr_mPercentMagicDamageMod->value;
    }

    auto ptr_mFlatPhysicalReduction = prop->cast_prop<yordle::data::prop::float32_prop>(2093165359u);
    if(ptr_mFlatPhysicalReduction != nullptr) {
        mFlatPhysicalReduction = ptr_mFlatPhysicalReduction->value;
    }

    auto ptr_mPercentPhysicalReduction = prop->cast_prop<yordle::data::prop::float32_prop>(1666883285u);
    if(ptr_mPercentPhysicalReduction != nullptr) {
        mPercentPhysicalReduction = ptr_mPercentPhysicalReduction->value;
    }

    auto ptr_mFlatMagicReduction = prop->cast_prop<yordle::data::prop::float32_prop>(1456684975u);
    if(ptr_mFlatMagicReduction != nullptr) {
        mFlatMagicReduction = ptr_mFlatMagicReduction->value;
    }

    auto ptr_mPercentMagicReduction = prop->cast_prop<yordle::data::prop::float32_prop>(2902530009u);
    if(ptr_mPercentMagicReduction != nullptr) {
        mPercentMagicReduction = ptr_mPercentMagicReduction->value;
    }

    auto ptr_mPercentEXPBonus = prop->cast_prop<yordle::data::prop::float32_prop>(2480014019u);
    if(ptr_mPercentEXPBonus != nullptr) {
        mPercentEXPBonus = ptr_mPercentEXPBonus->value;
    }

    auto ptr_mFlatAttackRangeMod = prop->cast_prop<yordle::data::prop::float32_prop>(2223490792u);
    if(ptr_mFlatAttackRangeMod != nullptr) {
        mFlatAttackRangeMod = ptr_mFlatAttackRangeMod->value;
    }

    auto ptr_mPercentAttackRangeMod = prop->cast_prop<yordle::data::prop::float32_prop>(3418195010u);
    if(ptr_mPercentAttackRangeMod != nullptr) {
        mPercentAttackRangeMod = ptr_mPercentAttackRangeMod->value;
    }

    auto ptr_mFlatCastRangeMod = prop->cast_prop<yordle::data::prop::float32_prop>(1205165755u);
    if(ptr_mFlatCastRangeMod != nullptr) {
        mFlatCastRangeMod = ptr_mFlatCastRangeMod->value;
    }

    auto ptr_mPercentCastRangeMod = prop->cast_prop<yordle::data::prop::float32_prop>(3849080725u);
    if(ptr_mPercentCastRangeMod != nullptr) {
        mPercentCastRangeMod = ptr_mPercentCastRangeMod->value;
    }

    auto ptr_mPercentAttackSpeedMod = prop->cast_prop<yordle::data::prop::float32_prop>(3311766576u);
    if(ptr_mPercentAttackSpeedMod != nullptr) {
        mPercentAttackSpeedMod = ptr_mPercentAttackSpeedMod->value;
    }

    auto ptr_mPercentMultiplicativeAttackSpeedMod = prop->cast_prop<yordle::data::prop::float32_prop>(3413524030u);
    if(ptr_mPercentMultiplicativeAttackSpeedMod != nullptr) {
        mPercentMultiplicativeAttackSpeedMod = ptr_mPercentMultiplicativeAttackSpeedMod->value;
    }

    auto ptr_mPercentHealingAmountMod = prop->cast_prop<yordle::data::prop::float32_prop>(205329187u);
    if(ptr_mPercentHealingAmountMod != nullptr) {
        mPercentHealingAmountMod = ptr_mPercentHealingAmountMod->value;
    }

    auto ptr_mPercentLifeStealMod = prop->cast_prop<yordle::data::prop::float32_prop>(53828642u);
    if(ptr_mPercentLifeStealMod != nullptr) {
        mPercentLifeStealMod = ptr_mPercentLifeStealMod->value;
    }

    auto ptr_mPercentSpellVampMod = prop->cast_prop<yordle::data::prop::float32_prop>(1734111875u);
    if(ptr_mPercentSpellVampMod != nullptr) {
        mPercentSpellVampMod = ptr_mPercentSpellVampMod->value;
    }

    auto ptr_PercentOmniVampMod = prop->cast_prop<yordle::data::prop::float32_prop>(3078168669u);
    if(ptr_PercentOmniVampMod != nullptr) {
        PercentOmniVampMod = ptr_PercentOmniVampMod->value;
    }

    auto ptr_PercentPhysicalVampMod = prop->cast_prop<yordle::data::prop::float32_prop>(471318737u);
    if(ptr_PercentPhysicalVampMod != nullptr) {
        PercentPhysicalVampMod = ptr_PercentPhysicalVampMod->value;
    }

    auto ptr_mPercentSpellEffectivenessMod = prop->cast_prop<yordle::data::prop::float32_prop>(4131342143u);
    if(ptr_mPercentSpellEffectivenessMod != nullptr) {
        mPercentSpellEffectivenessMod = ptr_mPercentSpellEffectivenessMod->value;
    }

    auto ptr_mFlatBubbleRadiusMod = prop->cast_prop<yordle::data::prop::float32_prop>(1894351929u);
    if(ptr_mFlatBubbleRadiusMod != nullptr) {
        mFlatBubbleRadiusMod = ptr_mFlatBubbleRadiusMod->value;
    }

    auto ptr_mPercentBubbleRadiusMod = prop->cast_prop<yordle::data::prop::float32_prop>(2982985559u);
    if(ptr_mPercentBubbleRadiusMod != nullptr) {
        mPercentBubbleRadiusMod = ptr_mPercentBubbleRadiusMod->value;
    }

    auto ptr_sellBackModifier = prop->cast_prop<yordle::data::prop::float32_prop>(1179205471u);
    if(ptr_sellBackModifier != nullptr) {
        sellBackModifier = ptr_sellBackModifier->value;
    }

    auto ptr_mCooldownShowDisabledDuration = prop->cast_prop<yordle::data::prop::float32_prop>(3414564600u);
    if(ptr_mCooldownShowDisabledDuration != nullptr) {
        mCooldownShowDisabledDuration = ptr_mCooldownShowDisabledDuration->value;
    }

    auto ptr_flatMPPoolMod = prop->cast_prop<yordle::data::prop::float32_prop>(2682018419u);
    if(ptr_flatMPPoolMod != nullptr) {
        flatMPPoolMod = ptr_flatMPPoolMod->value;
    }

    auto ptr_PercentMPPoolMod = prop->cast_prop<yordle::data::prop::float32_prop>(1465104691u);
    if(ptr_PercentMPPoolMod != nullptr) {
        PercentMPPoolMod = ptr_PercentMPPoolMod->value;
    }

    auto ptr_flatMPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(3589720264u);
    if(ptr_flatMPRegenMod != nullptr) {
        flatMPRegenMod = ptr_flatMPRegenMod->value;
    }

    auto ptr_PercentMPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(952926856u);
    if(ptr_PercentMPRegenMod != nullptr) {
        PercentMPRegenMod = ptr_PercentMPRegenMod->value;
    }

    auto ptr_percentBaseMPRegenMod = prop->cast_prop<yordle::data::prop::float32_prop>(2809881569u);
    if(ptr_percentBaseMPRegenMod != nullptr) {
        percentBaseMPRegenMod = ptr_percentBaseMPRegenMod->value;
    }

    auto ptr_mItemDataBuild = prop->cast_prop<yordle::data::prop::inline_structure_prop>(149088197u);
    if(ptr_mItemDataBuild != nullptr) {
        mItemDataBuild = yordle::data::meta::deserialize<yordle::data::meta::ItemDataBuild>(ptr_mItemDataBuild, 3845505502u);
    }

    auto ptr_mItemDataAvailability = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1472645072u);
    if(ptr_mItemDataAvailability != nullptr) {
        mItemDataAvailability = yordle::data::meta::deserialize<yordle::data::meta::ItemDataAvailability>(ptr_mItemDataAvailability, 3225152729u);
    }

    auto ptr_mCategories = prop->cast_prop<yordle::data::prop::set_prop>(3438910276u);
    if(ptr_mCategories != nullptr) {
        for(const auto &set_mCategories_entry : ptr_mCategories->value) {
            auto ptr_mCategories_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_mCategories_entry);
            if(ptr_mCategories_entry != nullptr) {
                mCategories.emplace_back(ptr_mCategories_entry->value);
            }
        }
    }

    auto ptr_mBuildDepth = prop->cast_prop<yordle::data::prop::int32_prop>(1632533069u);
    if(ptr_mBuildDepth != nullptr) {
        mBuildDepth = ptr_mBuildDepth->value;
    }

    auto ptr_mDataValues = prop->cast_prop<yordle::data::prop::set_prop>(525148326u);
    if(ptr_mDataValues != nullptr) {
        for(const auto &set_mDataValues_entry : ptr_mDataValues->value) {
            auto ptr_mDataValues_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_mDataValues_entry);
            if(ptr_mDataValues_entry != nullptr) {
                mDataValues.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ItemDataValue>(ptr_mDataValues_entry, 2999331975u));
            }
        }
    }

    auto ptr_xfb56608c = prop->cast_prop<yordle::data::prop::map_prop>(4216742028u);
    if(ptr_xfb56608c != nullptr) {
        for(const auto &set_xfb56608c_pair : ptr_xfb56608c->value) {
            auto ptr_xfb56608c_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_xfb56608c_pair.first);
            auto ptr_xfb56608c_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_xfb56608c_pair.second);
            if(ptr_xfb56608c_key != nullptr && ptr_xfb56608c_value != nullptr) {
                xfb56608c.emplace(ptr_xfb56608c_key->value, yordle::data::meta::deserialize<yordle::data::meta::x61f8c41c>(ptr_xfb56608c_value, 1643693084u));
            }
        }
    }

    auto ptr_mItemCalculations = prop->cast_prop<yordle::data::prop::map_prop>(180678869u);
    if(ptr_mItemCalculations != nullptr) {
        for(const auto &set_mItemCalculations_pair : ptr_mItemCalculations->value) {
            auto ptr_mItemCalculations_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_mItemCalculations_pair.first);
            auto ptr_mItemCalculations_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_mItemCalculations_pair.second);
            if(ptr_mItemCalculations_key != nullptr && ptr_mItemCalculations_value != nullptr) {
                mItemCalculations.emplace(ptr_mItemCalculations_key->value, yordle::data::meta::deserialize<yordle::data::meta::IGameCalculation>(ptr_mItemCalculations_value, 389493299u));
            }
        }
    }

    auto ptr_mItemAttributes = prop->cast_prop<yordle::data::prop::set_prop>(1465224138u);
    if(ptr_mItemAttributes != nullptr) {
        for(const auto &set_mItemAttributes_entry : ptr_mItemAttributes->value) {
            auto ptr_mItemAttributes_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::uint8_prop>(set_mItemAttributes_entry);
            if(ptr_mItemAttributes_entry != nullptr) {
                mItemAttributes.emplace_back(ptr_mItemAttributes_entry->value);
            }
        }
    }

    auto ptr_x224a3815 = prop->cast_prop<yordle::data::prop::int32_prop>(575289365u);
    if(ptr_x224a3815 != nullptr) {
        x224a3815 = ptr_x224a3815->value;
    }

    auto ptr_xc01bb6dd = prop->cast_prop<yordle::data::prop::uint8_prop>(3223041757u);
    if(ptr_xc01bb6dd != nullptr) {
        xc01bb6dd = ptr_xc01bb6dd->value;
    }

    auto ptr_x51265c89 = prop->cast_prop<yordle::data::prop::uint8_prop>(1361468553u);
    if(ptr_x51265c89 != nullptr) {
        x51265c89 = ptr_x51265c89->value;
    }

    auto ptr_mItemDataClient = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3643312288u);
    if(ptr_mItemDataClient != nullptr) {
        mItemDataClient = yordle::data::meta::deserialize<yordle::data::meta::ItemDataClient>(ptr_mItemDataClient, 2233135733u);
    }

    auto ptr_mVFXResourceResolver = prop->cast_prop<yordle::data::prop::structure_prop>(1602389154u);
    if(ptr_mVFXResourceResolver != nullptr) {
        mVFXResourceResolver = yordle::data::meta::deserialize<yordle::data::meta::ResourceResolver>(ptr_mVFXResourceResolver, 4013559603u);
    }

    auto ptr_mDisplayName = prop->cast_prop<yordle::data::prop::string_prop>(1960067173u);
    if(ptr_mDisplayName != nullptr) {
        mDisplayName = ptr_mDisplayName->value;
    }

    auto ptr_mEffectAmount = prop->cast_prop<yordle::data::prop::set_prop>(622481957u);
    if(ptr_mEffectAmount != nullptr) {
        for(const auto &set_mEffectAmount_entry : ptr_mEffectAmount->value) {
            auto ptr_mEffectAmount_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(set_mEffectAmount_entry);
            if(ptr_mEffectAmount_entry != nullptr) {
                mEffectAmount.emplace_back(ptr_mEffectAmount_entry->value);
            }
        }
    }

    auto ptr_mEnchantmentEffectAmount = prop->cast_prop<yordle::data::prop::set_prop>(4158404644u);
    if(ptr_mEnchantmentEffectAmount != nullptr) {
        for(const auto &set_mEnchantmentEffectAmount_entry : ptr_mEnchantmentEffectAmount->value) {
            auto ptr_mEnchantmentEffectAmount_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(set_mEnchantmentEffectAmount_entry);
            if(ptr_mEnchantmentEffectAmount_entry != nullptr) {
                mEnchantmentEffectAmount.emplace_back(ptr_mEnchantmentEffectAmount_entry->value);
            }
        }
    }

    auto ptr_mEffectByLevelAmount = prop->cast_prop<yordle::data::prop::set_prop>(4226416210u);
    if(ptr_mEffectByLevelAmount != nullptr) {
        for(const auto &set_mEffectByLevelAmount_entry : ptr_mEffectByLevelAmount->value) {
            auto ptr_mEffectByLevelAmount_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(set_mEffectByLevelAmount_entry);
            if(ptr_mEffectByLevelAmount_entry != nullptr) {
                mEffectByLevelAmount.emplace_back(ptr_mEffectByLevelAmount_entry->value);
            }
        }
    }

    auto ptr_spellName = prop->cast_prop<yordle::data::prop::string_prop>(2184067234u);
    if(ptr_spellName != nullptr) {
        spellName = ptr_spellName->value;
    }

    auto ptr_clickable = prop->cast_prop<yordle::data::prop::bool_prop>(4029153691u);
    if(ptr_clickable != nullptr) {
        clickable = ptr_clickable->value;
    }

    auto ptr_mMajorActiveItem = prop->cast_prop<yordle::data::prop::bool_prop>(2106565168u);
    if(ptr_mMajorActiveItem != nullptr) {
        mMajorActiveItem = ptr_mMajorActiveItem->value;
    }
}
