/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/LinearTransformProcessorData.hpp>

#include <yordle/data/meta/bin_defs/ValueProcessorData.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::LinearTransformProcessorData::LinearTransformProcessorData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ValueProcessorData(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mMultiplier = prop->cast_prop<yordle::data::prop::float32_prop>(746040831u);
    if(ptr_mMultiplier != nullptr) {
        mMultiplier = ptr_mMultiplier->value;
    }

    auto ptr_mIncrement = prop->cast_prop<yordle::data::prop::float32_prop>(2359684517u);
    if(ptr_mIncrement != nullptr) {
        mIncrement = ptr_mIncrement->value;
    }
}
