/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/LootItem.hpp>

#include <yordle/data/meta/bin_defs/LootStatus.hpp>
#include <yordle/data/meta/bin_defs/LootItemDetails.hpp>
#include <yordle/data/meta/bin_defs/LootOutputBase.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::LootItem::LootItem(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::LootOutputBase(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mInternalName = prop->cast_prop<yordle::data::prop::string_prop>(3912128722u);
    if(ptr_mInternalName != nullptr) {
        mInternalName = ptr_mInternalName->value;
    }

    auto ptr_mName = prop->cast_prop<yordle::data::prop::string_prop>(435142619u);
    if(ptr_mName != nullptr) {
        mName = ptr_mName->value;
    }

    auto ptr_mHoverDescription = prop->cast_prop<yordle::data::prop::string_prop>(959175484u);
    if(ptr_mHoverDescription != nullptr) {
        mHoverDescription = ptr_mHoverDescription->value;
    }

    auto ptr_mAdminDescription = prop->cast_prop<yordle::data::prop::string_prop>(3430910259u);
    if(ptr_mAdminDescription != nullptr) {
        mAdminDescription = ptr_mAdminDescription->value;
    }

    auto ptr_mStatus = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4283268666u);
    if(ptr_mStatus != nullptr) {
        mStatus = yordle::data::meta::deserialize<yordle::data::meta::LootStatus>(ptr_mStatus, 685945729u);
    }

    auto ptr_mDetails = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2369037022u);
    if(ptr_mDetails != nullptr) {
        mDetails = yordle::data::meta::deserialize<yordle::data::meta::LootItemDetails>(ptr_mDetails, 1665937510u);
    }
}
