/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/LootStatus.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::LootStatus::LootStatus(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mTags = prop->cast_prop<yordle::data::prop::set_prop>(1333146945u);
    if(ptr_mTags != nullptr) {
        for(const auto &set_mTags_entry : ptr_mTags->value) {
            auto ptr_mTags_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_mTags_entry);
            if(ptr_mTags_entry != nullptr) {
                mTags.emplace_back(ptr_mTags_entry->value);
            }
        }
    }

    auto ptr_mImageTexturePath = prop->cast_prop<yordle::data::prop::string_prop>(3437130819u);
    if(ptr_mImageTexturePath != nullptr) {
        mImageTexturePath = ptr_mImageTexturePath->value;
    }

    auto ptr_mActiveDate = prop->cast_prop<yordle::data::prop::string_prop>(225453014u);
    if(ptr_mActiveDate != nullptr) {
        mActiveDate = ptr_mActiveDate->value;
    }

    auto ptr_mInactiveDate = prop->cast_prop<yordle::data::prop::string_prop>(3474799429u);
    if(ptr_mInactiveDate != nullptr) {
        mInactiveDate = ptr_mInactiveDate->value;
    }

    auto ptr_mLifetimeMax = prop->cast_prop<yordle::data::prop::int32_prop>(876863779u);
    if(ptr_mLifetimeMax != nullptr) {
        mLifetimeMax = ptr_mLifetimeMax->value;
    }

    auto ptr_mAutoRedeem = prop->cast_prop<yordle::data::prop::bool_prop>(3819983323u);
    if(ptr_mAutoRedeem != nullptr) {
        mAutoRedeem = ptr_mAutoRedeem->value;
    }

    auto ptr_mActive = prop->cast_prop<yordle::data::prop::bool_prop>(235007858u);
    if(ptr_mActive != nullptr) {
        mActive = ptr_mActive->value;
    }
}
