/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/MapPlaceableContainer.hpp>

#include <yordle/data/meta/bin_defs/MapPlaceable.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::MapPlaceableContainer::MapPlaceableContainer(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_items = prop->cast_prop<yordle::data::prop::map_prop>(981021583u);
    if(ptr_items != nullptr) {
        for(const auto &set_items_pair : ptr_items->value) {
            auto ptr_items_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_items_pair.first);
            auto ptr_items_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_items_pair.second);
            if(ptr_items_key != nullptr && ptr_items_value != nullptr) {
                items.emplace(ptr_items_key->value, yordle::data::meta::deserialize<yordle::data::meta::MapPlaceable>(ptr_items_value, 1502315240u));
            }
        }
    }
}
