/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/MaterialParameterData.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::MaterialParameterData::MaterialParameterData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_type = prop->cast_prop<yordle::data::prop::uint8_prop>(1361572173u);
    if(ptr_type != nullptr) {
        type = ptr_type->value;
    }

    auto ptr_DefaultValue = prop->cast_prop<yordle::data::prop::quaternion_prop>(102228511u);
    if(ptr_DefaultValue != nullptr) {
        DefaultValue = ptr_DefaultValue->value;
    }
}
