/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/MessageBoxDialog.hpp>

#include <yordle/data/meta/bin_defs/HudMenuTransitionData.hpp>
#include <yordle/data/meta/bin_defs/x63394a54.hpp>
#include <yordle/data/meta/bin_defs/x75259ad3.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::MessageBoxDialog::MessageBoxDialog(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::x75259ad3(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x131c35c5 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(320615877u);
    if(ptr_x131c35c5 != nullptr) {
        x131c35c5 = ptr_x131c35c5->value;
    }

    auto ptr_x70020ab = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(117448875u);
    if(ptr_x70020ab != nullptr) {
        x70020ab = ptr_x70020ab->value;
    }

    auto ptr_x31dff863 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(836761699u);
    if(ptr_x31dff863 != nullptr) {
        x31dff863 = ptr_x31dff863->value;
    }

    auto ptr_x6fd80c = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(7329804u);
    if(ptr_x6fd80c != nullptr) {
        x6fd80c = ptr_x6fd80c->value;
    }

    auto ptr_xab91ba1f = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2878454303u);
    if(ptr_xab91ba1f != nullptr) {
        xab91ba1f = ptr_xab91ba1f->value;
    }

    auto ptr_x315b9a19 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(828086809u);
    if(ptr_x315b9a19 != nullptr) {
        x315b9a19 = ptr_x315b9a19->value;
    }

    auto ptr_x2992fe27 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(697499175u);
    if(ptr_x2992fe27 != nullptr) {
        x2992fe27 = yordle::data::meta::deserialize<yordle::data::meta::HudMenuTransitionData>(ptr_x2992fe27, 3273533950u);
    }

    auto ptr_x985233b8 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2555524024u);
    if(ptr_x985233b8 != nullptr) {
        x985233b8 = yordle::data::meta::deserialize<yordle::data::meta::x63394a54>(ptr_x985233b8, 1664698964u);
    }

    auto ptr_x1347d194 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(323473812u);
    if(ptr_x1347d194 != nullptr) {
        x1347d194 = yordle::data::meta::deserialize<yordle::data::meta::x63394a54>(ptr_x1347d194, 1664698964u);
    }
}
