/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ModeSelectViewController.hpp>

#include <yordle/data/meta/bin_defs/QueueDisplayData.hpp>
#include <yordle/data/meta/bin_defs/x61767839.hpp>
#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ModeSelectViewController::ModeSelectViewController(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xce6bd23b = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3463172667u);
    if(ptr_xce6bd23b != nullptr) {
        xce6bd23b = ptr_xce6bd23b->value;
    }

    auto ptr_x7125e498 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1898308760u);
    if(ptr_x7125e498 != nullptr) {
        x7125e498 = ptr_x7125e498->value;
    }

    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_QueueDisplayData = prop->cast_prop<yordle::data::prop::set_prop>(1532902214u);
    if(ptr_QueueDisplayData != nullptr) {
        for(const auto &set_QueueDisplayData_entry : ptr_QueueDisplayData->value) {
            auto ptr_QueueDisplayData_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_QueueDisplayData_entry);
            if(ptr_QueueDisplayData_entry != nullptr) {
                QueueDisplayData.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::QueueDisplayData>(ptr_QueueDisplayData_entry, 1532902214u));
            }
        }
    }

    auto ptr_x61767839 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1635153977u);
    if(ptr_x61767839 != nullptr) {
        x61767839 = yordle::data::meta::deserialize<yordle::data::meta::x61767839>(ptr_x61767839, 1635153977u);
    }

    auto ptr_SoundOnActivate = prop->cast_prop<yordle::data::prop::string_prop>(2690247672u);
    if(ptr_SoundOnActivate != nullptr) {
        SoundOnActivate = ptr_SoundOnActivate->value;
    }

    auto ptr_SoundOnDeActivate = prop->cast_prop<yordle::data::prop::string_prop>(54554555u);
    if(ptr_SoundOnDeActivate != nullptr) {
        SoundOnDeActivate = ptr_SoundOnDeActivate->value;
    }

    auto ptr_x71378d8b = prop->cast_prop<yordle::data::prop::set_prop>(1899466123u);
    if(ptr_x71378d8b != nullptr) {
        for(const auto &set_x71378d8b_entry : ptr_x71378d8b->value) {
            auto ptr_x71378d8b_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_x71378d8b_entry);
            if(ptr_x71378d8b_entry != nullptr) {
                x71378d8b.emplace_back(ptr_x71378d8b_entry->value);
            }
        }
    }
}
