/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/OptionTemplateSecondaryHotkeys1Column.hpp>

#include <yordle/data/meta/bin_defs/xceb70e5a.hpp>
#include <yordle/data/meta/bin_defs/x354988a8.hpp>
#include <yordle/data/meta/bin_defs/IOptionTemplate.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::OptionTemplateSecondaryHotkeys1Column::OptionTemplateSecondaryHotkeys1Column(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IOptionTemplate(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x5b59b589 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1532605833u);
    if(ptr_x5b59b589 != nullptr) {
        x5b59b589 = yordle::data::meta::deserialize<yordle::data::meta::xceb70e5a>(ptr_x5b59b589, 3468103258u);
    }

    auto ptr_x5a59b3f6 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1515828214u);
    if(ptr_x5a59b3f6 != nullptr) {
        x5a59b3f6 = yordle::data::meta::deserialize<yordle::data::meta::xceb70e5a>(ptr_x5a59b3f6, 3468103258u);
    }

    auto ptr_xfd31cbcb = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4247899083u);
    if(ptr_xfd31cbcb != nullptr) {
        xfd31cbcb = yordle::data::meta::deserialize<yordle::data::meta::xceb70e5a>(ptr_xfd31cbcb, 3468103258u);
    }

    auto ptr_x545758a8 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1415010472u);
    if(ptr_x545758a8 != nullptr) {
        x545758a8 = yordle::data::meta::deserialize<yordle::data::meta::x354988a8>(ptr_x545758a8, 894011560u);
    }
}
