/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/OptionTemplateCheckbox.hpp>

#include <yordle/data/meta/bin_defs/IOptionTemplate.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::OptionTemplateCheckbox::OptionTemplateCheckbox(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IOptionTemplate(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_buttonDefinition = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3751321492u);
    if(ptr_buttonDefinition != nullptr) {
        buttonDefinition = ptr_buttonDefinition->value;
    }

    auto ptr_LabelElement = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3889856367u);
    if(ptr_LabelElement != nullptr) {
        LabelElement = ptr_LabelElement->value;
    }
}
