/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/OptionItemSecondaryHotkeys2Column.hpp>

#include <yordle/data/meta/bin_defs/xea321356.hpp>
#include <yordle/data/meta/bin_defs/x430dd10d.hpp>
#include <yordle/data/meta/bin_defs/IOptionItem.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::OptionItemSecondaryHotkeys2Column::OptionItemSecondaryHotkeys2Column(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IOptionItem(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x694aaa0b = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1766500875u);
    if(ptr_x694aaa0b != nullptr) {
        x694aaa0b = ptr_x694aaa0b->value;
    }

    auto ptr_Header = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3834172512u);
    if(ptr_Header != nullptr) {
        Header = yordle::data::meta::deserialize<yordle::data::meta::xea321356>(ptr_Header, 3929150294u);
    }

    auto ptr_Rows = prop->cast_prop<yordle::data::prop::set_prop>(708293528u);
    if(ptr_Rows != nullptr) {
        for(const auto &set_Rows_entry : ptr_Rows->value) {
            auto ptr_Rows_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_Rows_entry);
            if(ptr_Rows_entry != nullptr) {
                Rows.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::x430dd10d>(ptr_Rows_entry, 1124978957u));
            }
        }
    }
}
