/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/PatchingViewController.hpp>

#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::PatchingViewController::PatchingViewController(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_x5efd144d = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1593644109u);
    if(ptr_x5efd144d != nullptr) {
        x5efd144d = ptr_x5efd144d->value;
    }

    auto ptr_x53162210 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1393959440u);
    if(ptr_x53162210 != nullptr) {
        x53162210 = ptr_x53162210->value;
    }

    auto ptr_x210a80d4 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(554336468u);
    if(ptr_x210a80d4 != nullptr) {
        x210a80d4 = ptr_x210a80d4->value;
    }

    auto ptr_xa2ed28e0 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2733451488u);
    if(ptr_xa2ed28e0 != nullptr) {
        xa2ed28e0 = ptr_xa2ed28e0->value;
    }

    auto ptr_x68464d70 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1749437808u);
    if(ptr_x68464d70 != nullptr) {
        x68464d70 = ptr_x68464d70->value;
    }
}
