/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/RegionSettings.hpp>

#include <yordle/data/meta/bin_defs/RegionsThatAllowContent.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::RegionSettings::RegionSettings(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mContentTypeAllowedSettings = prop->cast_prop<yordle::data::prop::map_prop>(2189143518u);
    if(ptr_mContentTypeAllowedSettings != nullptr) {
        for(const auto &set_mContentTypeAllowedSettings_pair : ptr_mContentTypeAllowedSettings->value) {
            auto ptr_mContentTypeAllowedSettings_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_mContentTypeAllowedSettings_pair.first);
            auto ptr_mContentTypeAllowedSettings_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_mContentTypeAllowedSettings_pair.second);
            if(ptr_mContentTypeAllowedSettings_key != nullptr && ptr_mContentTypeAllowedSettings_value != nullptr) {
                mContentTypeAllowedSettings.emplace(ptr_mContentTypeAllowedSettings_key->value, yordle::data::meta::deserialize<yordle::data::meta::RegionsThatAllowContent>(ptr_mContentTypeAllowedSettings_value, 2486262273u));
            }
        }
    }
}
