/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/ScriptSequence.hpp>

#include <yordle/data/meta/bin_defs/IScriptBlock.hpp>
#include <yordle/data/meta/bin_defs/IScriptSequence.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::ScriptSequence::ScriptSequence(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IScriptSequence(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Blocks = prop->cast_prop<yordle::data::prop::set_prop>(369992131u);
    if(ptr_Blocks != nullptr) {
        for(const auto &set_Blocks_entry : ptr_Blocks->value) {
            auto ptr_Blocks_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_Blocks_entry);
            if(ptr_Blocks_entry != nullptr) {
                Blocks.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::IScriptBlock>(ptr_Blocks_entry, 1009431984u));
            }
        }
    }
}
