/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/SelectorPairData.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::SelectorPairData::SelectorPairData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mClipName = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3391849597u);
    if(ptr_mClipName != nullptr) {
        mClipName = ptr_mClipName->value;
    }

    auto ptr_mProbability = prop->cast_prop<yordle::data::prop::float32_prop>(1674287183u);
    if(ptr_mProbability != nullptr) {
        mProbability = ptr_mProbability->value;
    }
}
