/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/SkinCharacterMetaDataProperties.hpp>

#include <yordle/data/meta/bin_defs/ESportTeamEntry.hpp>
#include <yordle/data/meta/bin_defs/ESportLeagueEntry.hpp>
#include <yordle/data/meta/bin_defs/SkinCharacterMetaDataProperties_SpawningSkinOffset.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::SkinCharacterMetaDataProperties::SkinCharacterMetaDataProperties(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_eSportCharacter = prop->cast_prop<yordle::data::prop::bool_prop>(1517097453u);
    if(ptr_eSportCharacter != nullptr) {
        eSportCharacter = ptr_eSportCharacter->value;
    }

    auto ptr_eSportTeamTable = prop->cast_prop<yordle::data::prop::set_prop>(1806054589u);
    if(ptr_eSportTeamTable != nullptr) {
        for(const auto &set_eSportTeamTable_entry : ptr_eSportTeamTable->value) {
            auto ptr_eSportTeamTable_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_eSportTeamTable_entry);
            if(ptr_eSportTeamTable_entry != nullptr) {
                eSportTeamTable.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ESportTeamEntry>(ptr_eSportTeamTable_entry, 336658597u));
            }
        }
    }

    auto ptr_eSportLeagueTable = prop->cast_prop<yordle::data::prop::set_prop>(1361690349u);
    if(ptr_eSportLeagueTable != nullptr) {
        for(const auto &set_eSportLeagueTable_entry : ptr_eSportLeagueTable->value) {
            auto ptr_eSportLeagueTable_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_eSportLeagueTable_entry);
            if(ptr_eSportLeagueTable_entry != nullptr) {
                eSportLeagueTable.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::ESportLeagueEntry>(ptr_eSportLeagueTable_entry, 1219793301u));
            }
        }
    }

    auto ptr_skinBasedRelativeColorScheme = prop->cast_prop<yordle::data::prop::bool_prop>(2789129537u);
    if(ptr_skinBasedRelativeColorScheme != nullptr) {
        skinBasedRelativeColorScheme = ptr_skinBasedRelativeColorScheme->value;
    }

    auto ptr_relativeColorSwapTable = prop->cast_prop<yordle::data::prop::set_prop>(4234249205u);
    if(ptr_relativeColorSwapTable != nullptr) {
        for(const auto &set_relativeColorSwapTable_entry : ptr_relativeColorSwapTable->value) {
            auto ptr_relativeColorSwapTable_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::int32_prop>(set_relativeColorSwapTable_entry);
            if(ptr_relativeColorSwapTable_entry != nullptr) {
                relativeColorSwapTable.emplace_back(ptr_relativeColorSwapTable_entry->value);
            }
        }
    }

    auto ptr_spawningSkinOffsets = prop->cast_prop<yordle::data::prop::set_prop>(3410485135u);
    if(ptr_spawningSkinOffsets != nullptr) {
        for(const auto &set_spawningSkinOffsets_entry : ptr_spawningSkinOffsets->value) {
            auto ptr_spawningSkinOffsets_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_spawningSkinOffsets_entry);
            if(ptr_spawningSkinOffsets_entry != nullptr) {
                spawningSkinOffsets.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::SkinCharacterMetaDataProperties_SpawningSkinOffset>(ptr_spawningSkinOffsets_entry, 1393249095u));
            }
        }
    }

    auto ptr_useGDSBinaries = prop->cast_prop<yordle::data::prop::bool_prop>(2816314501u);
    if(ptr_useGDSBinaries != nullptr) {
        useGDSBinaries = ptr_useGDSBinaries->value;
    }
}
