/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/SpecificColorMaterialDriver.hpp>

#include <yordle/data/meta/bin_defs/x995ca734.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::SpecificColorMaterialDriver::SpecificColorMaterialDriver(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::x995ca734(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_mColor = prop->cast_prop<yordle::data::prop::quaternion_prop>(1399972751u);
    if(ptr_mColor != nullptr) {
        mColor = ptr_mColor->value;
    }
}
