/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/SurrenderData.hpp>

#include <yordle/data/meta/bin_defs/SurrenderTypeData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::SurrenderData::SurrenderData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x43f7599b = prop->cast_prop<yordle::data::prop::float32_prop>(1140283803u);
    if(ptr_x43f7599b != nullptr) {
        x43f7599b = ptr_x43f7599b->value;
    }

    auto ptr_xe98993c = prop->cast_prop<yordle::data::prop::float32_prop>(244881724u);
    if(ptr_xe98993c != nullptr) {
        xe98993c = ptr_xe98993c->value;
    }

    auto ptr_xcc805103 = prop->cast_prop<yordle::data::prop::float32_prop>(3430961411u);
    if(ptr_xcc805103 != nullptr) {
        xcc805103 = ptr_xcc805103->value;
    }

    auto ptr_x3afeacf3 = prop->cast_prop<yordle::data::prop::float32_prop>(989768947u);
    if(ptr_x3afeacf3 != nullptr) {
        x3afeacf3 = ptr_x3afeacf3->value;
    }

    auto ptr_mTypeData = prop->cast_prop<yordle::data::prop::map_prop>(321593752u);
    if(ptr_mTypeData != nullptr) {
        for(const auto &set_mTypeData_pair : ptr_mTypeData->value) {
            auto ptr_mTypeData_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::uint8_prop>(set_mTypeData_pair.first);
            auto ptr_mTypeData_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_mTypeData_pair.second);
            if(ptr_mTypeData_key != nullptr && ptr_mTypeData_value != nullptr) {
                mTypeData.emplace(ptr_mTypeData_key->value, yordle::data::meta::deserialize<yordle::data::meta::SurrenderTypeData>(ptr_mTypeData_value, 740737797u));
            }
        }
    }
}
