/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/TargeterDefinitionWall.hpp>

#include <yordle/data/meta/bin_defs/DrawablePositionLocator.hpp>
#include <yordle/data/meta/bin_defs/FloatPerSpellLevel.hpp>
#include <yordle/data/meta/bin_defs/TargeterDefinition.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::TargeterDefinitionWall::TargeterDefinitionWall(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::TargeterDefinition(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_centerLocator = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3558690766u);
    if(ptr_centerLocator != nullptr) {
        centerLocator = yordle::data::meta::deserialize<yordle::data::meta::DrawablePositionLocator>(ptr_centerLocator, 3451066870u);
    }

    auto ptr_wallOrientation = prop->cast_prop<yordle::data::prop::uint32_prop>(352573681u);
    if(ptr_wallOrientation != nullptr) {
        wallOrientation = ptr_wallOrientation->value;
    }

    auto ptr_wallRotation = prop->cast_prop<yordle::data::prop::float32_prop>(2088878927u);
    if(ptr_wallRotation != nullptr) {
        wallRotation = ptr_wallRotation->value;
    }

    auto ptr_thickness = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1829741845u);
    if(ptr_thickness != nullptr) {
        thickness = yordle::data::meta::deserialize<yordle::data::meta::FloatPerSpellLevel>(ptr_thickness, 508250748u);
    }

    auto ptr_length = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2211460629u);
    if(ptr_length != nullptr) {
        length = yordle::data::meta::deserialize<yordle::data::meta::FloatPerSpellLevel>(ptr_length, 508250748u);
    }

    auto ptr_textureWallOverrideName = prop->cast_prop<yordle::data::prop::string_prop>(3253697459u);
    if(ptr_textureWallOverrideName != nullptr) {
        textureWallOverrideName = ptr_textureWallOverrideName->value;
    }
}
