/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/TftGameStartViewController.hpp>

#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::TftGameStartViewController::TftGameStartViewController(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x81317ee6 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2167504614u);
    if(ptr_x81317ee6 != nullptr) {
        x81317ee6 = ptr_x81317ee6->value;
    }

    auto ptr_xfc59b058 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4233736280u);
    if(ptr_xfc59b058 != nullptr) {
        xfc59b058 = ptr_xfc59b058->value;
    }

    auto ptr_xf6a44ab6 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4137962166u);
    if(ptr_xf6a44ab6 != nullptr) {
        xf6a44ab6 = ptr_xf6a44ab6->value;
    }

    auto ptr_x56b85896 = prop->cast_prop<yordle::data::prop::float32_prop>(1454921878u);
    if(ptr_x56b85896 != nullptr) {
        x56b85896 = ptr_x56b85896->value;
    }

    auto ptr_x14713b68 = prop->cast_prop<yordle::data::prop::float32_prop>(342965096u);
    if(ptr_x14713b68 != nullptr) {
        x14713b68 = ptr_x14713b68->value;
    }

    auto ptr_x87f66219 = prop->cast_prop<yordle::data::prop::float32_prop>(2281071129u);
    if(ptr_x87f66219 != nullptr) {
        x87f66219 = ptr_x87f66219->value;
    }
}
