/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/VfxEmitterDefinitionData.hpp>

#include <yordle/data/meta/bin_defs/IMaterialDef.hpp>
#include <yordle/data/meta/bin_defs/IVfxMaterialDriver.hpp>
#include <yordle/data/meta/bin_defs/VfxFieldCollectionDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxMaterialOverrideDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxSoftParticleDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxAlphaErosionDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxPaletteDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxReflectionDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxDistortionDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/VfxEmissionSurfaceData.hpp>
#include <yordle/data/meta/bin_defs/VfxPrimitiveBase.hpp>
#include <yordle/data/meta/bin_defs/ValueFloat.hpp>
#include <yordle/data/meta/bin_defs/FlexValueFloat.hpp>
#include <yordle/data/meta/bin_defs/ValueVector3.hpp>
#include <yordle/data/meta/bin_defs/FlexValueVector3.hpp>
#include <yordle/data/meta/bin_defs/FlexTypeFloat.hpp>
#include <yordle/data/meta/bin_defs/FlexValueVector2.hpp>
#include <yordle/data/meta/bin_defs/ValueColor.hpp>
#include <yordle/data/meta/bin_defs/ValueVector2.hpp>
#include <yordle/data/meta/bin_defs/VfxShape.hpp>
#include <yordle/data/meta/bin_defs/xb13097f0.hpp>
#include <yordle/data/meta/bin_defs/IntegratedValueVector2.hpp>
#include <yordle/data/meta/bin_defs/IntegratedValueFloat.hpp>
#include <yordle/data/meta/bin_defs/IntegratedValueVector3.hpp>
#include <yordle/data/meta/bin_defs/VfxChildParticleSetDefinitionData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::VfxEmitterDefinitionData::VfxEmitterDefinitionData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_emitterName = prop->cast_prop<yordle::data::prop::string_prop>(1025882318u);
    if(ptr_emitterName != nullptr) {
        emitterName = ptr_emitterName->value;
    }

    auto ptr_disabled = prop->cast_prop<yordle::data::prop::bool_prop>(871591685u);
    if(ptr_disabled != nullptr) {
        disabled = ptr_disabled->value;
    }

    auto ptr_disableBackfaceCull = prop->cast_prop<yordle::data::prop::bool_prop>(1016188605u);
    if(ptr_disableBackfaceCull != nullptr) {
        disableBackfaceCull = ptr_disableBackfaceCull->value;
    }

    auto ptr_isTexturePixelated = prop->cast_prop<yordle::data::prop::bool_prop>(3329156504u);
    if(ptr_isTexturePixelated != nullptr) {
        isTexturePixelated = ptr_isTexturePixelated->value;
    }

    auto ptr_renderPhaseOverride = prop->cast_prop<yordle::data::prop::uint8_prop>(1996186992u);
    if(ptr_renderPhaseOverride != nullptr) {
        renderPhaseOverride = ptr_renderPhaseOverride->value;
    }

    auto ptr_blendMode = prop->cast_prop<yordle::data::prop::uint8_prop>(4202188459u);
    if(ptr_blendMode != nullptr) {
        blendMode = ptr_blendMode->value;
    }

    auto ptr_colorblindVisibility = prop->cast_prop<yordle::data::prop::uint8_prop>(1183687955u);
    if(ptr_colorblindVisibility != nullptr) {
        colorblindVisibility = ptr_colorblindVisibility->value;
    }

    auto ptr_offsetLifeScalingSymmetryMode = prop->cast_prop<yordle::data::prop::uint8_prop>(1302105276u);
    if(ptr_offsetLifeScalingSymmetryMode != nullptr) {
        offsetLifeScalingSymmetryMode = ptr_offsetLifeScalingSymmetryMode->value;
    }

    auto ptr_material = prop->cast_prop<yordle::data::prop::reference_prop>(3538210912u);
    if(ptr_material != nullptr) {
        material = yordle::data::meta::bin_ref<yordle::data::meta::IMaterialDef>(3975636772u, ptr_material->value);
    }

    auto ptr_materialDrivers = prop->cast_prop<yordle::data::prop::map_prop>(3305964759u);
    if(ptr_materialDrivers != nullptr) {
        for(const auto &set_materialDrivers_pair : ptr_materialDrivers->value) {
            auto ptr_materialDrivers_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_materialDrivers_pair.first);
            auto ptr_materialDrivers_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_materialDrivers_pair.second);
            if(ptr_materialDrivers_key != nullptr && ptr_materialDrivers_value != nullptr) {
                materialDrivers.emplace(ptr_materialDrivers_key->value, yordle::data::meta::deserialize<yordle::data::meta::IVfxMaterialDriver>(ptr_materialDrivers_value, 37724083u));
            }
        }
    }

    auto ptr_fieldCollectionDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(2924424250u);
    if(ptr_fieldCollectionDefinition != nullptr) {
        fieldCollectionDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxFieldCollectionDefinitionData>(ptr_fieldCollectionDefinition, 3149931448u);
    }

    auto ptr_materialOverrideDefinitions = prop->cast_prop<yordle::data::prop::set_prop>(858467462u);
    if(ptr_materialOverrideDefinitions != nullptr) {
        for(const auto &set_materialOverrideDefinitions_entry : ptr_materialOverrideDefinitions->value) {
            auto ptr_materialOverrideDefinitions_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_materialOverrideDefinitions_entry);
            if(ptr_materialOverrideDefinitions_entry != nullptr) {
                materialOverrideDefinitions.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::VfxMaterialOverrideDefinitionData>(ptr_materialOverrideDefinitions_entry, 3652726407u));
            }
        }
    }

    auto ptr_softParticleParams = prop->cast_prop<yordle::data::prop::structure_prop>(3216043997u);
    if(ptr_softParticleParams != nullptr) {
        softParticleParams = yordle::data::meta::deserialize<yordle::data::meta::VfxSoftParticleDefinitionData>(ptr_softParticleParams, 497696688u);
    }

    auto ptr_alphaErosionDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(3295031301u);
    if(ptr_alphaErosionDefinition != nullptr) {
        alphaErosionDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxAlphaErosionDefinitionData>(ptr_alphaErosionDefinition, 1585720219u);
    }

    auto ptr_paletteDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(2325872577u);
    if(ptr_paletteDefinition != nullptr) {
        paletteDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxPaletteDefinitionData>(ptr_paletteDefinition, 2829943575u);
    }

    auto ptr_reflectionDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(1064658893u);
    if(ptr_reflectionDefinition != nullptr) {
        reflectionDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxReflectionDefinitionData>(ptr_reflectionDefinition, 1091758723u);
    }

    auto ptr_distortionDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(3162545371u);
    if(ptr_distortionDefinition != nullptr) {
        distortionDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxDistortionDefinitionData>(ptr_distortionDefinition, 1238702953u);
    }

    auto ptr_emissionSurfaceDefinition = prop->cast_prop<yordle::data::prop::structure_prop>(1414715544u);
    if(ptr_emissionSurfaceDefinition != nullptr) {
        emissionSurfaceDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxEmissionSurfaceData>(ptr_emissionSurfaceDefinition, 3217219891u);
    }

    auto ptr_primitive = prop->cast_prop<yordle::data::prop::structure_prop>(8066294u);
    if(ptr_primitive != nullptr) {
        primitive = yordle::data::meta::deserialize<yordle::data::meta::VfxPrimitiveBase>(ptr_primitive, 3801322209u);
    }

    auto ptr_pass = prop->cast_prop<yordle::data::prop::int16_prop>(2071622424u);
    if(ptr_pass != nullptr) {
        pass = ptr_pass->value;
    }

    auto ptr_miscRenderFlags = prop->cast_prop<yordle::data::prop::uint8_prop>(1701035752u);
    if(ptr_miscRenderFlags != nullptr) {
        miscRenderFlags = ptr_miscRenderFlags->value;
    }

    auto ptr_meshRenderFlags = prop->cast_prop<yordle::data::prop::uint8_prop>(431879391u);
    if(ptr_meshRenderFlags != nullptr) {
        meshRenderFlags = ptr_meshRenderFlags->value;
    }

    auto ptr_colorRenderFlags = prop->cast_prop<yordle::data::prop::uint8_prop>(358556747u);
    if(ptr_colorRenderFlags != nullptr) {
        colorRenderFlags = ptr_colorRenderFlags->value;
    }

    auto ptr_stencilMode = prop->cast_prop<yordle::data::prop::uint8_prop>(451903612u);
    if(ptr_stencilMode != nullptr) {
        stencilMode = ptr_stencilMode->value;
    }

    auto ptr_stencilRef = prop->cast_prop<yordle::data::prop::uint8_prop>(2068046572u);
    if(ptr_stencilRef != nullptr) {
        stencilRef = ptr_stencilRef->value;
    }

    auto ptr_alphaRef = prop->cast_prop<yordle::data::prop::uint8_prop>(3113423092u);
    if(ptr_alphaRef != nullptr) {
        alphaRef = ptr_alphaRef->value;
    }

    auto ptr_depthBiasFactors = prop->cast_prop<yordle::data::prop::point_prop>(1739970345u);
    if(ptr_depthBiasFactors != nullptr) {
        depthBiasFactors = ptr_depthBiasFactors->value;
    }

    auto ptr_sliceTechniqueRange = prop->cast_prop<yordle::data::prop::float32_prop>(173979394u);
    if(ptr_sliceTechniqueRange != nullptr) {
        sliceTechniqueRange = ptr_sliceTechniqueRange->value;
    }

    auto ptr_texDiv = prop->cast_prop<yordle::data::prop::point_prop>(2259174665u);
    if(ptr_texDiv != nullptr) {
        texDiv = ptr_texDiv->value;
    }

    auto ptr_texDivMult = prop->cast_prop<yordle::data::prop::point_prop>(374036275u);
    if(ptr_texDivMult != nullptr) {
        texDivMult = ptr_texDivMult->value;
    }

    auto ptr_texture = prop->cast_prop<yordle::data::prop::string_prop>(1013213428u);
    if(ptr_texture != nullptr) {
        texture = ptr_texture->value;
    }

    auto ptr_textureMult = prop->cast_prop<yordle::data::prop::string_prop>(791583218u);
    if(ptr_textureMult != nullptr) {
        textureMult = ptr_textureMult->value;
    }

    auto ptr_particleColorTexture = prop->cast_prop<yordle::data::prop::string_prop>(3043919889u);
    if(ptr_particleColorTexture != nullptr) {
        particleColorTexture = ptr_particleColorTexture->value;
    }

    auto ptr_falloffTexture = prop->cast_prop<yordle::data::prop::string_prop>(2780351988u);
    if(ptr_falloffTexture != nullptr) {
        falloffTexture = ptr_falloffTexture->value;
    }

    auto ptr_texAddressModeMult = prop->cast_prop<yordle::data::prop::uint8_prop>(1529123847u);
    if(ptr_texAddressModeMult != nullptr) {
        texAddressModeMult = ptr_texAddressModeMult->value;
    }

    auto ptr_uvMode = prop->cast_prop<yordle::data::prop::uint8_prop>(642448697u);
    if(ptr_uvMode != nullptr) {
        uvMode = ptr_uvMode->value;
    }

    auto ptr_colorLookUpTypeX = prop->cast_prop<yordle::data::prop::uint8_prop>(628404258u);
    if(ptr_colorLookUpTypeX != nullptr) {
        colorLookUpTypeX = ptr_colorLookUpTypeX->value;
    }

    auto ptr_colorLookUpTypeY = prop->cast_prop<yordle::data::prop::uint8_prop>(645181877u);
    if(ptr_colorLookUpTypeY != nullptr) {
        colorLookUpTypeY = ptr_colorLookUpTypeY->value;
    }

    auto ptr_colorLookUpScales = prop->cast_prop<yordle::data::prop::point_prop>(4029404237u);
    if(ptr_colorLookUpScales != nullptr) {
        colorLookUpScales = ptr_colorLookUpScales->value;
    }

    auto ptr_colorLookUpOffsets = prop->cast_prop<yordle::data::prop::point_prop>(3445240382u);
    if(ptr_colorLookUpOffsets != nullptr) {
        colorLookUpOffsets = ptr_colorLookUpOffsets->value;
    }

    auto ptr_modulationFactor = prop->cast_prop<yordle::data::prop::quaternion_prop>(1704114260u);
    if(ptr_modulationFactor != nullptr) {
        modulationFactor = ptr_modulationFactor->value;
    }

    auto ptr_scaleBirthScaleByBoundObjectSize = prop->cast_prop<yordle::data::prop::float32_prop>(2500926249u);
    if(ptr_scaleBirthScaleByBoundObjectSize != nullptr) {
        scaleBirthScaleByBoundObjectSize = ptr_scaleBirthScaleByBoundObjectSize->value;
    }

    auto ptr_scaleBirthScaleByBoundObjectHeight = prop->cast_prop<yordle::data::prop::float32_prop>(3859373059u);
    if(ptr_scaleBirthScaleByBoundObjectHeight != nullptr) {
        scaleBirthScaleByBoundObjectHeight = ptr_scaleBirthScaleByBoundObjectHeight->value;
    }

    auto ptr_scaleBirthScaleByBoundObjectRadius = prop->cast_prop<yordle::data::prop::float32_prop>(942293422u);
    if(ptr_scaleBirthScaleByBoundObjectRadius != nullptr) {
        scaleBirthScaleByBoundObjectRadius = ptr_scaleBirthScaleByBoundObjectRadius->value;
    }

    auto ptr_keywordsExcluded = prop->cast_prop<yordle::data::prop::set_prop>(3245931207u);
    if(ptr_keywordsExcluded != nullptr) {
        for(const auto &set_keywordsExcluded_entry : ptr_keywordsExcluded->value) {
            auto ptr_keywordsExcluded_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_keywordsExcluded_entry);
            if(ptr_keywordsExcluded_entry != nullptr) {
                keywordsExcluded.emplace_back(ptr_keywordsExcluded_entry->value);
            }
        }
    }

    auto ptr_keywordsRequired = prop->cast_prop<yordle::data::prop::set_prop>(339958704u);
    if(ptr_keywordsRequired != nullptr) {
        for(const auto &set_keywordsRequired_entry : ptr_keywordsRequired->value) {
            auto ptr_keywordsRequired_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_keywordsRequired_entry);
            if(ptr_keywordsRequired_entry != nullptr) {
                keywordsRequired.emplace_back(ptr_keywordsRequired_entry->value);
            }
        }
    }

    auto ptr_keywordsIncluded = prop->cast_prop<yordle::data::prop::set_prop>(1204559849u);
    if(ptr_keywordsIncluded != nullptr) {
        for(const auto &set_keywordsIncluded_entry : ptr_keywordsIncluded->value) {
            auto ptr_keywordsIncluded_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_keywordsIncluded_entry);
            if(ptr_keywordsIncluded_entry != nullptr) {
                keywordsIncluded.emplace_back(ptr_keywordsIncluded_entry->value);
            }
        }
    }

    auto ptr_importance = prop->cast_prop<yordle::data::prop::uint8_prop>(3109120623u);
    if(ptr_importance != nullptr) {
        importance = ptr_importance->value;
    }

    auto ptr_censorPolicy = prop->cast_prop<yordle::data::prop::uint8_prop>(590183341u);
    if(ptr_censorPolicy != nullptr) {
        censorPolicy = ptr_censorPolicy->value;
    }

    auto ptr_spectatorPolicy = prop->cast_prop<yordle::data::prop::uint8_prop>(3864561452u);
    if(ptr_spectatorPolicy != nullptr) {
        spectatorPolicy = ptr_spectatorPolicy->value;
    }

    auto ptr_particleLingerType = prop->cast_prop<yordle::data::prop::uint8_prop>(948533348u);
    if(ptr_particleLingerType != nullptr) {
        particleLingerType = ptr_particleLingerType->value;
    }

    auto ptr_particleLifetime = prop->cast_prop<yordle::data::prop::inline_structure_prop>(710223508u);
    if(ptr_particleLifetime != nullptr) {
        particleLifetime = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_particleLifetime, 70254680u);
    }

    auto ptr_lifetime = prop->cast_prop<yordle::data::prop::optional_prop>(1376955374u);
    if(ptr_lifetime != nullptr) {
        auto ptr_lifetime_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_lifetime->value);
        if (ptr_lifetime_opt != nullptr) {
            lifetime = ptr_lifetime_opt->value;
        }
    }

    auto ptr_flexParticleLifetime = prop->cast_prop<yordle::data::prop::structure_prop>(1875177007u);
    if(ptr_flexParticleLifetime != nullptr) {
        flexParticleLifetime = yordle::data::meta::deserialize<yordle::data::meta::FlexValueFloat>(ptr_flexParticleLifetime, 1370198255u);
    }

    auto ptr_particleLinger = prop->cast_prop<yordle::data::prop::optional_prop>(607245356u);
    if(ptr_particleLinger != nullptr) {
        auto ptr_particleLinger_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_particleLinger->value);
        if (ptr_particleLinger_opt != nullptr) {
            particleLinger = ptr_particleLinger_opt->value;
        }
    }

    auto ptr_emitterLinger = prop->cast_prop<yordle::data::prop::optional_prop>(1002806966u);
    if(ptr_emitterLinger != nullptr) {
        auto ptr_emitterLinger_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_emitterLinger->value);
        if (ptr_emitterLinger_opt != nullptr) {
            emitterLinger = ptr_emitterLinger_opt->value;
        }
    }

    auto ptr_birthVelocity = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4198607757u);
    if(ptr_birthVelocity != nullptr) {
        birthVelocity = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthVelocity, 1759261366u);
    }

    auto ptr_flexBirthVelocity = prop->cast_prop<yordle::data::prop::structure_prop>(2673908472u);
    if(ptr_flexBirthVelocity != nullptr) {
        flexBirthVelocity = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector3>(ptr_flexBirthVelocity, 1113621825u);
    }

    auto ptr_flexScaleBirthScale = prop->cast_prop<yordle::data::prop::structure_prop>(729256261u);
    if(ptr_flexScaleBirthScale != nullptr) {
        flexScaleBirthScale = yordle::data::meta::deserialize<yordle::data::meta::FlexTypeFloat>(ptr_flexScaleBirthScale, 796686208u);
    }

    auto ptr_flexBirthUVScrollRate = prop->cast_prop<yordle::data::prop::structure_prop>(3188174315u);
    if(ptr_flexBirthUVScrollRate != nullptr) {
        flexBirthUVScrollRate = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector2>(ptr_flexBirthUVScrollRate, 1096844206u);
    }

    auto ptr_flexBirthUVScrollRateMult = prop->cast_prop<yordle::data::prop::structure_prop>(3083423149u);
    if(ptr_flexBirthUVScrollRateMult != nullptr) {
        flexBirthUVScrollRateMult = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector2>(ptr_flexBirthUVScrollRateMult, 1096844206u);
    }

    auto ptr_birthColor = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2211310241u);
    if(ptr_birthColor != nullptr) {
        birthColor = yordle::data::meta::deserialize<yordle::data::meta::ValueColor>(ptr_birthColor, 122655197u);
    }

    auto ptr_birthAcceleration = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2723004782u);
    if(ptr_birthAcceleration != nullptr) {
        birthAcceleration = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthAcceleration, 1759261366u);
    }

    auto ptr_birthRotationalAcceleration = prop->cast_prop<yordle::data::prop::inline_structure_prop>(922375025u);
    if(ptr_birthRotationalAcceleration != nullptr) {
        birthRotationalAcceleration = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthRotationalAcceleration, 1759261366u);
    }

    auto ptr_birthDrag = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2188761752u);
    if(ptr_birthDrag != nullptr) {
        birthDrag = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthDrag, 1759261366u);
    }

    auto ptr_birthOrbitalVelocity = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1363361524u);
    if(ptr_birthOrbitalVelocity != nullptr) {
        birthOrbitalVelocity = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthOrbitalVelocity, 1759261366u);
    }

    auto ptr_birthFrameRate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3319946389u);
    if(ptr_birthFrameRate != nullptr) {
        birthFrameRate = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthFrameRate, 70254680u);
    }

    auto ptr_birthUVOffset = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3105458730u);
    if(ptr_birthUVOffset != nullptr) {
        birthUVOffset = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_birthUVOffset, 1776038985u);
    }

    auto ptr_birthUVOffsetMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1946986944u);
    if(ptr_birthUVOffsetMult != nullptr) {
        birthUVOffsetMult = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_birthUVOffsetMult, 1776038985u);
    }

    auto ptr_flexBirthUVOffset = prop->cast_prop<yordle::data::prop::structure_prop>(617655883u);
    if(ptr_flexBirthUVOffset != nullptr) {
        flexBirthUVOffset = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector2>(ptr_flexBirthUVOffset, 1096844206u);
    }

    auto ptr_rate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2927860839u);
    if(ptr_rate != nullptr) {
        rate = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_rate, 70254680u);
    }

    auto ptr_rateByVelocityFunction = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1354185085u);
    if(ptr_rateByVelocityFunction != nullptr) {
        rateByVelocityFunction = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_rateByVelocityFunction, 1776038985u);
    }

    auto ptr_MaximumRateByVelocity = prop->cast_prop<yordle::data::prop::optional_prop>(3338279773u);
    if(ptr_MaximumRateByVelocity != nullptr) {
        auto ptr_MaximumRateByVelocity_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_MaximumRateByVelocity->value);
        if (ptr_MaximumRateByVelocity_opt != nullptr) {
            MaximumRateByVelocity = ptr_MaximumRateByVelocity_opt->value;
        }
    }

    auto ptr_flexRate = prop->cast_prop<yordle::data::prop::structure_prop>(1999564000u);
    if(ptr_flexRate != nullptr) {
        flexRate = yordle::data::meta::deserialize<yordle::data::meta::FlexValueFloat>(ptr_flexRate, 1370198255u);
    }

    auto ptr_timeBeforeFirstEmission = prop->cast_prop<yordle::data::prop::float32_prop>(585589692u);
    if(ptr_timeBeforeFirstEmission != nullptr) {
        timeBeforeFirstEmission = ptr_timeBeforeFirstEmission->value;
    }

    auto ptr_xcef2ba70 = prop->cast_prop<yordle::data::prop::float32_prop>(3472013936u);
    if(ptr_xcef2ba70 != nullptr) {
        xcef2ba70 = ptr_xcef2ba70->value;
    }

    auto ptr_timeActiveDuringPeriod = prop->cast_prop<yordle::data::prop::optional_prop>(400147918u);
    if(ptr_timeActiveDuringPeriod != nullptr) {
        auto ptr_timeActiveDuringPeriod_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_timeActiveDuringPeriod->value);
        if (ptr_timeActiveDuringPeriod_opt != nullptr) {
            timeActiveDuringPeriod = ptr_timeActiveDuringPeriod_opt->value;
        }
    }

    auto ptr_period = prop->cast_prop<yordle::data::prop::optional_prop>(2580104964u);
    if(ptr_period != nullptr) {
        auto ptr_period_opt = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::float32_prop>(ptr_period->value);
        if (ptr_period_opt != nullptr) {
            period = ptr_period_opt->value;
        }
    }

    auto ptr_shape = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2646858022u);
    if(ptr_shape != nullptr) {
        shape = yordle::data::meta::deserialize<yordle::data::meta::VfxShape>(ptr_shape, 2010092456u);
    }

    auto ptr_x4ffce322 = prop->cast_prop<yordle::data::prop::structure_prop>(1341973282u);
    if(ptr_x4ffce322 != nullptr) {
        x4ffce322 = yordle::data::meta::deserialize<yordle::data::meta::xb13097f0>(ptr_x4ffce322, 2972751856u);
    }

    auto ptr_flexOffset = prop->cast_prop<yordle::data::prop::structure_prop>(3808923573u);
    if(ptr_flexOffset != nullptr) {
        flexOffset = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector3>(ptr_flexOffset, 1113621825u);
    }

    auto ptr_startFrame = prop->cast_prop<yordle::data::prop::uint16_prop>(1996008740u);
    if(ptr_startFrame != nullptr) {
        startFrame = ptr_startFrame->value;
    }

    auto ptr_numFrames = prop->cast_prop<yordle::data::prop::uint16_prop>(510111985u);
    if(ptr_numFrames != nullptr) {
        numFrames = ptr_numFrames->value;
    }

    auto ptr_frameRate = prop->cast_prop<yordle::data::prop::float32_prop>(2601589476u);
    if(ptr_frameRate != nullptr) {
        frameRate = ptr_frameRate->value;
    }

    auto ptr_soundOnCreateName = prop->cast_prop<yordle::data::prop::string_prop>(2483486550u);
    if(ptr_soundOnCreateName != nullptr) {
        soundOnCreateName = ptr_soundOnCreateName->value;
    }

    auto ptr_voiceOverOnCreateName = prop->cast_prop<yordle::data::prop::string_prop>(1368414985u);
    if(ptr_voiceOverOnCreateName != nullptr) {
        voiceOverOnCreateName = ptr_voiceOverOnCreateName->value;
    }

    auto ptr_soundPersistentName = prop->cast_prop<yordle::data::prop::string_prop>(2596207722u);
    if(ptr_soundPersistentName != nullptr) {
        soundPersistentName = ptr_soundPersistentName->value;
    }

    auto ptr_voiceOverPersistentName = prop->cast_prop<yordle::data::prop::string_prop>(391068981u);
    if(ptr_voiceOverPersistentName != nullptr) {
        voiceOverPersistentName = ptr_voiceOverPersistentName->value;
    }

    auto ptr_censorModulateValue = prop->cast_prop<yordle::data::prop::quaternion_prop>(146090009u);
    if(ptr_censorModulateValue != nullptr) {
        censorModulateValue = ptr_censorModulateValue->value;
    }

    auto ptr_emissionMeshName = prop->cast_prop<yordle::data::prop::string_prop>(557171924u);
    if(ptr_emissionMeshName != nullptr) {
        emissionMeshName = ptr_emissionMeshName->value;
    }

    auto ptr_offsetLifetimeScaling = prop->cast_prop<yordle::data::prop::vector_prop>(1743020646u);
    if(ptr_offsetLifetimeScaling != nullptr) {
        offsetLifetimeScaling = ptr_offsetLifetimeScaling->value;
    }

    auto ptr_emitterUvScrollRate = prop->cast_prop<yordle::data::prop::point_prop>(1375800169u);
    if(ptr_emitterUvScrollRate != nullptr) {
        emitterUvScrollRate = ptr_emitterUvScrollRate->value;
    }

    auto ptr_emitterUvScrollRateMult = prop->cast_prop<yordle::data::prop::point_prop>(3785168275u);
    if(ptr_emitterUvScrollRateMult != nullptr) {
        emitterUvScrollRateMult = ptr_emitterUvScrollRateMult->value;
    }

    auto ptr_translationOverride = prop->cast_prop<yordle::data::prop::vector_prop>(3010264884u);
    if(ptr_translationOverride != nullptr) {
        translationOverride = ptr_translationOverride->value;
    }

    auto ptr_rotationOverride = prop->cast_prop<yordle::data::prop::vector_prop>(191882543u);
    if(ptr_rotationOverride != nullptr) {
        rotationOverride = ptr_rotationOverride->value;
    }

    auto ptr_scaleOverride = prop->cast_prop<yordle::data::prop::vector_prop>(240857825u);
    if(ptr_scaleOverride != nullptr) {
        scaleOverride = ptr_scaleOverride->value;
    }

    auto ptr_FlexInstanceScale = prop->cast_prop<yordle::data::prop::structure_prop>(2172495129u);
    if(ptr_FlexInstanceScale != nullptr) {
        FlexInstanceScale = yordle::data::meta::deserialize<yordle::data::meta::FlexTypeFloat>(ptr_FlexInstanceScale, 796686208u);
    }

    auto ptr_isRandomStartFrameMult = prop->cast_prop<yordle::data::prop::bit_prop>(274016829u);
    if(ptr_isRandomStartFrameMult != nullptr) {
        isRandomStartFrameMult = (ptr_isRandomStartFrameMult->value & 64) == 64;
    }

    auto ptr_isUniformScale = prop->cast_prop<yordle::data::prop::bit_prop>(895082843u);
    if(ptr_isUniformScale != nullptr) {
        isUniformScale = (ptr_isUniformScale->value & 8) == 8;
    }

    auto ptr_particleIsLocalOrientation = prop->cast_prop<yordle::data::prop::bit_prop>(937277300u);
    if(ptr_particleIsLocalOrientation != nullptr) {
        particleIsLocalOrientation = (ptr_particleIsLocalOrientation->value & 2) == 2;
    }

    auto ptr_doesCastShadow = prop->cast_prop<yordle::data::prop::bit_prop>(3038085223u);
    if(ptr_doesCastShadow != nullptr) {
        doesCastShadow = (ptr_doesCastShadow->value & 128) == 128;
    }

    auto ptr_isDirectionOriented = prop->cast_prop<yordle::data::prop::bit_prop>(3724322854u);
    if(ptr_isDirectionOriented != nullptr) {
        isDirectionOriented = (ptr_isDirectionOriented->value & 4) == 4;
    }

    auto ptr_isRandomStartFrame = prop->cast_prop<yordle::data::prop::bit_prop>(3768409787u);
    if(ptr_isRandomStartFrame != nullptr) {
        isRandomStartFrame = (ptr_isRandomStartFrame->value & 32) == 32;
    }

    auto ptr_uvScrollAlphaMult = prop->cast_prop<yordle::data::prop::bit_prop>(3946508263u);
    if(ptr_uvScrollAlphaMult != nullptr) {
        uvScrollAlphaMult = (ptr_uvScrollAlphaMult->value & 1) == 1;
    }

    auto ptr_hasPostRotateOrientation = prop->cast_prop<yordle::data::prop::bit_prop>(3985060700u);
    if(ptr_hasPostRotateOrientation != nullptr) {
        hasPostRotateOrientation = (ptr_hasPostRotateOrientation->value & 16) == 16;
    }

    auto ptr_isGroundLayer = prop->cast_prop<yordle::data::prop::bit_prop>(668207363u);
    if(ptr_isGroundLayer != nullptr) {
        isGroundLayer = (ptr_isGroundLayer->value & 16) == 16;
    }

    auto ptr_x676949a1 = prop->cast_prop<yordle::data::prop::bit_prop>(1734953377u);
    if(ptr_x676949a1 != nullptr) {
        x676949a1 = (ptr_x676949a1->value & 128) == 128;
    }

    auto ptr_uvScrollClampMult = prop->cast_prop<yordle::data::prop::bit_prop>(2059647136u);
    if(ptr_uvScrollClampMult != nullptr) {
        uvScrollClampMult = (ptr_uvScrollClampMult->value & 4) == 4;
    }

    auto ptr_useEmissionMeshNormalForBirth = prop->cast_prop<yordle::data::prop::bit_prop>(2074613737u);
    if(ptr_useEmissionMeshNormalForBirth != nullptr) {
        useEmissionMeshNormalForBirth = (ptr_useEmissionMeshNormalForBirth->value & 32) == 32;
    }

    auto ptr_isRotationEnabled = prop->cast_prop<yordle::data::prop::bit_prop>(2368611444u);
    if(ptr_isRotationEnabled != nullptr) {
        isRotationEnabled = (ptr_isRotationEnabled->value & 1) == 1;
    }

    auto ptr_uvScrollClamp = prop->cast_prop<yordle::data::prop::bit_prop>(2791509514u);
    if(ptr_uvScrollClamp != nullptr) {
        uvScrollClamp = (ptr_uvScrollClamp->value & 2) == 2;
    }

    auto ptr_isFollowingTerrain = prop->cast_prop<yordle::data::prop::bit_prop>(3131498697u);
    if(ptr_isFollowingTerrain != nullptr) {
        isFollowingTerrain = (ptr_isFollowingTerrain->value & 8) == 8;
    }

    auto ptr_useNavmeshMask = prop->cast_prop<yordle::data::prop::bit_prop>(3722305920u);
    if(ptr_useNavmeshMask != nullptr) {
        useNavmeshMask = (ptr_useNavmeshMask->value & 64) == 64;
    }

    auto ptr_isLocalOrientation = prop->cast_prop<yordle::data::prop::bit_prop>(719533490u);
    if(ptr_isLocalOrientation != nullptr) {
        isLocalOrientation = (ptr_isLocalOrientation->value & 32) == 32;
    }

    auto ptr_hasFixedOrbit = prop->cast_prop<yordle::data::prop::bit_prop>(874974657u);
    if(ptr_hasFixedOrbit != nullptr) {
        hasFixedOrbit = (ptr_hasFixedOrbit->value & 64) == 64;
    }

    auto ptr_isSingleParticle = prop->cast_prop<yordle::data::prop::bit_prop>(1119715179u);
    if(ptr_isSingleParticle != nullptr) {
        isSingleParticle = (ptr_isSingleParticle->value & 16) == 16;
    }

    auto ptr_x538effa4 = prop->cast_prop<yordle::data::prop::bit_prop>(1401880484u);
    if(ptr_x538effa4 != nullptr) {
        x538effa4 = (ptr_x538effa4->value & 8) == 8;
    }

    auto ptr_UseLingerScale = prop->cast_prop<yordle::data::prop::bit_prop>(1582117303u);
    if(ptr_UseLingerScale != nullptr) {
        UseLingerScale = (ptr_UseLingerScale->value & 4) == 4;
    }

    auto ptr_lockedToEmitter = prop->cast_prop<yordle::data::prop::bit_prop>(2575304460u);
    if(ptr_lockedToEmitter != nullptr) {
        lockedToEmitter = (ptr_lockedToEmitter->value & 128) == 128;
    }

    auto ptr_xbd9b83c7 = prop->cast_prop<yordle::data::prop::bit_prop>(3181085639u);
    if(ptr_xbd9b83c7 != nullptr) {
        xbd9b83c7 = (ptr_xbd9b83c7->value & 1) == 1;
    }

    auto ptr_UseLingerRotation = prop->cast_prop<yordle::data::prop::bit_prop>(3730513113u);
    if(ptr_UseLingerRotation != nullptr) {
        UseLingerRotation = (ptr_UseLingerRotation->value & 2) == 2;
    }

    auto ptr_doesParticleLifetimeScale = prop->cast_prop<yordle::data::prop::bit_prop>(283792845u);
    if(ptr_doesParticleLifetimeScale != nullptr) {
        doesParticleLifetimeScale = (ptr_doesParticleLifetimeScale->value & 32) == 32;
    }

    auto ptr_useLingerColor = prop->cast_prop<yordle::data::prop::bit_prop>(452491014u);
    if(ptr_useLingerColor != nullptr) {
        useLingerColor = (ptr_useLingerColor->value & 8) == 8;
    }

    auto ptr_UseLingerVelocity = prop->cast_prop<yordle::data::prop::bit_prop>(848541616u);
    if(ptr_UseLingerVelocity != nullptr) {
        UseLingerVelocity = (ptr_UseLingerVelocity->value & 2) == 2;
    }

    auto ptr_x51af37d2 = prop->cast_prop<yordle::data::prop::bit_prop>(1370437586u);
    if(ptr_x51af37d2 != nullptr) {
        x51af37d2 = (ptr_x51af37d2->value & 128) == 128;
    }

    auto ptr_doesLifetimeScale = prop->cast_prop<yordle::data::prop::bit_prop>(2041100123u);
    if(ptr_doesLifetimeScale != nullptr) {
        doesLifetimeScale = (ptr_doesLifetimeScale->value & 64) == 64;
    }

    auto ptr_UseLingerDrag = prop->cast_prop<yordle::data::prop::bit_prop>(3007716357u);
    if(ptr_UseLingerDrag != nullptr) {
        UseLingerDrag = (ptr_UseLingerDrag->value & 16) == 16;
    }

    auto ptr_UseLingerAcceleration = prop->cast_prop<yordle::data::prop::bit_prop>(4071846627u);
    if(ptr_UseLingerAcceleration != nullptr) {
        UseLingerAcceleration = (ptr_UseLingerAcceleration->value & 4) == 4;
    }

    auto ptr_scaleUpFromOrigin = prop->cast_prop<yordle::data::prop::bit_prop>(4190326694u);
    if(ptr_scaleUpFromOrigin != nullptr) {
        scaleUpFromOrigin = (ptr_scaleUpFromOrigin->value & 1) == 1;
    }

    auto ptr_postRotateOrientationAxis = prop->cast_prop<yordle::data::prop::vector_prop>(4198887203u);
    if(ptr_postRotateOrientationAxis != nullptr) {
        postRotateOrientationAxis = ptr_postRotateOrientationAxis->value;
    }

    auto ptr_birthUvScrollRate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3484878814u);
    if(ptr_birthUvScrollRate != nullptr) {
        birthUvScrollRate = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_birthUvScrollRate, 1776038985u);
    }

    auto ptr_birthUvScrollRateMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(842359924u);
    if(ptr_birthUvScrollRateMult != nullptr) {
        birthUvScrollRateMult = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_birthUvScrollRateMult, 1776038985u);
    }

    auto ptr_birthUvRotateRate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(849595928u);
    if(ptr_birthUvRotateRate != nullptr) {
        birthUvRotateRate = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthUvRotateRate, 70254680u);
    }

    auto ptr_birthUvRotateRateMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3988564566u);
    if(ptr_birthUvRotateRateMult != nullptr) {
        birthUvRotateRateMult = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthUvRotateRateMult, 70254680u);
    }

    auto ptr_uvRotation = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2525133280u);
    if(ptr_uvRotation != nullptr) {
        uvRotation = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_uvRotation, 70254680u);
    }

    auto ptr_x33b8543e = prop->cast_prop<yordle::data::prop::inline_structure_prop>(867718206u);
    if(ptr_x33b8543e != nullptr) {
        x33b8543e = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_x33b8543e, 70254680u);
    }

    auto ptr_particleUVScrollRate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1683889035u);
    if(ptr_particleUVScrollRate != nullptr) {
        particleUVScrollRate = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueVector2>(ptr_particleUVScrollRate, 1808563568u);
    }

    auto ptr_particleUVScrollRateMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1838660429u);
    if(ptr_particleUVScrollRateMult != nullptr) {
        particleUVScrollRateMult = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueVector2>(ptr_particleUVScrollRateMult, 1808563568u);
    }

    auto ptr_particleUVRotateRate = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3224963885u);
    if(ptr_particleUVRotateRate != nullptr) {
        particleUVRotateRate = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueFloat>(ptr_particleUVRotateRate, 3515916773u);
    }

    auto ptr_particleUVRotateRateMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(328812087u);
    if(ptr_particleUVRotateRateMult != nullptr) {
        particleUVRotateRateMult = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueFloat>(ptr_particleUVRotateRateMult, 3515916773u);
    }

    auto ptr_directionVelocityScale = prop->cast_prop<yordle::data::prop::float32_prop>(2061075621u);
    if(ptr_directionVelocityScale != nullptr) {
        directionVelocityScale = ptr_directionVelocityScale->value;
    }

    auto ptr_directionVelocityMinScale = prop->cast_prop<yordle::data::prop::float32_prop>(3956555907u);
    if(ptr_directionVelocityMinScale != nullptr) {
        directionVelocityMinScale = ptr_directionVelocityMinScale->value;
    }

    auto ptr_uvParallaxScale = prop->cast_prop<yordle::data::prop::float32_prop>(4137197537u);
    if(ptr_uvParallaxScale != nullptr) {
        uvParallaxScale = ptr_uvParallaxScale->value;
    }

    auto ptr_velocity = prop->cast_prop<yordle::data::prop::inline_structure_prop>(846470194u);
    if(ptr_velocity != nullptr) {
        velocity = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_velocity, 1759261366u);
    }

    auto ptr_acceleration = prop->cast_prop<yordle::data::prop::inline_structure_prop>(799062685u);
    if(ptr_acceleration != nullptr) {
        acceleration = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_acceleration, 1759261366u);
    }

    auto ptr_worldAcceleration = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3952758287u);
    if(ptr_worldAcceleration != nullptr) {
        worldAcceleration = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueVector3>(ptr_worldAcceleration, 1825341187u);
    }

    auto ptr_color = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1031692888u);
    if(ptr_color != nullptr) {
        color = yordle::data::meta::deserialize<yordle::data::meta::ValueColor>(ptr_color, 122655197u);
    }

    auto ptr_bindWeight = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3393217302u);
    if(ptr_bindWeight != nullptr) {
        bindWeight = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_bindWeight, 70254680u);
    }

    auto ptr_drag = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3096186179u);
    if(ptr_drag != nullptr) {
        drag = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_drag, 1759261366u);
    }

    auto ptr_lingerVelocity = prop->cast_prop<yordle::data::prop::inline_structure_prop>(160052109u);
    if(ptr_lingerVelocity != nullptr) {
        lingerVelocity = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_lingerVelocity, 1759261366u);
    }

    auto ptr_lingerAcceleration = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3751201134u);
    if(ptr_lingerAcceleration != nullptr) {
        lingerAcceleration = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_lingerAcceleration, 1759261366u);
    }

    auto ptr_lingerColor = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3922363041u);
    if(ptr_lingerColor != nullptr) {
        lingerColor = yordle::data::meta::deserialize<yordle::data::meta::ValueColor>(ptr_lingerColor, 122655197u);
    }

    auto ptr_lingerDrag = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4207272600u);
    if(ptr_lingerDrag != nullptr) {
        lingerDrag = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_lingerDrag, 1759261366u);
    }

    auto ptr_childParticleSetDefinition = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2687919304u);
    if(ptr_childParticleSetDefinition != nullptr) {
        childParticleSetDefinition = yordle::data::meta::deserialize<yordle::data::meta::VfxChildParticleSetDefinitionData>(ptr_childParticleSetDefinition, 3038774362u);
    }

    auto ptr_emissionMeshScale = prop->cast_prop<yordle::data::prop::float32_prop>(3182003607u);
    if(ptr_emissionMeshScale != nullptr) {
        emissionMeshScale = ptr_emissionMeshScale->value;
    }

    auto ptr_texAddressModeBase = prop->cast_prop<yordle::data::prop::uint8_prop>(844078864u);
    if(ptr_texAddressModeBase != nullptr) {
        texAddressModeBase = ptr_texAddressModeBase->value;
    }

    auto ptr_fixedOrbitType = prop->cast_prop<yordle::data::prop::uint8_prop>(3168650627u);
    if(ptr_fixedOrbitType != nullptr) {
        fixedOrbitType = ptr_fixedOrbitType->value;
    }

    auto ptr_orientation = prop->cast_prop<yordle::data::prop::uint8_prop>(3309681697u);
    if(ptr_orientation != nullptr) {
        orientation = ptr_orientation->value;
    }

    auto ptr_x2bf854fb = prop->cast_prop<yordle::data::prop::bit_prop>(737694971u);
    if(ptr_x2bf854fb != nullptr) {
        x2bf854fb = (ptr_x2bf854fb->value & 2) == 2;
    }

    auto ptr_x2cf8568e = prop->cast_prop<yordle::data::prop::bit_prop>(754472590u);
    if(ptr_x2cf8568e != nullptr) {
        x2cf8568e = (ptr_x2cf8568e->value & 1) == 1;
    }

    auto ptr_x38b0b8cc = prop->cast_prop<yordle::data::prop::bit_prop>(951105740u);
    if(ptr_x38b0b8cc != nullptr) {
        x38b0b8cc = (ptr_x38b0b8cc->value & 4) == 4;
    }

    auto ptr_x3bb0bd85 = prop->cast_prop<yordle::data::prop::bit_prop>(1001438597u);
    if(ptr_x3bb0bd85 != nullptr) {
        x3bb0bd85 = (ptr_x3bb0bd85->value & 8) == 8;
    }

    auto ptr_particleBind = prop->cast_prop<yordle::data::prop::point_prop>(1364523800u);
    if(ptr_particleBind != nullptr) {
        particleBind = ptr_particleBind->value;
    }

    auto ptr_scaleBias = prop->cast_prop<yordle::data::prop::point_prop>(1183217344u);
    if(ptr_scaleBias != nullptr) {
        scaleBias = ptr_scaleBias->value;
    }

    auto ptr_birthRotation0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1496514460u);
    if(ptr_birthRotation0 != nullptr) {
        birthRotation0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthRotation0, 1759261366u);
    }

    auto ptr_birthScale0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4041961604u);
    if(ptr_birthScale0 != nullptr) {
        birthScale0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthScale0, 1759261366u);
    }

    auto ptr_birthRotationalVelocity0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(494378602u);
    if(ptr_birthRotationalVelocity0 != nullptr) {
        birthRotationalVelocity0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_birthRotationalVelocity0, 1759261366u);
    }

    auto ptr_flexBirthRotationalVelocity0 = prop->cast_prop<yordle::data::prop::structure_prop>(2007555677u);
    if(ptr_flexBirthRotationalVelocity0 != nullptr) {
        flexBirthRotationalVelocity0 = yordle::data::meta::deserialize<yordle::data::meta::FlexValueVector3>(ptr_flexBirthRotationalVelocity0, 1113621825u);
    }

    auto ptr_scale0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3571546707u);
    if(ptr_scale0 != nullptr) {
        scale0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_scale0, 1759261366u);
    }

    auto ptr_rotation0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1898643901u);
    if(ptr_rotation0 != nullptr) {
        rotation0 = yordle::data::meta::deserialize<yordle::data::meta::IntegratedValueVector3>(ptr_rotation0, 1825341187u);
    }

    auto ptr_uvScale = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3990797128u);
    if(ptr_uvScale != nullptr) {
        uvScale = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_uvScale, 1776038985u);
    }

    auto ptr_uvScaleMult = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3440526982u);
    if(ptr_uvScaleMult != nullptr) {
        uvScaleMult = yordle::data::meta::deserialize<yordle::data::meta::ValueVector2>(ptr_uvScaleMult, 1776038985u);
    }

    auto ptr_uvTransformCenter = prop->cast_prop<yordle::data::prop::point_prop>(1989927343u);
    if(ptr_uvTransformCenter != nullptr) {
        uvTransformCenter = ptr_uvTransformCenter->value;
    }

    auto ptr_uvTransformCenterMult = prop->cast_prop<yordle::data::prop::point_prop>(947681201u);
    if(ptr_uvTransformCenterMult != nullptr) {
        uvTransformCenterMult = ptr_uvTransformCenterMult->value;
    }

    auto ptr_LingerRotation0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1751193500u);
    if(ptr_LingerRotation0 != nullptr) {
        LingerRotation0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_LingerRotation0, 1759261366u);
    }

    auto ptr_LingerScale0 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2106505348u);
    if(ptr_LingerScale0 != nullptr) {
        LingerScale0 = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_LingerScale0, 1759261366u);
    }

    auto ptr_birthRotation1 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1513292079u);
    if(ptr_birthRotation1 != nullptr) {
        birthRotation1 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthRotation1, 70254680u);
    }

    auto ptr_birthScale1 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4058739223u);
    if(ptr_birthScale1 != nullptr) {
        birthScale1 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthScale1, 70254680u);
    }

    auto ptr_birthRotationalVelocity1 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(511156221u);
    if(ptr_birthRotationalVelocity1 != nullptr) {
        birthRotationalVelocity1 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_birthRotationalVelocity1, 70254680u);
    }

    auto ptr_flexBirthRotationalVelocity1 = prop->cast_prop<yordle::data::prop::structure_prop>(1990778058u);
    if(ptr_flexBirthRotationalVelocity1 != nullptr) {
        flexBirthRotationalVelocity1 = yordle::data::meta::deserialize<yordle::data::meta::FlexValueFloat>(ptr_flexBirthRotationalVelocity1, 1370198255u);
    }

    auto ptr_uvScrollRate1 = prop->cast_prop<yordle::data::prop::point_prop>(542661344u);
    if(ptr_uvScrollRate1 != nullptr) {
        uvScrollRate1 = ptr_uvScrollRate1->value;
    }

    auto ptr_scale1 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3554769088u);
    if(ptr_scale1 != nullptr) {
        scale1 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_scale1, 70254680u);
    }

    auto ptr_rotation1 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1881866282u);
    if(ptr_rotation1 != nullptr) {
        rotation1 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_rotation1, 70254680u);
    }
}
