/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/VfxPaletteDefinitionData.hpp>

#include <yordle/data/meta/bin_defs/ValueColor.hpp>
#include <yordle/data/meta/bin_defs/ValueVector3.hpp>
#include <yordle/data/meta/bin_defs/ValueFloat.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::VfxPaletteDefinitionData::VfxPaletteDefinitionData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_paletteTexture = prop->cast_prop<yordle::data::prop::string_prop>(4289139195u);
    if(ptr_paletteTexture != nullptr) {
        paletteTexture = ptr_paletteTexture->value;
    }

    auto ptr_PaletteTextureAddressMode = prop->cast_prop<yordle::data::prop::uint8_prop>(91092758u);
    if(ptr_PaletteTextureAddressMode != nullptr) {
        PaletteTextureAddressMode = ptr_PaletteTextureAddressMode->value;
    }

    auto ptr_palleteSrcMixColor = prop->cast_prop<yordle::data::prop::inline_structure_prop>(339674833u);
    if(ptr_palleteSrcMixColor != nullptr) {
        palleteSrcMixColor = yordle::data::meta::deserialize<yordle::data::meta::ValueColor>(ptr_palleteSrcMixColor, 122655197u);
    }

    auto ptr_paletteSelector = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2345951285u);
    if(ptr_paletteSelector != nullptr) {
        paletteSelector = yordle::data::meta::deserialize<yordle::data::meta::ValueVector3>(ptr_paletteSelector, 1759261366u);
    }

    auto ptr_x34d8fac6 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(886635206u);
    if(ptr_x34d8fac6 != nullptr) {
        x34d8fac6 = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_x34d8fac6, 70254680u);
    }

    auto ptr_x44fd44cb = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1157448907u);
    if(ptr_x44fd44cb != nullptr) {
        x44fd44cb = yordle::data::meta::deserialize<yordle::data::meta::ValueFloat>(ptr_x44fd44cb, 70254680u);
    }

    auto ptr_paletteCount = prop->cast_prop<yordle::data::prop::int32_prop>(2656188463u);
    if(ptr_paletteCount != nullptr) {
        paletteCount = ptr_paletteCount->value;
    }
}
