/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x1bca1a5e.hpp>

#include <yordle/data/meta/bin_defs/x32ea23b7.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x1bca1a5e::x1bca1a5e(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xff1455b7 = prop->cast_prop<yordle::data::prop::structure_prop>(4279522743u);
    if(ptr_xff1455b7 != nullptr) {
        xff1455b7 = yordle::data::meta::deserialize<yordle::data::meta::x32ea23b7>(ptr_xff1455b7, 854205367u);
    }

    auto ptr_x907be531 = prop->cast_prop<yordle::data::prop::bool_prop>(2424038705u);
    if(ptr_x907be531 != nullptr) {
        x907be531 = ptr_x907be531->value;
    }

    auto ptr_Backdrop = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2478896375u);
    if(ptr_Backdrop != nullptr) {
        Backdrop = ptr_Backdrop->value;
    }

    auto ptr_xd4080da5 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3557297573u);
    if(ptr_xd4080da5 != nullptr) {
        xd4080da5 = ptr_xd4080da5->value;
    }

    auto ptr_xaf3b2421 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2939888673u);
    if(ptr_xaf3b2421 != nullptr) {
        xaf3b2421 = ptr_xaf3b2421->value;
    }
}
