/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x1e18eebe.hpp>

#include <yordle/data/meta/bin_defs/x522ba90a.hpp>
#include <yordle/data/meta/bin_defs/xbcdc9113.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x1e18eebe::x1e18eebe(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::xbcdc9113(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x61e47ab2 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1642363570u);
    if(ptr_x61e47ab2 != nullptr) {
        x61e47ab2 = ptr_x61e47ab2->value;
    }

    auto ptr_xd4080da5 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3557297573u);
    if(ptr_xd4080da5 != nullptr) {
        xd4080da5 = ptr_xd4080da5->value;
    }

    auto ptr_x82b638b9 = prop->cast_prop<yordle::data::prop::set_prop>(2192980153u);
    if(ptr_x82b638b9 != nullptr) {
        for(const auto &set_x82b638b9_entry : ptr_x82b638b9->value) {
            auto ptr_x82b638b9_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_x82b638b9_entry);
            if(ptr_x82b638b9_entry != nullptr) {
                x82b638b9.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::x522ba90a>(ptr_x82b638b9_entry, 1378593034u));
            }
        }
    }

    auto ptr_x3ba1659e = prop->cast_prop<yordle::data::prop::float32_prop>(1000433054u);
    if(ptr_x3ba1659e != nullptr) {
        x3ba1659e = ptr_x3ba1659e->value;
    }
}
