/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x242fe438.hpp>

#include <yordle/data/meta/bin_defs/x99e777d.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x242fe438::x242fe438(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Group = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1605967500u);
    if(ptr_Group != nullptr) {
        Group = ptr_Group->value;
    }

    auto ptr_Icon = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3862959600u);
    if(ptr_Icon != nullptr) {
        Icon = ptr_Icon->value;
    }

    auto ptr_x944d842 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(155506754u);
    if(ptr_x944d842 != nullptr) {
        x944d842 = ptr_x944d842->value;
    }

    auto ptr_x558c76b4 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1435268788u);
    if(ptr_x558c76b4 != nullptr) {
        x558c76b4 = ptr_x558c76b4->value;
    }

    auto ptr_xe5b78177 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3854008695u);
    if(ptr_xe5b78177 != nullptr) {
        xe5b78177 = ptr_xe5b78177->value;
    }

    auto ptr_textures = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2567998597u);
    if(ptr_textures != nullptr) {
        textures = yordle::data::meta::deserialize<yordle::data::meta::x99e777d>(ptr_textures, 161380221u);
    }
}
