/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x2dfb2488.hpp>

#include <yordle/data/meta/bin_defs/x15793a8c.hpp>
#include <yordle/data/meta/bin_defs/xa5f32abe.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x2dfb2488::x2dfb2488(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::xa5f32abe(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xc43e335a = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3292410714u);
    if(ptr_xc43e335a != nullptr) {
        xc43e335a = yordle::data::meta::deserialize<yordle::data::meta::x15793a8c>(ptr_xc43e335a, 360266380u);
    }
}
