/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x3c8d0b5d.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x3c8d0b5d::x3c8d0b5d(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x7521711d = prop->cast_prop<yordle::data::prop::set_prop>(1965125917u);
    if(ptr_x7521711d != nullptr) {
        auto index_x7521711d = 0;
        for(const auto &set_x7521711d_entry : ptr_x7521711d->value) {
            auto ptr_x7521711d_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_x7521711d_entry);
            if(ptr_x7521711d_entry != nullptr) {
                x7521711d[index_x7521711d] = ptr_x7521711d_entry->value;
            }
            index_x7521711d++;
        }
    }
}
