/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x3e59e2ca.hpp>

#include <yordle/data/meta/bin_defs/IOptionItemFilter.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x3e59e2ca::x3e59e2ca(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IOptionItemFilter(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x7b98ffdd = prop->cast_prop<yordle::data::prop::bool_prop>(2073624541u);
    if(ptr_x7b98ffdd != nullptr) {
        x7b98ffdd = ptr_x7b98ffdd->value;
    }

    auto ptr_x812748a2 = prop->cast_prop<yordle::data::prop::bool_prop>(2166835362u);
    if(ptr_x812748a2 != nullptr) {
        x812748a2 = ptr_x812748a2->value;
    }

    auto ptr_x37985b59 = prop->cast_prop<yordle::data::prop::bool_prop>(932731737u);
    if(ptr_x37985b59 != nullptr) {
        x37985b59 = ptr_x37985b59->value;
    }
}
