/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x45652c20.hpp>

#include <yordle/data/meta/bin_defs/x61c3629.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x45652c20::x45652c20(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::x61c3629(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Icon = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3862959600u);
    if(ptr_Icon != nullptr) {
        Icon = ptr_Icon->value;
    }

    auto ptr_xf5b8026a = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4122477162u);
    if(ptr_xf5b8026a != nullptr) {
        xf5b8026a = ptr_xf5b8026a->value;
    }

    auto ptr_xece4b81e = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3974412318u);
    if(ptr_xece4b81e != nullptr) {
        xece4b81e = ptr_xece4b81e->value;
    }

    auto ptr_HitRegion = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4092291606u);
    if(ptr_HitRegion != nullptr) {
        HitRegion = ptr_HitRegion->value;
    }
}
