/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x48c9ff38.hpp>

#include <yordle/data/meta/bin_defs/AnnouncementIcon.hpp>
#include <yordle/data/meta/bin_defs/AnnouncementStyleBasic.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x48c9ff38::x48c9ff38(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::AnnouncementStyleBasic(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_SourceIcon = prop->cast_prop<yordle::data::prop::reference_prop>(2120735593u);
    if(ptr_SourceIcon != nullptr) {
        SourceIcon = yordle::data::meta::bin_ref<yordle::data::meta::AnnouncementIcon>(728839351u, ptr_SourceIcon->value);
    }
}
