/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x4fe40e4a.hpp>

#include <yordle/data/meta/bin_defs/Cheat.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x4fe40e4a::x4fe40e4a(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::Cheat(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Target = prop->cast_prop<yordle::data::prop::uint32_prop>(845187144u);
    if(ptr_Target != nullptr) {
        Target = ptr_Target->value;
    }

    auto ptr_x5083dbe2 = prop->cast_prop<yordle::data::prop::float32_prop>(1350818786u);
    if(ptr_x5083dbe2 != nullptr) {
        x5083dbe2 = ptr_x5083dbe2->value;
    }

    auto ptr_xf79bcddf = prop->cast_prop<yordle::data::prop::bool_prop>(4154183135u);
    if(ptr_xf79bcddf != nullptr) {
        xf79bcddf = ptr_xf79bcddf->value;
    }
}
