/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x5289f880.hpp>

#include <yordle/data/meta/bin_defs/xc2da185a.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x5289f880::x5289f880(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::xc2da185a(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_type = prop->cast_prop<yordle::data::prop::uint8_prop>(1361572173u);
    if(ptr_type != nullptr) {
        type = ptr_type->value;
    }

    auto ptr_lightColor = prop->cast_prop<yordle::data::prop::quaternion_prop>(1953294142u);
    if(ptr_lightColor != nullptr) {
        lightColor = ptr_lightColor->value;
    }

    auto ptr_intensityScale = prop->cast_prop<yordle::data::prop::float32_prop>(1015244992u);
    if(ptr_intensityScale != nullptr) {
        intensityScale = ptr_intensityScale->value;
    }

    auto ptr_radius = prop->cast_prop<yordle::data::prop::float32_prop>(230313139u);
    if(ptr_radius != nullptr) {
        radius = ptr_radius->value;
    }

    auto ptr_xc7334a55 = prop->cast_prop<yordle::data::prop::float32_prop>(3342027349u);
    if(ptr_xc7334a55 != nullptr) {
        xc7334a55 = ptr_xc7334a55->value;
    }

    auto ptr_Impact = prop->cast_prop<yordle::data::prop::uint8_prop>(510767767u);
    if(ptr_Impact != nullptr) {
        Impact = ptr_Impact->value;
    }
}
