/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x58e072e0.hpp>

#include <yordle/data/meta/bin_defs/x59dc4713.hpp>
#include <yordle/data/meta/bin_defs/x580644e.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x58e072e0::x58e072e0(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::x580644e(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xe095d841 = prop->cast_prop<yordle::data::prop::string_prop>(3767916609u);
    if(ptr_xe095d841 != nullptr) {
        xe095d841 = ptr_xe095d841->value;
    }

    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_x43e53626 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1139095078u);
    if(ptr_x43e53626 != nullptr) {
        x43e53626 = ptr_x43e53626->value;
    }

    auto ptr_xa76f8e16 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2809105942u);
    if(ptr_xa76f8e16 != nullptr) {
        xa76f8e16 = ptr_xa76f8e16->value;
    }

    auto ptr_x16904044 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(378552388u);
    if(ptr_x16904044 != nullptr) {
        x16904044 = ptr_x16904044->value;
    }

    auto ptr_xe7569bc = prop->cast_prop<yordle::data::prop::inline_structure_prop>(242575804u);
    if(ptr_xe7569bc != nullptr) {
        xe7569bc = yordle::data::meta::deserialize<yordle::data::meta::x59dc4713>(ptr_xe7569bc, 1507608339u);
    }
}
