/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x5b9614dc.hpp>

#include <yordle/data/meta/bin_defs/TargetingTypeData.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x5b9614dc::x5b9614dc(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::TargetingTypeData(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xbb4a1111 = prop->cast_prop<yordle::data::prop::float32_prop>(3142193425u);
    if(ptr_xbb4a1111 != nullptr) {
        xbb4a1111 = ptr_xbb4a1111->value;
    }
}
