/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x65ed244.hpp>

#include <yordle/data/meta/bin_defs/x1c494c09.hpp>
#include <yordle/data/meta/bin_defs/Character.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x65ed244::x65ed244(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IFxAction(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Location = prop->cast_prop<yordle::data::prop::structure_prop>(200649126u);
    if(ptr_Location != nullptr) {
        Location = yordle::data::meta::deserialize<yordle::data::meta::x1c494c09>(ptr_Location, 474565641u);
    }

    auto ptr_Character = prop->cast_prop<yordle::data::prop::reference_prop>(2335876880u);
    if(ptr_Character != nullptr) {
        Character = yordle::data::meta::bin_ref<yordle::data::meta::Character>(2335876880u, ptr_Character->value);
    }

    auto ptr_SkinID = prop->cast_prop<yordle::data::prop::uint32_prop>(2067069477u);
    if(ptr_SkinID != nullptr) {
        SkinID = ptr_SkinID->value;
    }

    auto ptr_x64fe3d2f = prop->cast_prop<yordle::data::prop::uint32_prop>(1694383407u);
    if(ptr_x64fe3d2f != nullptr) {
        x64fe3d2f = ptr_x64fe3d2f->value;
    }

    auto ptr_priority = prop->cast_prop<yordle::data::prop::uint8_prop>(2498028297u);
    if(ptr_priority != nullptr) {
        priority = ptr_priority->value;
    }

    auto ptr_x6495fab8 = prop->cast_prop<yordle::data::prop::string_prop>(1687550648u);
    if(ptr_x6495fab8 != nullptr) {
        x6495fab8 = ptr_x6495fab8->value;
    }

    auto ptr_xd65e723c = prop->cast_prop<yordle::data::prop::string_prop>(3596513852u);
    if(ptr_xd65e723c != nullptr) {
        xd65e723c = ptr_xd65e723c->value;
    }
}
