/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x682de9e7.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x682de9e7::x682de9e7(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x43b27471 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1135768689u);
    if(ptr_x43b27471 != nullptr) {
        x43b27471 = ptr_x43b27471->value;
    }

    auto ptr_xbdd80f6 = prop->cast_prop<yordle::data::prop::string_prop>(199065846u);
    if(ptr_xbdd80f6 != nullptr) {
        xbdd80f6 = ptr_xbdd80f6->value;
    }

    auto ptr_x29ce6f56 = prop->cast_prop<yordle::data::prop::uint32_prop>(701394774u);
    if(ptr_x29ce6f56 != nullptr) {
        x29ce6f56 = ptr_x29ce6f56->value;
    }
}
