/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x795bfcc0.hpp>

#include <yordle/data/meta/bin_defs/x186be64c.hpp>
#include <yordle/data/meta/bin_defs/x8eba574f.hpp>
#include <yordle/data/meta/bin_defs/x1bca1a5e.hpp>
#include <yordle/data/meta/bin_defs/x34270fce.hpp>
#include <yordle/data/meta/bin_defs/xbb59fd4.hpp>
#include <yordle/data/meta/bin_defs/xf535ab5.hpp>
#include <yordle/data/meta/bin_defs/xb78525db.hpp>
#include <yordle/data/meta/bin_defs/xff5d83bd.hpp>
#include <yordle/data/meta/bin_defs/x486e38ec.hpp>
#include <yordle/data/meta/bin_defs/xa914101a.hpp>
#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x795bfcc0::x795bfcc0(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_xad2db494 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2905453716u);
    if(ptr_xad2db494 != nullptr) {
        xad2db494 = ptr_xad2db494->value;
    }

    auto ptr_Portrait = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(806924506u);
    if(ptr_Portrait != nullptr) {
        Portrait = ptr_Portrait->value;
    }

    auto ptr_x4e85c5c4 = prop->cast_prop<yordle::data::prop::bool_prop>(1317389764u);
    if(ptr_x4e85c5c4 != nullptr) {
        x4e85c5c4 = ptr_x4e85c5c4->value;
    }

    auto ptr_x186be64c = prop->cast_prop<yordle::data::prop::inline_structure_prop>(409724492u);
    if(ptr_x186be64c != nullptr) {
        x186be64c = yordle::data::meta::deserialize<yordle::data::meta::x186be64c>(ptr_x186be64c, 409724492u);
    }

    auto ptr_xc03c708a = prop->cast_prop<yordle::data::prop::structure_prop>(3225186442u);
    if(ptr_xc03c708a != nullptr) {
        xc03c708a = yordle::data::meta::deserialize<yordle::data::meta::x8eba574f>(ptr_xc03c708a, 2394576719u);
    }

    auto ptr_x35d8178d = prop->cast_prop<yordle::data::prop::inline_structure_prop>(903354253u);
    if(ptr_x35d8178d != nullptr) {
        x35d8178d = yordle::data::meta::deserialize<yordle::data::meta::x1bca1a5e>(ptr_x35d8178d, 466229854u);
    }

    auto ptr_x53a54b1e = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1403341598u);
    if(ptr_x53a54b1e != nullptr) {
        x53a54b1e = ptr_x53a54b1e->value;
    }

    auto ptr_xe0b29ef4 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3769802484u);
    if(ptr_xe0b29ef4 != nullptr) {
        xe0b29ef4 = yordle::data::meta::deserialize<yordle::data::meta::x34270fce>(ptr_xe0b29ef4, 874975182u);
    }

    auto ptr_x4e1babb4 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1310436276u);
    if(ptr_x4e1babb4 != nullptr) {
        x4e1babb4 = yordle::data::meta::deserialize<yordle::data::meta::x34270fce>(ptr_x4e1babb4, 874975182u);
    }

    auto ptr_xf71e50d6 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4145959126u);
    if(ptr_xf71e50d6 != nullptr) {
        xf71e50d6 = yordle::data::meta::deserialize<yordle::data::meta::xbb59fd4>(ptr_xf71e50d6, 196452308u);
    }

    auto ptr_xac5665a7 = prop->cast_prop<yordle::data::prop::structure_prop>(2891343271u);
    if(ptr_xac5665a7 != nullptr) {
        xac5665a7 = yordle::data::meta::deserialize<yordle::data::meta::xf535ab5>(ptr_xac5665a7, 257120949u);
    }

    auto ptr_x8b2e412d = prop->cast_prop<yordle::data::prop::structure_prop>(2335064365u);
    if(ptr_x8b2e412d != nullptr) {
        x8b2e412d = yordle::data::meta::deserialize<yordle::data::meta::xb78525db>(ptr_x8b2e412d, 3078956507u);
    }

    auto ptr_x2067de5d = prop->cast_prop<yordle::data::prop::inline_structure_prop>(543678045u);
    if(ptr_x2067de5d != nullptr) {
        x2067de5d = yordle::data::meta::deserialize<yordle::data::meta::xff5d83bd>(ptr_x2067de5d, 4284318653u);
    }

    auto ptr_xf0e72c76 = prop->cast_prop<yordle::data::prop::unordered_set_prop>(4041682038u);
    if(ptr_xf0e72c76 != nullptr) {
        for(const auto &set_xf0e72c76_entry : ptr_xf0e72c76->value) {
            auto ptr_xf0e72c76_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::structure_prop>(set_xf0e72c76_entry);
            if(ptr_xf0e72c76_entry != nullptr) {
                xf0e72c76.emplace_back(yordle::data::meta::deserialize<yordle::data::meta::x486e38ec>(ptr_xf0e72c76_entry, 1215183084u));
            }
        }
    }

    auto ptr_x89eec19c = prop->cast_prop<yordle::data::prop::structure_prop>(2314125724u);
    if(ptr_x89eec19c != nullptr) {
        x89eec19c = yordle::data::meta::deserialize<yordle::data::meta::xa914101a>(ptr_x89eec19c, 2836664346u);
    }

    auto ptr_xe095d841 = prop->cast_prop<yordle::data::prop::string_prop>(3767916609u);
    if(ptr_xe095d841 != nullptr) {
        xe095d841 = ptr_xe095d841->value;
    }
}
