/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/x8558dd6d.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::x8558dd6d::x8558dd6d(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x54222157 = prop->cast_prop<yordle::data::prop::float32_prop>(1411522903u);
    if(ptr_x54222157 != nullptr) {
        x54222157 = ptr_x54222157->value;
    }

    auto ptr_xa40f930a = prop->cast_prop<yordle::data::prop::float32_prop>(2752484106u);
    if(ptr_xa40f930a != nullptr) {
        xa40f930a = ptr_xa40f930a->value;
    }

    auto ptr_xaa32e168 = prop->cast_prop<yordle::data::prop::bool_prop>(2855461224u);
    if(ptr_xaa32e168 != nullptr) {
        xaa32e168 = ptr_xaa32e168->value;
    }

    auto ptr_x61cc66ee = prop->cast_prop<yordle::data::prop::bool_prop>(1640785646u);
    if(ptr_x61cc66ee != nullptr) {
        x61cc66ee = ptr_x61cc66ee->value;
    }
}
