/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xa44b28c0.hpp>

#include <yordle/data/meta/bin_defs/x2aa61eb4.hpp>
#include <yordle/data/meta/bin_defs/x94e53457.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xa44b28c0::xa44b28c0(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xd563e1e9 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3580092905u);
    if(ptr_xd563e1e9 != nullptr) {
        xd563e1e9 = ptr_xd563e1e9->value;
    }

    auto ptr_xfd894807 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4253632519u);
    if(ptr_xfd894807 != nullptr) {
        xfd894807 = ptr_xfd894807->value;
    }

    auto ptr_x7ff19d0c = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2146540812u);
    if(ptr_x7ff19d0c != nullptr) {
        x7ff19d0c = ptr_x7ff19d0c->value;
    }

    auto ptr_Dragons = prop->cast_prop<yordle::data::prop::map_prop>(4001738135u);
    if(ptr_Dragons != nullptr) {
        for(const auto &set_Dragons_pair : ptr_Dragons->value) {
            auto ptr_Dragons_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::fnv_hash_prop>(set_Dragons_pair.first);
            auto ptr_Dragons_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_Dragons_pair.second);
            if(ptr_Dragons_key != nullptr && ptr_Dragons_value != nullptr) {
                Dragons.emplace(ptr_Dragons_key->value, yordle::data::meta::deserialize<yordle::data::meta::x2aa61eb4>(ptr_Dragons_value, 715529908u));
            }
        }
    }

    auto ptr_x42331f2a = prop->cast_prop<yordle::data::prop::set_prop>(1110646570u);
    if(ptr_x42331f2a != nullptr) {
        auto index_x42331f2a = 0;
        for(const auto &set_x42331f2a_entry : ptr_x42331f2a->value) {
            auto ptr_x42331f2a_entry = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::inline_structure_prop>(set_x42331f2a_entry);
            if(ptr_x42331f2a_entry != nullptr) {
                x42331f2a[index_x42331f2a] = yordle::data::meta::deserialize<yordle::data::meta::x94e53457>(ptr_x42331f2a_entry, 2498049111u);
            }
            index_x42331f2a++;
        }
    }
}
