/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xa56cc36d.hpp>

#include <yordle/data/meta/bin_defs/xf795f405.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xa56cc36d::xa56cc36d(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::xf795f405(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x43b27471 = prop->cast_prop<yordle::data::prop::uint32_prop>(1135768689u);
    if(ptr_x43b27471 != nullptr) {
        x43b27471 = ptr_x43b27471->value;
    }
}
