/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xa5f32abe.hpp>

#include <yordle/data/meta/bin_defs/x17b19502.hpp>
#include <yordle/data/meta/bin_defs/xa89e6d1e.hpp>
#include <yordle/data/meta/bin_defs/x2fae5ced.hpp>
#include <yordle/data/meta/bin_defs/x604da433.hpp>
#include <yordle/data/meta/bin_defs/xa502a9f5.hpp>
#include <yordle/data/meta/bin_defs/xc0b50425.hpp>
#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xa5f32abe::xa5f32abe(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_x4671ae97 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1181855383u);
    if(ptr_x4671ae97 != nullptr) {
        x4671ae97 = yordle::data::meta::deserialize<yordle::data::meta::x17b19502>(ptr_x4671ae97, 397513986u);
    }

    auto ptr_x4babd89d = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1269553309u);
    if(ptr_x4babd89d != nullptr) {
        x4babd89d = yordle::data::meta::deserialize<yordle::data::meta::xa89e6d1e>(ptr_x4babd89d, 2828954910u);
    }

    auto ptr_x9a942af = prop->cast_prop<yordle::data::prop::inline_structure_prop>(162087599u);
    if(ptr_x9a942af != nullptr) {
        x9a942af = yordle::data::meta::deserialize<yordle::data::meta::x2fae5ced>(ptr_x9a942af, 799956205u);
    }

    auto ptr_xf2fb8359 = prop->cast_prop<yordle::data::prop::inline_structure_prop>(4076569433u);
    if(ptr_xf2fb8359 != nullptr) {
        xf2fb8359 = yordle::data::meta::deserialize<yordle::data::meta::x604da433>(ptr_xf2fb8359, 1615701043u);
    }

    auto ptr_x6b3178fb = prop->cast_prop<yordle::data::prop::inline_structure_prop>(1798404347u);
    if(ptr_x6b3178fb != nullptr) {
        x6b3178fb = yordle::data::meta::deserialize<yordle::data::meta::xa502a9f5>(ptr_x6b3178fb, 2768415221u);
    }

    auto ptr_x7b10d5cb = prop->cast_prop<yordle::data::prop::inline_structure_prop>(2064700875u);
    if(ptr_x7b10d5cb != nullptr) {
        x7b10d5cb = yordle::data::meta::deserialize<yordle::data::meta::xc0b50425>(ptr_x7b10d5cb, 3233088549u);
    }

    auto ptr_xe095d841 = prop->cast_prop<yordle::data::prop::string_prop>(3767916609u);
    if(ptr_xe095d841 != nullptr) {
        xe095d841 = ptr_xe095d841->value;
    }
}
