/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xb1757147.hpp>

#include <yordle/data/meta/bin_defs/x5c086dbd.hpp>
#include <yordle/data/meta/bin_defs/VfxSystemDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xb1757147::xb1757147(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::IFxAction(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xb8c60cba = prop->cast_prop<yordle::data::prop::inline_structure_prop>(3099987130u);
    if(ptr_xb8c60cba != nullptr) {
        xb8c60cba = yordle::data::meta::deserialize<yordle::data::meta::x5c086dbd>(ptr_xb8c60cba, 1544056253u);
    }

    auto ptr_Particle = prop->cast_prop<yordle::data::prop::reference_prop>(2324120511u);
    if(ptr_Particle != nullptr) {
        Particle = yordle::data::meta::bin_ref<yordle::data::meta::VfxSystemDefinitionData>(1171098015u, ptr_Particle->value);
    }

    auto ptr_looping = prop->cast_prop<yordle::data::prop::bool_prop>(1972607277u);
    if(ptr_looping != nullptr) {
        looping = ptr_looping->value;
    }
}
