/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xbf5ac0ff.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xbf5ac0ff::xbf5ac0ff(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Scene = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(543410963u);
    if(ptr_Scene != nullptr) {
        Scene = ptr_Scene->value;
    }

    auto ptr_x538d27eb = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1401759723u);
    if(ptr_x538d27eb != nullptr) {
        x538d27eb = ptr_x538d27eb->value;
    }

    auto ptr_x3ca13504 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1017197828u);
    if(ptr_x3ca13504 != nullptr) {
        x3ca13504 = ptr_x3ca13504->value;
    }

    auto ptr_xa064eee8 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2690969320u);
    if(ptr_xa064eee8 != nullptr) {
        xa064eee8 = ptr_xa064eee8->value;
    }

    auto ptr_Timer = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1550380322u);
    if(ptr_Timer != nullptr) {
        Timer = ptr_Timer->value;
    }

    auto ptr_x22d4499e = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(584337822u);
    if(ptr_x22d4499e != nullptr) {
        x22d4499e = ptr_x22d4499e->value;
    }

    auto ptr_x76b767cf = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1991731151u);
    if(ptr_x76b767cf != nullptr) {
        x76b767cf = ptr_x76b767cf->value;
    }

    auto ptr_x302ccf7d = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(808243069u);
    if(ptr_x302ccf7d != nullptr) {
        x302ccf7d = ptr_x302ccf7d->value;
    }

    auto ptr_xc26ddee = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(203873774u);
    if(ptr_xc26ddee != nullptr) {
        xc26ddee = ptr_xc26ddee->value;
    }
}
