/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xcd809187.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xcd809187::xcd809187(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_Group = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1605967500u);
    if(ptr_Group != nullptr) {
        Group = ptr_Group->value;
    }

    auto ptr_Icon = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3862959600u);
    if(ptr_Icon != nullptr) {
        Icon = ptr_Icon->value;
    }

    auto ptr_x98850381 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2558854017u);
    if(ptr_x98850381 != nullptr) {
        x98850381 = ptr_x98850381->value;
    }

    auto ptr_xabcc11e8 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2882277864u);
    if(ptr_xabcc11e8 != nullptr) {
        xabcc11e8 = ptr_xabcc11e8->value;
    }

    auto ptr_x43b27471 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1135768689u);
    if(ptr_x43b27471 != nullptr) {
        x43b27471 = ptr_x43b27471->value;
    }

    auto ptr_Vfx = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(2318872799u);
    if(ptr_Vfx != nullptr) {
        Vfx = ptr_Vfx->value;
    }
}
