/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xce8769d7.hpp>

#include <yordle/data/meta/bin_defs/xf261b123.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xce8769d7::xce8769d7(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x20890fc4 = prop->cast_prop<yordle::data::prop::map_prop>(545853380u);
    if(ptr_x20890fc4 != nullptr) {
        for(const auto &set_x20890fc4_pair : ptr_x20890fc4->value) {
            auto ptr_x20890fc4_key = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::string_prop>(set_x20890fc4_pair.first);
            auto ptr_x20890fc4_value = yordle::data::prop::empty_prop::cast_prop<yordle::data::prop::reference_prop>(set_x20890fc4_pair.second);
            if(ptr_x20890fc4_key != nullptr && ptr_x20890fc4_value != nullptr) {
                x20890fc4.emplace(ptr_x20890fc4_key->value, yordle::data::meta::bin_ref<yordle::data::meta::xf261b123>(4066488611u, ptr_x20890fc4_value->value));
            }
        }
    }
}
