/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xd60f170b.hpp>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xd60f170b::xd60f170b(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_radius = prop->cast_prop<yordle::data::prop::float32_prop>(230313139u);
    if(ptr_radius != nullptr) {
        radius = ptr_radius->value;
    }

    auto ptr_xba744195 = prop->cast_prop<yordle::data::prop::float32_prop>(3128181141u);
    if(ptr_xba744195 != nullptr) {
        xba744195 = ptr_xba744195->value;
    }

    auto ptr_x47676523 = prop->cast_prop<yordle::data::prop::float32_prop>(1197958435u);
    if(ptr_x47676523 != nullptr) {
        x47676523 = ptr_x47676523->value;
    }

    auto ptr_xe4c18db4 = prop->cast_prop<yordle::data::prop::float32_prop>(3837889972u);
    if(ptr_xe4c18db4 != nullptr) {
        xe4c18db4 = ptr_xe4c18db4->value;
    }

    auto ptr_x141bdb6 = prop->cast_prop<yordle::data::prop::float32_prop>(21085622u);
    if(ptr_x141bdb6 != nullptr) {
        x141bdb6 = ptr_x141bdb6->value;
    }

    auto ptr_x53dd7e1a = prop->cast_prop<yordle::data::prop::string_prop>(1407024666u);
    if(ptr_x53dd7e1a != nullptr) {
        x53dd7e1a = ptr_x53dd7e1a->value;
    }

    auto ptr_xe403ebcc = prop->cast_prop<yordle::data::prop::float32_prop>(3825462220u);
    if(ptr_xe403ebcc != nullptr) {
        xe403ebcc = ptr_xe403ebcc->value;
    }
}
