/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xd63809d8.hpp>

#include <yordle/data/meta/bin_defs/x700d0136.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xd63809d8::xd63809d8(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::x700d0136(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xf0d308f6 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4040362230u);
    if(ptr_xf0d308f6 != nullptr) {
        xf0d308f6 = ptr_xf0d308f6->value;
    }

    auto ptr_xc96b5b85 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3379256197u);
    if(ptr_xc96b5b85 != nullptr) {
        xc96b5b85 = ptr_xc96b5b85->value;
    }
}
