/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xe04f7948.hpp>

#include <yordle/data/meta/bin_defs/x7a851cd8.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xe04f7948::xe04f7948(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::bin_class(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_xc6f291ed = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3337785837u);
    if(ptr_xc6f291ed != nullptr) {
        xc6f291ed = ptr_xc6f291ed->value;
    }

    auto ptr_x91b3ecea = prop->cast_prop<yordle::data::prop::bool_prop>(2444487914u);
    if(ptr_x91b3ecea != nullptr) {
        x91b3ecea = ptr_x91b3ecea->value;
    }

    auto ptr_x94c90e2b = prop->cast_prop<yordle::data::prop::bool_prop>(2496204331u);
    if(ptr_x94c90e2b != nullptr) {
        x94c90e2b = ptr_x94c90e2b->value;
    }

    auto ptr_x74116245 = prop->cast_prop<yordle::data::prop::bool_prop>(1947296325u);
    if(ptr_x74116245 != nullptr) {
        x74116245 = ptr_x74116245->value;
    }

    auto ptr_x92213dee = prop->cast_prop<yordle::data::prop::bool_prop>(2451652078u);
    if(ptr_x92213dee != nullptr) {
        x92213dee = ptr_x92213dee->value;
    }

    auto ptr_x315f2098 = prop->cast_prop<yordle::data::prop::float32_prop>(828317848u);
    if(ptr_x315f2098 != nullptr) {
        x315f2098 = ptr_x315f2098->value;
    }

    auto ptr_Condition = prop->cast_prop<yordle::data::prop::structure_prop>(3524459198u);
    if(ptr_Condition != nullptr) {
        Condition = yordle::data::meta::deserialize<yordle::data::meta::x7a851cd8>(ptr_Condition, 2055544024u);
    }
}
