/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#include <yordle/data/meta/bin_defs/xf1c387c0.hpp>

#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/prop/empty_prop.hpp>
#include <yordle/data/prop/inline_structure_prop.hpp>
#include <yordle/data/prop/map_prop.hpp>
#include <yordle/data/prop/optional_prop.hpp>
#include <yordle/data/prop/primitive_array_prop.hpp>
#include <yordle/data/prop/primitive_prop.hpp>
#include <yordle/data/prop/set_prop.hpp>
#include <yordle/data/prop/string_prop.hpp>
#include <yordle/data/prop/unordered_set_prop.hpp>
#include <yordle/data/prop/structure_prop.hpp>

yordle::data::meta::xf1c387c0::xf1c387c0(const std::shared_ptr<yordle::data::prop::structure_prop> &prop) : yordle::data::meta::ViewController(prop) {
    if(prop == nullptr) {
        return;
    }
    auto ptr_x276cfa24 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(661453348u);
    if(ptr_x276cfa24 != nullptr) {
        x276cfa24 = ptr_x276cfa24->value;
    }

    auto ptr_x7cc89a2 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(130845090u);
    if(ptr_x7cc89a2 != nullptr) {
        x7cc89a2 = ptr_x7cc89a2->value;
    }

    auto ptr_x4d302530 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(1295000880u);
    if(ptr_x4d302530 != nullptr) {
        x4d302530 = ptr_x4d302530->value;
    }

    auto ptr_xbd3bb93 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(198425491u);
    if(ptr_xbd3bb93 != nullptr) {
        xbd3bb93 = ptr_xbd3bb93->value;
    }

    auto ptr_xfb678d00 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(4217867520u);
    if(ptr_xfb678d00 != nullptr) {
        xfb678d00 = ptr_xfb678d00->value;
    }

    auto ptr_xbe72a198 = prop->cast_prop<yordle::data::prop::fnv_hash_prop>(3195183512u);
    if(ptr_xbe72a198 != nullptr) {
        xbe72a198 = ptr_xbe72a198->value;
    }
}
