/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_Breakpoint
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT Breakpoint : public bin_class {
        explicit Breakpoint(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2392053998u;
        }

        uint32_t mLevel = 1u;
        float xd5fd07ed = 0.0f;
        float x57fdc438 = 0.0f;
    };
}
#define YORDLE_META_DEF_Breakpoint
#endif
