/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_ByCharLevelInterpolationCalculationPart
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/IGameCalculationPartByCharLevel.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT ByCharLevelInterpolationCalculationPart : public IGameCalculationPartByCharLevel {
        explicit ByCharLevelInterpolationCalculationPart(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 369020348u || IGameCalculationPartByCharLevel::is_type(type);
        }

        float mStartValue = 0.0;
        float mEndValue = 0.0;
        bool x7fe8e3b3 = false;
        bool xa331f6bf = true;
    };
}
#define YORDLE_META_DEF_ByCharLevelInterpolationCalculationPart
#endif
