/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_CommonUiTunables
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT CommonUiTunables : public bin_class {
        explicit CommonUiTunables(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2733481098u;
        }

        float x472b866d = 1.5;
        uint8_t xb3f4a621 = 8u;
    };
}
#define YORDLE_META_DEF_CommonUiTunables
#endif
