/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_CursorConfig
#pragma once

#include <memory>
#include <array>

#include <yordle/data/meta/bin_defs/CursorData.hpp>
#include <yordle/data/meta/bin_defs/CursorDataTeamContext.hpp>
#include <yordle/data/meta/bin_defs/CursorDataCaptureCooldownContext.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_CursorData
    struct CursorData;
#endif

#ifndef YORDLE_META_DEF_CursorDataTeamContext
    struct CursorDataTeamContext;
#endif

#ifndef YORDLE_META_DEF_CursorDataCaptureCooldownContext
    struct CursorDataCaptureCooldownContext;
#endif
    struct YORDLE_EXPORT CursorConfig : public bin_class {
        explicit CursorConfig(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3994575677u;
        }

        std::array<std::shared_ptr<yordle::data::meta::CursorData>, 10> mSingleContextCursors { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
        std::array<std::shared_ptr<yordle::data::meta::CursorDataTeamContext>, 3> mTeamContextCursors { nullptr, nullptr, nullptr };
        std::shared_ptr<yordle::data::meta::CursorDataCaptureCooldownContext> mHoverNotUseableCursor {};
    };
}
#define YORDLE_META_DEF_CursorConfig
#endif
