/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_EffectDesaturateElementData
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/AtlasData.hpp>
#include <yordle/data/meta/bin_defs/EffectElementData.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_AtlasData
    struct AtlasData;
#endif
    struct YORDLE_EXPORT EffectDesaturateElementData : public EffectElementData {
        explicit EffectDesaturateElementData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1335813830u || EffectElementData::is_type(type);
        }

        float MinimumSaturation = 0.0f;
        float MaximumSaturation = 1.0f;
        bool mFlipX = false;
        bool mFlipY = false;
        bool mPerPixelUvsX = false;
        std::shared_ptr<yordle::data::meta::AtlasData> mAtlas {};
    };
}
#define YORDLE_META_DEF_EffectDesaturateElementData
#endif
