/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_EsportsBannerOptions
#pragma once

#include <memory>
#include <string>
#include <cstdint>

#include <yordle/data/meta/bin_defs/IMaterialDef.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_IMaterialDef
    struct IMaterialDef;
#endif
    struct YORDLE_EXPORT EsportsBannerOptions : public bin_class {
        explicit EsportsBannerOptions(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 224714173u;
        }

        std::string subMeshName {};
        yordle::data::meta::bin_xx_hash defaultTexturePath = 0u;
        bool IsSpectatorOnly = true;
        uint32_t x754cdce2 = 2u;
        yordle::data::meta::bin_ref<yordle::data::meta::IMaterialDef> DefaultBlankMaterial { 3975636772 };
    };
}
#define YORDLE_META_DEF_EsportsBannerOptions
#endif
