/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_FixedSpeedMovement
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/MissileMovementSpec.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT FixedSpeedMovement : public MissileMovementSpec {
        explicit FixedSpeedMovement(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 103819417u || MissileMovementSpec::is_type(type);
        }

        bool mInferDirectionFromFacingIfNeeded = true;
        bool mProjectTargetToCastRange = false;
        bool x99aa2d1f = false;
        bool mUseGroundHeightAtTarget = true;
        float mSpeed = 0.0;
    };
}
#define YORDLE_META_DEF_FixedSpeedMovement
#endif
