/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_FloatLiteralMaterialDriver
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/IDynamicMaterialFloatDriver.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT FloatLiteralMaterialDriver : public IDynamicMaterialFloatDriver {
        explicit FloatLiteralMaterialDriver(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1895822007u || IDynamicMaterialFloatDriver::is_type(type);
        }

        float mValue = 0.0;
    };
}
#define YORDLE_META_DEF_FloatLiteralMaterialDriver
#endif
