/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_FloatingTextTunables
#pragma once

#include <memory>
#include <cstdint>
#include <vector>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT FloatingTextTunables : public bin_class {
        explicit FloatingTextTunables(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 395898060u;
        }

        float mAnimatedTextQueueDelay = 0.10000000149011612f;
        float mIntervalInPix = -1.0f;
        float mScrollSpeed = 45.0f;
        uint32_t mMaxFloatingTextItems = 25u;
        float mMinimumDynamicScale = 1.0f;
        float mMaximumDynamicScale = 1.75f;
        float mYResolutionBaseline = 1200.0f;
        float xccf713a7 = 1000000.0f;
        float xf56f095c = -1.0f;
        float mMinionComparisonMultiplier = 1.25f;
        float mLocalPlayerHealthComparison = 12.5f;
        std::vector<float> mComparisonByLevel {};
    };
}
#define YORDLE_META_DEF_FloatingTextTunables
#endif
