/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_FontType
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/FontLocaleType.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_FontLocaleType
    struct FontLocaleType;
#endif
    struct YORDLE_EXPORT FontType : public bin_class {
        explicit FontType(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 766729624u;
        }

        std::vector<std::shared_ptr<yordle::data::meta::FontLocaleType>> localeTypes {};
    };
}
#define YORDLE_META_DEF_FontType
#endif
