/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_FunctionDefinition
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/ScriptSequence.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ScriptSequence
    struct ScriptSequence;
#endif
    struct YORDLE_EXPORT FunctionDefinition : public bin_class {
        explicit FunctionDefinition(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3984358668u;
        }

        std::vector<yordle::data::meta::bin_fnv_hash> InputParameters {};
        std::vector<yordle::data::meta::bin_fnv_hash> OutputParameters {};
        std::shared_ptr<yordle::data::meta::ScriptSequence> Sequence {};
    };
}
#define YORDLE_META_DEF_FunctionDefinition
#endif
