/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_healthBarData
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xd0217984.hpp>
#include <yordle/data/meta/bin_defs/xbcdc9113.hpp>
#include <yordle/data/meta/bin_defs/xb075814f.hpp>
#include <yordle/data/meta/bin_defs/xad58e686.hpp>
#include <yordle/data/meta/bin_defs/x6172a47c.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_xd0217984
    struct xd0217984;
#endif

#ifndef YORDLE_META_DEF_xbcdc9113
    struct xbcdc9113;
#endif

#ifndef YORDLE_META_DEF_xb075814f
    struct xb075814f;
#endif

#ifndef YORDLE_META_DEF_xad58e686
    struct xad58e686;
#endif

#ifndef YORDLE_META_DEF_x6172a47c
    struct x6172a47c;
#endif
    struct YORDLE_EXPORT healthBarData : public bin_class {
        explicit healthBarData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1372076792u;
        }

        std::shared_ptr<yordle::data::meta::xd0217984> HealthBar {};
        yordle::data::meta::bin_fnv_hash xd20a71a6 = 0u;
        yordle::data::meta::bin_fnv_hash Backdrop = 0u;
        std::shared_ptr<yordle::data::meta::xbcdc9113> xc1615329 {};
        yordle::data::meta::bin_fnv_hash x472fe83 = 0u;
        std::shared_ptr<yordle::data::meta::xb075814f> xa3482ede {};
        std::shared_ptr<yordle::data::meta::xad58e686> fadeData {};
        std::shared_ptr<yordle::data::meta::x6172a47c> x2cc9296f {};
    };
}
#define YORDLE_META_DEF_healthBarData
#endif
