/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_HudHealthBarBurstData
#pragma once

#include <memory>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT HudHealthBarBurstData : public bin_class {
        explicit HudHealthBarBurstData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 234651109u;
        }

        float burstTimeWindow = 0.20000000298023224;
        float burstTriggerPercent = 0.3499999940395355;
        float flashTriggerPercent = 0.3499999940395355;
        float flashDuration = 0.20000000298023224;
        float shakeDuration = 0.10000000149011612;
        std::array<float, 2> shakeBox { 6, 3 };
        std::array<float, 2> shakeReferenceResolution { 1024, 768 };
        float shakeTriggerPercent = 0.30000001192092896;
        float shakeFrequency = 10.0;
        float fadeSpeed = 0.5;
        float fadeAcceleration = 0.0;
        float fadeHoldTime = 0.0;
    };
}
#define YORDLE_META_DEF_HudHealthBarBurstData
#endif
