/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_HudHealthBarFadeData
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT HudHealthBarFadeData : public bin_class {
        explicit HudHealthBarFadeData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1035555423u;
        }

        float fadeSpeed = 0.5;
        float fadeAcceleration = 0.0;
        float fadeHoldTime = 0.0;
    };
}
#define YORDLE_META_DEF_HudHealthBarFadeData
#endif
