/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_HudHealthBarProgressiveTickData
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/MicroTicksPerTickData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_MicroTicksPerTickData
    struct MicroTicksPerTickData;
#endif
    struct YORDLE_EXPORT HudHealthBarProgressiveTickData : public bin_class {
        explicit HudHealthBarProgressiveTickData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 503820853u;
        }

        std::vector<std::shared_ptr<yordle::data::meta::MicroTicksPerTickData>> microTickPerTickData {};
        float healthPerTick = 1000.0;
    };
}
#define YORDLE_META_DEF_HudHealthBarProgressiveTickData
#endif
