/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_HudTeamScoreMeterProperties
#pragma once

#include <memory>
#include <cstdint>
#include <string>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT HudTeamScoreMeterProperties : public bin_class {
        explicit HudTeamScoreMeterProperties(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3303051661u;
        }

        uint8_t mTeamScoreMeterType = 0u;
        bool mShowScoreText = false;
        std::string x86864fbc {};
        std::string x6044a790 {};
    };
}
#define YORDLE_META_DEF_HudTeamScoreMeterProperties
#endif
