/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_HybridMaterialDefPreset
#pragma once

#include <memory>
#include <map>
#include <string>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT HybridMaterialDefPreset : public bin_class {
        explicit HybridMaterialDefPreset(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1659255250u;
        }

        std::map<std::string, std::string> shaderMacros {};
        bool depthEnable = true;
        bool stencilEnable = false;
        bool blendEnable = false;
        bool cullEnable = true;
        bool xaab4104c = false;
        uint8_t depthCompareFunc = 3u;
        uint8_t stencilCompareFunc = 1u;
        uint32_t stencilReferenceVal = 0u;
        uint32_t stencilMask = 0u;
        uint8_t stencilFailOp = 0u;
        uint8_t stencilPassDepthFailOp = 0u;
        uint8_t stencilPassDepthPassOp = 0u;
        uint8_t srcColorBlendFactor = 1u;
        uint8_t srcAlphaBlendFactor = 1u;
        uint8_t dstColorBlendFactor = 0u;
        uint8_t dstAlphaBlendFactor = 0u;
        uint8_t blendEquation = 0u;
        uint8_t windingToCull = 1u;
        uint8_t writeMask = 31u;
        float depthOffsetSlope = 0.0;
        float depthOffsetBias = 0.0;
    };
}
#define YORDLE_META_DEF_HybridMaterialDefPreset
#endif
