/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_ItemRecommendationContext
#pragma once

#include <memory>
#include <cstdint>
#include <vector>

#include <yordle/data/meta/bin_defs/ItemRecommendationMatrix.hpp>
#include <yordle/data/meta/bin_defs/ItemRecommendationItemList.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ItemRecommendationMatrix
    struct ItemRecommendationMatrix;
#endif

#ifndef YORDLE_META_DEF_ItemRecommendationItemList
    struct ItemRecommendationItemList;
#endif
    struct YORDLE_EXPORT ItemRecommendationContext : public bin_class {
        explicit ItemRecommendationContext(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 4266457040u;
        }

        uint32_t mChampionId = 0u;
        uint32_t mMapID = 0u;
        yordle::data::meta::bin_fnv_hash x37b75f5c = 0u;
        yordle::data::meta::bin_fnv_hash mPosition = 0u;
        bool mIsDefaultPosition = false;
        std::vector<yordle::data::meta::bin_fnv_hash> mPopularItems {};
        std::shared_ptr<yordle::data::meta::ItemRecommendationMatrix> mStartingItemMatrix {};
        std::vector<std::shared_ptr<yordle::data::meta::ItemRecommendationItemList>> mStartingItemBundles {};
        std::shared_ptr<yordle::data::meta::ItemRecommendationMatrix> mCompletedItemMatrix {};
    };
}
#define YORDLE_META_DEF_ItemRecommendationContext
#endif
