/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_LerpMaterialDriver
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/IDynamicMaterialBoolDriver.hpp>
#include <yordle/data/meta/bin_defs/IDynamicMaterialFloatDriver.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_IDynamicMaterialBoolDriver
    struct IDynamicMaterialBoolDriver;
#endif
    struct YORDLE_EXPORT LerpMaterialDriver : public IDynamicMaterialFloatDriver {
        explicit LerpMaterialDriver(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3032802403u || IDynamicMaterialFloatDriver::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::IDynamicMaterialBoolDriver> mBoolDriver {};
        float mOnValue = 1.0f;
        float mOffValue = 0.0f;
        float mTurnOnTimeSec = 1.0f;
        float mTurnOffTimeSec = 1.0f;
        bool xa452be9f = false;
    };
}
#define YORDLE_META_DEF_LerpMaterialDriver
#endif
