/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MapGraphicsFeature
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/MapComponent.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT MapGraphicsFeature : public MapComponent {
        explicit MapGraphicsFeature(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 66354938u || MapComponent::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_MapGraphicsFeature
#endif
