/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MapLightingV2
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/MapGraphicsFeature.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT MapLightingV2 : public MapGraphicsFeature {
        explicit MapLightingV2(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3701691417u || MapGraphicsFeature::is_type(type);
        }

        float xee91017d = 0.0;
        float xc916a9fc = 3000.0;
    };
}
#define YORDLE_META_DEF_MapLightingV2
#endif
