/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MasteryBadgeData
#pragma once

#include <memory>
#include <string>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT MasteryBadgeData : public bin_class {
        explicit MasteryBadgeData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1337363141u;
        }

        yordle::data::meta::bin_fnv_hash mName = 0u;
        std::string mParticleName {};
        float mRenderScale = 1.0;
        float mVerticalOffset = 0.0;
        int32_t mSummonerIconId = -1;
        uint32_t mMasteryLevel = 0u;
    };
}
#define YORDLE_META_DEF_MasteryBadgeData
#endif
