/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MaterialParameterDataCollection
#pragma once

#include <memory>
#include <cstdint>
#include <map>
#include <string>

#include <yordle/data/meta/bin_defs/IdMappingEntry.hpp>
#include <yordle/data/meta/bin_defs/MaterialParameterData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_IdMappingEntry
    struct IdMappingEntry;
#endif

#ifndef YORDLE_META_DEF_MaterialParameterData
    struct MaterialParameterData;
#endif
    struct YORDLE_EXPORT MaterialParameterDataCollection : public bin_class {
        explicit MaterialParameterDataCollection(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3921803671u;
        }

        int16_t nextID = 1u;
        std::map<std::string, std::shared_ptr<yordle::data::meta::IdMappingEntry>> Entries {};
        std::string xea57bf12 {};
        std::map<uint16_t, std::shared_ptr<yordle::data::meta::MaterialParameterData>> data {};
    };
}
#define YORDLE_META_DEF_MaterialParameterDataCollection
#endif
