/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MaterialDataCollections
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/MaterialParameterDataCollection.hpp>
#include <yordle/data/meta/bin_defs/MaterialTextureDataCollection.hpp>
#include <yordle/data/meta/bin_defs/MaterialSwitchDataCollection.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_MaterialParameterDataCollection
    struct MaterialParameterDataCollection;
#endif

#ifndef YORDLE_META_DEF_MaterialTextureDataCollection
    struct MaterialTextureDataCollection;
#endif

#ifndef YORDLE_META_DEF_MaterialSwitchDataCollection
    struct MaterialSwitchDataCollection;
#endif
    struct YORDLE_EXPORT MaterialDataCollections : public bin_class {
        explicit MaterialDataCollections(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1874373301u;
        }

        std::shared_ptr<yordle::data::meta::MaterialParameterDataCollection> ParameterData {};
        std::shared_ptr<yordle::data::meta::MaterialTextureDataCollection> TextureData {};
        std::shared_ptr<yordle::data::meta::MaterialSwitchDataCollection> switchData {};
    };
}
#define YORDLE_META_DEF_MaterialDataCollections
#endif
