/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MaterialParameterData
#pragma once

#include <memory>
#include <cstdint>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT MaterialParameterData : public bin_class {
        explicit MaterialParameterData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1407148951u;
        }

        uint8_t type = 4u;
        std::array<float, 4> DefaultValue { 0.0f, 0.0f, 0.0f, 1.0f };
    };
}
#define YORDLE_META_DEF_MaterialParameterData
#endif
