/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_MessageBoxDialog
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/HudMenuTransitionData.hpp>
#include <yordle/data/meta/bin_defs/x63394a54.hpp>
#include <yordle/data/meta/bin_defs/x75259ad3.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_HudMenuTransitionData
    struct HudMenuTransitionData;
#endif

#ifndef YORDLE_META_DEF_x63394a54
    struct x63394a54;
#endif
    struct YORDLE_EXPORT MessageBoxDialog : public x75259ad3 {
        explicit MessageBoxDialog(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3766132529u || x75259ad3::is_type(type);
        }

        yordle::data::meta::bin_fnv_hash x131c35c5 = 0u;
        yordle::data::meta::bin_fnv_hash x70020ab = 0u;
        yordle::data::meta::bin_fnv_hash x31dff863 = 0u;
        yordle::data::meta::bin_fnv_hash x6fd80c = 0u;
        yordle::data::meta::bin_fnv_hash xab91ba1f = 0u;
        yordle::data::meta::bin_fnv_hash x315b9a19 = 0u;
        std::shared_ptr<yordle::data::meta::HudMenuTransitionData> x2992fe27 {};
        std::shared_ptr<yordle::data::meta::x63394a54> x985233b8 {};
        std::shared_ptr<yordle::data::meta::x63394a54> x1347d194 {};
    };
}
#define YORDLE_META_DEF_MessageBoxDialog
#endif
