/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_NeutralTimerSourceIconData
#pragma once

#include <memory>
#include <string>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT NeutralTimerSourceIconData : public bin_class {
        explicit NeutralTimerSourceIconData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 230608261u;
        }

        yordle::data::meta::bin_fnv_hash xf135454f = 0u;
        std::string xfed22233 {};
        yordle::data::meta::bin_fnv_hash Icon = 0u;
    };
}
#define YORDLE_META_DEF_NeutralTimerSourceIconData
#endif
