/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_OptionTemplateSecondaryHotkeys1Column
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xceb70e5a.hpp>
#include <yordle/data/meta/bin_defs/x354988a8.hpp>
#include <yordle/data/meta/bin_defs/IOptionTemplate.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_xceb70e5a
    struct xceb70e5a;
#endif

#ifndef YORDLE_META_DEF_x354988a8
    struct x354988a8;
#endif
    struct YORDLE_EXPORT OptionTemplateSecondaryHotkeys1Column : public IOptionTemplate {
        explicit OptionTemplateSecondaryHotkeys1Column(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3369934580u || IOptionTemplate::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::xceb70e5a> x5b59b589 {};
        std::shared_ptr<yordle::data::meta::xceb70e5a> x5a59b3f6 {};
        std::shared_ptr<yordle::data::meta::xceb70e5a> xfd31cbcb {};
        std::shared_ptr<yordle::data::meta::x354988a8> x545758a8 {};
    };
}
#define YORDLE_META_DEF_OptionTemplateSecondaryHotkeys1Column
#endif
