/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_ScriptDataObjectList
#pragma once

#include <memory>
#include <string>
#include <vector>

#include <yordle/data/meta/bin_defs/ScriptDataObject.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ScriptDataObject
    struct ScriptDataObject;
#endif
    struct YORDLE_EXPORT ScriptDataObjectList : public bin_class {
        explicit ScriptDataObjectList(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3171701405u;
        }

        std::string mName {};
        std::vector<yordle::data::meta::bin_ref<yordle::data::meta::ScriptDataObject>> mScriptDataObjects {};
    };
}
#define YORDLE_META_DEF_ScriptDataObjectList
#endif
