/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_SummonerIconData
#pragma once

#include <memory>
#include <cstdint>
#include <string>

#include <yordle/data/meta/bin_defs/CollectiblesEsportsTeamData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_CollectiblesEsportsTeamData
    struct CollectiblesEsportsTeamData;
#endif
    struct YORDLE_EXPORT SummonerIconData : public bin_class {
        explicit SummonerIconData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2783969040u;
        }

        uint32_t iconId = 0u;
        yordle::data::meta::bin_ref<yordle::data::meta::CollectiblesEsportsTeamData> esportsTeam { 3808259511 };
        std::string gameTexture {};
        bool x50e5b6e1 = false;
        std::string eSportsEventMutator {};
    };
}
#define YORDLE_META_DEF_SummonerIconData
#endif
