/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_SummonerNameCreateViewController
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/HudMenuTransitionData.hpp>
#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_HudMenuTransitionData
    struct HudMenuTransitionData;
#endif
    struct YORDLE_EXPORT SummonerNameCreateViewController : public ViewController {
        explicit SummonerNameCreateViewController(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3950575855u || ViewController::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::HudMenuTransitionData> x2992fe27 {};
        yordle::data::meta::bin_fnv_hash x4d302530 = 0u;
        yordle::data::meta::bin_fnv_hash x27215cd1 = 0u;
        yordle::data::meta::bin_fnv_hash x315b9a19 = 0u;
    };
}
#define YORDLE_META_DEF_SummonerNameCreateViewController
#endif
