/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_SurrenderTypeData
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT SurrenderTypeData : public bin_class {
        explicit SurrenderTypeData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 740737797u;
        }

        float VoteTimeout = 60.0;
        float windowLength = 60.0;
        float startTime = 1200.0;
        float percentageRequired = 0.699999988079071;
        float x3f72f07a = 1200.0;
    };
}
#define YORDLE_META_DEF_SurrenderTypeData
#endif
