/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TargetTypeFilter
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/IStatStoneLogicDriver.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT TargetTypeFilter : public IStatStoneLogicDriver {
        explicit TargetTypeFilter(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3994264754u || IStatStoneLogicDriver::is_type(type);
        }

        bool x47bac313 = true;
        bool x1e3fcd64 = true;
        bool xd5e57340 = false;
    };
}
#define YORDLE_META_DEF_TargetTypeFilter
#endif
