/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TargeterDefinitionWall
#pragma once

#include <memory>
#include <cstdint>
#include <string>

#include <yordle/data/meta/bin_defs/DrawablePositionLocator.hpp>
#include <yordle/data/meta/bin_defs/FloatPerSpellLevel.hpp>
#include <yordle/data/meta/bin_defs/TargeterDefinition.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_DrawablePositionLocator
    struct DrawablePositionLocator;
#endif

#ifndef YORDLE_META_DEF_FloatPerSpellLevel
    struct FloatPerSpellLevel;
#endif
    struct YORDLE_EXPORT TargeterDefinitionWall : public TargeterDefinition {
        explicit TargeterDefinitionWall(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1653312970u || TargeterDefinition::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::DrawablePositionLocator> centerLocator {};
        uint32_t wallOrientation = 3u;
        float wallRotation = 0.0f;
        std::shared_ptr<yordle::data::meta::FloatPerSpellLevel> thickness {};
        std::shared_ptr<yordle::data::meta::FloatPerSpellLevel> length {};
        std::string textureWallOverrideName {};
    };
}
#define YORDLE_META_DEF_TargeterDefinitionWall
#endif
