/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TftItemComposition
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/TftItemData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_TftItemData
    struct TftItemData;
#endif
    struct YORDLE_EXPORT TftItemComposition : public bin_class {
        explicit TftItemComposition(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1707263328u;
        }

        std::vector<yordle::data::meta::bin_ref<yordle::data::meta::TftItemData>> mComponents {};
    };
}
#define YORDLE_META_DEF_TftItemComposition
#endif
