/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TFTNotificationData
#pragma once

#include <memory>
#include <string>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT TFTNotificationData : public bin_class {
        explicit TFTNotificationData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2099815050u;
        }

        std::string mName {};
        float mDurationSeconds = 3.0f;
        std::string mToplineTra {};
        std::string mBottomlineTra {};
        std::string mIconPath {};
        std::string x1e7fffb0 {};
        std::string xde5be189 {};
        std::string xa6874a6e {};
    };
}
#define YORDLE_META_DEF_TFTNotificationData
#endif
