/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TooltipInstance
#pragma once

#include <memory>
#include <string>
#include <map>

#include <yordle/data/meta/bin_defs/TooltipFormat.hpp>
#include <yordle/data/meta/bin_defs/TooltipInstanceList.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_TooltipFormat
    struct TooltipFormat;
#endif

#ifndef YORDLE_META_DEF_TooltipInstanceList
    struct TooltipInstanceList;
#endif
    struct YORDLE_EXPORT TooltipInstance : public bin_class {
        explicit TooltipInstance(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2250161003u;
        }

        std::string mObjectName {};
        yordle::data::meta::bin_ref<yordle::data::meta::TooltipFormat> mFormat { 2994559891 };
        std::map<std::string, std::string> mLocKeys {};
        std::map<std::string, std::shared_ptr<yordle::data::meta::TooltipInstanceList>> mLists {};
    };
}
#define YORDLE_META_DEF_TooltipInstance
#endif
