/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TooltipInstanceBuff
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/TooltipInstance.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT TooltipInstanceBuff : public TooltipInstance {
        explicit TooltipInstanceBuff(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1588263926u || TooltipInstance::is_type(type);
        }

        bool mEnableExtendedTooltip = false;
    };
}
#define YORDLE_META_DEF_TooltipInstanceBuff
#endif
