/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_TrophyData
#pragma once

#include <memory>
#include <string>

#include <yordle/data/meta/bin_defs/SkinMeshDataProperties.hpp>
#include <yordle/data/meta/bin_defs/AnimationGraphData.hpp>
#include <yordle/data/meta/bin_defs/ResourceResolver.hpp>
#include <yordle/data/meta/bin_defs/BaseLoadoutData.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_SkinMeshDataProperties
    struct SkinMeshDataProperties;
#endif

#ifndef YORDLE_META_DEF_AnimationGraphData
    struct AnimationGraphData;
#endif

#ifndef YORDLE_META_DEF_ResourceResolver
    struct ResourceResolver;
#endif
    struct YORDLE_EXPORT TrophyData : public BaseLoadoutData {
        explicit TrophyData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1176619879u || BaseLoadoutData::is_type(type);
        }

        float mPerceptionBubbleRadius = 250.0;
        std::shared_ptr<yordle::data::meta::SkinMeshDataProperties> skinMeshProperties {};
        yordle::data::meta::bin_ref<yordle::data::meta::AnimationGraphData> AnimationGraphData { 4126869447 };
        std::shared_ptr<yordle::data::meta::ResourceResolver> mVFXResourceResolver {};
        std::string mBracketTRAKey {};
    };
}
#define YORDLE_META_DEF_TrophyData
#endif
