/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_VfxAnimatedColorVariableData
#pragma once

#include <memory>
#include <array>
#include <vector>

#include <yordle/data/meta/bin_defs/VfxProbabilityTableData.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_VfxProbabilityTableData
    struct VfxProbabilityTableData;
#endif
    struct YORDLE_EXPORT VfxAnimatedColorVariableData : public bin_class {
        explicit VfxAnimatedColorVariableData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1128908277u;
        }

        std::array<std::shared_ptr<yordle::data::meta::VfxProbabilityTableData>, 4> probabilityTables { nullptr, nullptr, nullptr, nullptr };
        std::vector<float> times {};
        std::vector<std::array<float, 4>> values {};
    };
}
#define YORDLE_META_DEF_VfxAnimatedColorVariableData
#endif
