/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_VfxEmissionSurfaceData
#pragma once

#include <memory>
#include <string>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT VfxEmissionSurfaceData : public bin_class {
        explicit VfxEmissionSurfaceData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3217219891u;
        }

        std::string meshName {};
        std::string skeletonName {};
        std::string animationName {};
        float meshScale = 1.0;
        int16_t maxJointWeights = 4u;
        bool useAvatarPose = false;
        bool useSurfaceNormalForBirthPhysics = true;
    };
}
#define YORDLE_META_DEF_VfxEmissionSurfaceData
#endif
