/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_VfxFieldNoiseDefinitionData
#pragma once

#include <memory>
#include <array>

#include <yordle/data/meta/bin_defs/ValueVector3.hpp>
#include <yordle/data/meta/bin_defs/ValueFloat.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ValueVector3
    struct ValueVector3;
#endif

#ifndef YORDLE_META_DEF_ValueFloat
    struct ValueFloat;
#endif
    struct YORDLE_EXPORT VfxFieldNoiseDefinitionData : public bin_class {
        explicit VfxFieldNoiseDefinitionData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1666037840u;
        }

        std::shared_ptr<yordle::data::meta::ValueVector3> position {};
        std::shared_ptr<yordle::data::meta::ValueFloat> radius {};
        std::shared_ptr<yordle::data::meta::ValueFloat> frequency {};
        std::shared_ptr<yordle::data::meta::ValueFloat> velocityDelta {};
        std::array<float, 3> axisFraction { 0.0f, 0.0f, 0.0f };
    };
}
#define YORDLE_META_DEF_VfxFieldNoiseDefinitionData
#endif
