/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_VfxSineMaterialDriver
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/IVfxMaterialDriver.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT VfxSineMaterialDriver : public IVfxMaterialDriver {
        explicit VfxSineMaterialDriver(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 719276917u || IVfxMaterialDriver::is_type(type);
        }

        float mFrequency = 1.0;
        float mScale = 1.0;
        float mBias = 0.0;
    };
}
#define YORDLE_META_DEF_VfxSineMaterialDriver
#endif
