/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_VfxTrailDefinitionData
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_defs/ValueVector3.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ValueVector3
    struct ValueVector3;
#endif
    struct YORDLE_EXPORT VfxTrailDefinitionData : public bin_class {
        explicit VfxTrailDefinitionData(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 12755856u;
        }

        std::shared_ptr<yordle::data::meta::ValueVector3> mBirthTilingSize {};
        float mCutoff = 0.0f;
        int32_t mMaxAddedPerFrame = 0;
        uint8_t mSmoothingMode = 0u;
        uint8_t mMode = 0u;
    };
}
#define YORDLE_META_DEF_VfxTrailDefinitionData
#endif
