/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x10f4d0bf
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/ICastRequirement.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x10f4d0bf : public ICastRequirement {
        explicit x10f4d0bf(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 284479679u || ICastRequirement::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_x10f4d0bf
#endif
