/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x1122b16e
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xdd53d1ce.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x1122b16e : public xdd53d1ce {
        explicit x1122b16e(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 287486318u || xdd53d1ce::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_x1122b16e
#endif
