/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x1466479b
#pragma once

#include <memory>
#include <string>
#include <cstdint>

#include <yordle/data/meta/bin_defs/x5c086dbd.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_x5c086dbd
    struct x5c086dbd;
#endif
    struct YORDLE_EXPORT x1466479b : public IFxAction {
        explicit x1466479b(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 342247323u || IFxAction::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::x5c086dbd> Target {};
        std::string x42042493 {};
        float x4e748b9a = 0.0f;
        float x820a08fd = 1.0f;
        uint8_t EasingType = 0u;
    };
}
#define YORDLE_META_DEF_x1466479b
#endif
