/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x16eb9b94
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/x19780ce6.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_x19780ce6
    struct x19780ce6;
#endif
    struct YORDLE_EXPORT x16eb9b94 : public bin_class {
        explicit x16eb9b94(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 384539540u;
        }

        yordle::data::meta::bin_fnv_hash Group = 0u;
        yordle::data::meta::bin_fnv_hash x6723e4bf = 0u;
        yordle::data::meta::bin_fnv_hash x368afe7b = 0u;
        yordle::data::meta::bin_fnv_hash xc04a6f62 = 0u;
        yordle::data::meta::bin_fnv_hash x1dfa58a3 = 0u;
        yordle::data::meta::bin_fnv_hash x2e9429e7 = 0u;
        yordle::data::meta::bin_fnv_hash x76daf025 = 0u;
        yordle::data::meta::bin_fnv_hash x9d51f9c1 = 0u;
        yordle::data::meta::bin_fnv_hash xe443d8d6 = 0u;
        yordle::data::meta::bin_fnv_hash xb5616e48 = 0u;
        yordle::data::meta::bin_fnv_hash x2aa5cb5e = 0u;
        yordle::data::meta::bin_fnv_hash x1c330f2a = 0u;
        yordle::data::meta::bin_fnv_hash x1180f709 = 0u;
        yordle::data::meta::bin_fnv_hash xff626dee = 0u;
        yordle::data::meta::bin_fnv_hash x47b3e0c4 = 0u;
        yordle::data::meta::bin_fnv_hash x6f18be08 = 0u;
        yordle::data::meta::bin_fnv_hash xa4a823f4 = 0u;
        yordle::data::meta::bin_fnv_hash x42be75b5 = 0u;
        yordle::data::meta::bin_fnv_hash x4a5b3cd3 = 0u;
        yordle::data::meta::bin_fnv_hash xae75d5ef = 0u;
        yordle::data::meta::bin_fnv_hash x8a64df98 = 0u;
        yordle::data::meta::bin_fnv_hash xc9abc1cd = 0u;
        std::shared_ptr<yordle::data::meta::x19780ce6> xe65501bc {};
        std::shared_ptr<yordle::data::meta::x19780ce6> x35919151 {};
        std::shared_ptr<yordle::data::meta::x19780ce6> x34918fbe {};
    };
}
#define YORDLE_META_DEF_x16eb9b94
#endif
