/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x1e8d9860
#pragma once

#include <memory>
#include <cstdint>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x1e8d9860 : public bin_class {
        explicit x1e8d9860(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 512596064u;
        }

        std::array<uint8_t, 4> PulseStartColor { 193, 251, 255, 255 };
        std::array<uint8_t, 4> PulseEndColor { 219, 252, 255, 255 };
        std::array<float, 2> x59eebc86 { 0.0f, 0.009999999776482582f };
        float pulseTime = 0.4000000059604645f;
        float pulseInterval = 0.20000000298023224f;
    };
}
#define YORDLE_META_DEF_x1e8d9860
#endif
