/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x5ee7c71f
#pragma once

#include <memory>
#include <cstdint>
#include <vector>

#include <yordle/data/meta/bin_defs/xe76e6115.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x5ee7c71f : public xe76e6115 {
        explicit x5ee7c71f(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1592248095u || xe76e6115::is_type(type);
        }

        bool xd95f7caa = false;
        bool x68aa7f75 = true;
        std::vector<uint8_t> x47c120b7 {};
    };
}
#define YORDLE_META_DEF_x5ee7c71f
#endif
