/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x651375aa
#pragma once

#include <memory>
#include <map>
#include <string>

#include <yordle/data/meta/bin_defs/VfxSystemDefinitionData.hpp>
#include <yordle/data/meta/bin_defs/MapComponent.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_VfxSystemDefinitionData
    struct VfxSystemDefinitionData;
#endif
    struct YORDLE_EXPORT x651375aa : public MapComponent {
        explicit x651375aa(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1695774122u || MapComponent::is_type(type);
        }

        std::map<std::string, yordle::data::meta::bin_ref<yordle::data::meta::VfxSystemDefinitionData>> x71755aa6 {};
    };
}
#define YORDLE_META_DEF_x651375aa
#endif
