/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x6e817df8
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xf1c387c0.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x6e817df8 : public xf1c387c0 {
        explicit x6e817df8(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1853980152u || xf1c387c0::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_x6e817df8
#endif
