/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x75259ad3
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/ViewPaneDefinition.hpp>
#include <yordle/data/meta/bin_defs/ViewController.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_ViewPaneDefinition
    struct ViewPaneDefinition;
#endif
    struct YORDLE_EXPORT x75259ad3 : public ViewController {
        explicit x75259ad3(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1965398739u || ViewController::is_type(type);
        }

        yordle::data::meta::bin_fnv_hash CloseButtonDefinition = 0u;
        yordle::data::meta::bin_fnv_hash ConfirmButtonDefinition = 0u;
        yordle::data::meta::bin_fnv_hash CancelButtonDefinition = 0u;
        yordle::data::meta::bin_fnv_hash ContentScene = 0u;
        std::shared_ptr<yordle::data::meta::ViewPaneDefinition> ViewPaneDefinition {};
    };
}
#define YORDLE_META_DEF_x75259ad3
#endif
