/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x769171e6
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/x1c494c09.hpp>
#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_x1c494c09
    struct x1c494c09;
#endif
    struct YORDLE_EXPORT x769171e6 : public IFxAction {
        explicit x769171e6(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 1989243366u || IFxAction::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::x1c494c09> Location {};
    };
}
#define YORDLE_META_DEF_x769171e6
#endif
