/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x7aaf9246
#pragma once

#include <memory>
#include <string>
#include <vector>

#include <yordle/data/meta/bin_defs/x9a2769a4.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x7aaf9246 : public x9a2769a4 {
        explicit x7aaf9246(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2058326598u || x9a2769a4::is_type(type);
        }

        std::vector<std::string> values {};
    };
}
#define YORDLE_META_DEF_x7aaf9246
#endif
