/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x81862b0f
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x81862b0f : public bin_class {
        explicit x81862b0f(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2173053711u;
        }

        uint8_t minAlpha = 0u;
        uint8_t maxAlpha = 255u;
        float maxOffset = 0.05000000074505806;
        float x1568581f = 0.27000001072883606;
        float x1cb012da = 0.10000000149011612;
        float overshoot = 1.0;
        float inertia = 0.5;
        float xe5bc4657 = 5.0;
    };
}
#define YORDLE_META_DEF_x81862b0f
#endif
