/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x84c11b53
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/x1a96332d.hpp>
#include <yordle/data/meta/bin_defs/x6d8274d.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_x1a96332d
    struct x1a96332d;
#endif
    struct YORDLE_EXPORT x84c11b53 : public x6d8274d {
        explicit x84c11b53(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2227247955u || x6d8274d::is_type(type);
        }

        std::vector<std::shared_ptr<yordle::data::meta::x1a96332d>> xfa660ed6 {};
    };
}
#define YORDLE_META_DEF_x84c11b53
#endif
