/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x868f2575
#pragma once

#include <memory>
#include <map>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x868f2575 : public bin_class {
        explicit x868f2575(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2257528181u;
        }

        std::map<uint32_t, yordle::data::meta::bin_fnv_hash> xa46a43a {};
    };
}
#define YORDLE_META_DEF_x868f2575
#endif
