/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x889fe194
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x889fe194 : public bin_class {
        explicit x889fe194(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2292179348u;
        }

        yordle::data::meta::bin_fnv_hash name = 0u;
        bool xd921c2c0 = false;
    };
}
#define YORDLE_META_DEF_x889fe194
#endif
