/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x8e85b8c7
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xf795f405.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_xf795f405
    struct xf795f405;
#endif
    struct YORDLE_EXPORT x8e85b8c7 : public xf795f405 {
        explicit x8e85b8c7(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2391128263u || xf795f405::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::xf795f405> x1bcf29d8 {};
    };
}
#define YORDLE_META_DEF_x8e85b8c7
#endif
