/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x90347ed8
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x90347ed8 : public bin_class {
        explicit x90347ed8(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2419359448u;
        }

        yordle::data::meta::bin_fnv_hash x3d56aa08 = 0u;
        yordle::data::meta::bin_fnv_hash xd20a71a6 = 0u;
        yordle::data::meta::bin_fnv_hash x8f7ddbd9 = 0u;
        yordle::data::meta::bin_fnv_hash Icon = 0u;
        yordle::data::meta::bin_fnv_hash x26d64467 = 0u;
        yordle::data::meta::bin_fnv_hash x75694838 = 0u;
        yordle::data::meta::bin_fnv_hash x836908e2 = 0u;
        yordle::data::meta::bin_fnv_hash xce2e82b0 = 0u;
        yordle::data::meta::bin_fnv_hash xc2035d7a = 0u;
        yordle::data::meta::bin_fnv_hash x850a3bd3 = 0u;
        yordle::data::meta::bin_fnv_hash x520e9f93 = 0u;
        yordle::data::meta::bin_fnv_hash x6f80474c = 0u;
        yordle::data::meta::bin_fnv_hash x72804c05 = 0u;
        yordle::data::meta::bin_fnv_hash x1c73ba1a = 0u;
        yordle::data::meta::bin_fnv_hash xf4596dad = 0u;
        yordle::data::meta::bin_fnv_hash x620384f9 = 0u;
        yordle::data::meta::bin_fnv_hash x85c88168 = 0u;
        yordle::data::meta::bin_fnv_hash NameText = 0u;
        yordle::data::meta::bin_fnv_hash x884d04dc = 0u;
        yordle::data::meta::bin_fnv_hash x2681dad1 = 0u;
        yordle::data::meta::bin_fnv_hash MuteButton = 0u;
    };
}
#define YORDLE_META_DEF_x90347ed8
#endif
