/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x99cce3c
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_defs/IFxAction.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x99cce3c : public IFxAction {
        explicit x99cce3c(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 161271356u || IFxAction::is_type(type);
        }

        uint8_t ZoomEase = 2u;
    };
}
#define YORDLE_META_DEF_x99cce3c
#endif
