/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x9a619bbc
#pragma once

#include <memory>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x9a619bbc : public bin_class {
        explicit x9a619bbc(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2590088124u;
        }

        std::array<yordle::data::meta::bin_fnv_hash, 4> xbfda5017 { 0u, 0u, 0u, 0u };
        std::array<yordle::data::meta::bin_fnv_hash, 4> x75a1a58c { 0u, 0u, 0u, 0u };
        std::array<yordle::data::meta::bin_fnv_hash, 4> xe5032427 { 0u, 0u, 0u, 0u };
    };
}
#define YORDLE_META_DEF_x9a619bbc
#endif
