/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_x9e5aed77
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT x9e5aed77 : public bin_class {
        explicit x9e5aed77(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2656759159u;
        }

        int32_t x571a97a3 = 0;
        int32_t x88a45101 = 0;
        int32_t x1a8b3cc8 = 0;
        int32_t xbb9129ab = 0;
        int32_t xe2e4f9c2 = 0;
        int32_t x47bdbbe9 = 0;
    };
}
#define YORDLE_META_DEF_x9e5aed77
#endif
