/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xa23088af
#pragma once

#include <memory>
#include <string>

#include <yordle/data/meta/bin_defs/x6df7291a.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xa23088af : public x6df7291a {
        explicit xa23088af(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2721089711u || x6df7291a::is_type(type);
        }

        std::string TitleKey {};
        std::string BodyKey {};
    };
}
#define YORDLE_META_DEF_xa23088af
#endif
