/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xa37f48cd
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xa37f48cd : public bin_class {
        explicit xa37f48cd(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2743027917u;
        }

        yordle::data::meta::bin_fnv_hash x75538f6e = 0u;
        yordle::data::meta::bin_fnv_hash x605b77ad = 0u;
    };
}
#define YORDLE_META_DEF_xa37f48cd
#endif
