/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xa6e3bf67
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xa6e3bf67 : public bin_class {
        explicit xa6e3bf67(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2799943527u;
        }

        yordle::data::meta::bin_fnv_hash Scene = 0u;
        yordle::data::meta::bin_fnv_hash x6cebd5d8 = 0u;
        yordle::data::meta::bin_fnv_hash x6d0613e = 0u;
        yordle::data::meta::bin_fnv_hash x830b37d2 = 0u;
    };
}
#define YORDLE_META_DEF_xa6e3bf67
#endif
