/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xb0d49a20
#pragma once

#include <memory>
#include <vector>
#include <cstdint>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xb0d49a20 : public bin_class {
        explicit xb0d49a20(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2966723104u;
        }

        std::vector<yordle::data::meta::bin_fnv_hash> xe6e3afce {};
        std::array<uint8_t, 4> x7c7732a1 { 10, 190, 250, 255 };
        std::array<uint8_t, 4> x3810c3f2 { 210, 230, 240, 255 };
    };
}
#define YORDLE_META_DEF_xb0d49a20
#endif
