/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xb1a585e5
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xb1a585e5 : public bin_class {
        explicit xb1a585e5(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2980414949u;
        }

        yordle::data::meta::bin_fnv_hash border = 0u;
        yordle::data::meta::bin_fnv_hash x1c9ff127 = 0u;
        yordle::data::meta::bin_fnv_hash x39ed6fc = 0u;
        yordle::data::meta::bin_fnv_hash x28cd6f66 = 0u;
        yordle::data::meta::bin_fnv_hash x1cd5f428 = 0u;
        yordle::data::meta::bin_fnv_hash xc96c4266 = 0u;
        yordle::data::meta::bin_fnv_hash xe04c974f = 0u;
    };
}
#define YORDLE_META_DEF_xb1a585e5
#endif
