/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xb277fa06
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_defs/xa51270e5.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xb277fa06 : public xa51270e5 {
        explicit xb277fa06(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2994207238u || xa51270e5::is_type(type);
        }

        uint8_t x3301fcdf = 0u;
        uint8_t xb49ed6f0 = 0u;
    };
}
#define YORDLE_META_DEF_xb277fa06
#endif
