/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xb2cc5617
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/xa5666564.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_xa5666564
    struct xa5666564;
#endif
    struct YORDLE_EXPORT xb2cc5617 : public bin_class {
        explicit xb2cc5617(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 2999735831u;
        }

        std::vector<std::shared_ptr<yordle::data::meta::xa5666564>> x77312335 {};
    };
}
#define YORDLE_META_DEF_xb2cc5617
#endif
