/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xb3a933a4
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/x8df16a16.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xb3a933a4 : public x8df16a16 {
        explicit xb3a933a4(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3014210468u || x8df16a16::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_xb3a933a4
#endif
