/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xbe48096c
#pragma once

#include <memory>
#include <map>

#include <yordle/data/meta/bin_defs/x7c402f20.hpp>
#include <yordle/data/meta/bin_defs/x78ec7262.hpp>
#include <yordle/data/meta/bin_defs/x2070f6ad.hpp>
#include <yordle/data/meta/bin_defs/x696a421b.hpp>
#include <yordle/data/meta/bin_defs/x48184113.hpp>
#include <yordle/data/meta/bin_defs/xc8924ad4.hpp>
#include <yordle/data/meta/bin_defs/healthBarData.hpp>
#include <yordle/data/meta/bin_defs/x1bca1a5e.hpp>
#include <yordle/data/meta/bin_defs/x9c472cf3.hpp>
#include <yordle/data/meta/bin_defs/x506291c8.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_x7c402f20
    struct x7c402f20;
#endif

#ifndef YORDLE_META_DEF_x78ec7262
    struct x78ec7262;
#endif

#ifndef YORDLE_META_DEF_x2070f6ad
    struct x2070f6ad;
#endif

#ifndef YORDLE_META_DEF_x696a421b
    struct x696a421b;
#endif

#ifndef YORDLE_META_DEF_x48184113
    struct x48184113;
#endif

#ifndef YORDLE_META_DEF_xc8924ad4
    struct xc8924ad4;
#endif

#ifndef YORDLE_META_DEF_healthBarData
    struct healthBarData;
#endif

#ifndef YORDLE_META_DEF_x1bca1a5e
    struct x1bca1a5e;
#endif

#ifndef YORDLE_META_DEF_x9c472cf3
    struct x9c472cf3;
#endif
    struct YORDLE_EXPORT xbe48096c : public x506291c8 {
        explicit xbe48096c(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3192392044u || x506291c8::is_type(type);
        }

        std::shared_ptr<yordle::data::meta::x7c402f20> burstData {};
        yordle::data::meta::bin_fnv_hash x944586d6 = 0u;
        yordle::data::meta::bin_fnv_hash x9d41b7c6 = 0u;
        yordle::data::meta::bin_fnv_hash xcf5d9d5b = 0u;
        std::shared_ptr<yordle::data::meta::x78ec7262> burstHealData {};
        yordle::data::meta::bin_fnv_hash x35cff176 = 0u;
        yordle::data::meta::bin_fnv_hash x6081c408 = 0u;
        yordle::data::meta::bin_fnv_hash xea2e3332 = 0u;
        yordle::data::meta::bin_fnv_hash x50c0698 = 0u;
        yordle::data::meta::bin_fnv_hash x36b04926 = 0u;
        std::map<yordle::data::meta::bin_fnv_hash, yordle::data::meta::bin_fnv_hash> x54a5eeef {};
        yordle::data::meta::bin_fnv_hash x15f21b36 = 0u;
        yordle::data::meta::bin_fnv_hash x6fe80584 = 0u;
        std::shared_ptr<yordle::data::meta::x2070f6ad> x9265210c {};
        std::shared_ptr<yordle::data::meta::x696a421b> x755be631 {};
        std::shared_ptr<yordle::data::meta::x48184113> icons {};
        std::shared_ptr<yordle::data::meta::xc8924ad4> xbab0c3f7 {};
        std::shared_ptr<yordle::data::meta::healthBarData> HealthBar {};
        std::shared_ptr<yordle::data::meta::x1bca1a5e> xa75595ed {};
        std::shared_ptr<yordle::data::meta::x1bca1a5e> xdacd361e {};
        std::shared_ptr<yordle::data::meta::x9c472cf3> xecc35e4b {};
    };
}
#define YORDLE_META_DEF_xbe48096c
#endif
