/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xce4229fb
#pragma once

#include <memory>
#include <cstdint>

#include <yordle/data/meta/bin_defs/xcd02833b.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xce4229fb : public xcd02833b {
        explicit xce4229fb(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3460442619u || xcd02833b::is_type(type);
        }

        int32_t value = 0;
    };
}
#define YORDLE_META_DEF_xce4229fb
#endif
