/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xd20000f6
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_defs/xb35ad9d8.hpp>
#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
#ifndef YORDLE_META_DEF_xb35ad9d8
    struct xb35ad9d8;
#endif
    struct YORDLE_EXPORT xd20000f6 : public bin_class {
        explicit xd20000f6(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3523215606u;
        }

        yordle::data::meta::bin_fnv_hash SceneData = 0u;
        yordle::data::meta::bin_fnv_hash Opened = 0u;
        yordle::data::meta::bin_fnv_hash Closed = 0u;
        yordle::data::meta::bin_fnv_hash x35e716ec = 0u;
        yordle::data::meta::bin_fnv_hash x67ddf4a7 = 0u;
        yordle::data::meta::bin_fnv_hash xc5612cad = 0u;
        std::vector<yordle::data::meta::bin_fnv_hash> x3cfec826 {};
        yordle::data::meta::bin_fnv_hash PinButton = 0u;
        std::shared_ptr<yordle::data::meta::xb35ad9d8> x434952b4 {};
    };
}
#define YORDLE_META_DEF_xd20000f6
#endif
