/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xd3cb80a0
#pragma once

#include <memory>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xd3cb80a0 : public bin_class {
        explicit xd3cb80a0(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3553329312u;
        }

        yordle::data::meta::bin_fnv_hash xd8d71d83 = 0u;
        yordle::data::meta::bin_fnv_hash x6afd17cf = 0u;
        yordle::data::meta::bin_fnv_hash x58de27c1 = 0u;
        yordle::data::meta::bin_fnv_hash xdffc8083 = 0u;
        yordle::data::meta::bin_fnv_hash xcc5d06d5 = 0u;
    };
}
#define YORDLE_META_DEF_xd3cb80a0
#endif
