/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xd946a9af
#pragma once

#include <memory>
#include <vector>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xd946a9af : public bin_class {
        explicit xd946a9af(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3645286831u;
        }

        std::vector<yordle::data::meta::bin_fnv_hash> xa2a39d73 {};
        std::vector<yordle::data::meta::bin_fnv_hash> x41ccb763 {};
        std::vector<yordle::data::meta::bin_fnv_hash> x4255c7d1 {};
        yordle::data::meta::bin_fnv_hash x82ad3a6e = 0u;
    };
}
#define YORDLE_META_DEF_xd946a9af
#endif
