/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xe0d5fc7e
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xefc7f35c.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xe0d5fc7e : public xefc7f35c {
        explicit xe0d5fc7e(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3772120190u || xefc7f35c::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_xe0d5fc7e
#endif
