/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xebd18932
#pragma once

#include <memory>
#include <array>
#include <string>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xebd18932 : public bin_class {
        explicit xebd18932(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 3956377906u;
        }

        yordle::data::meta::bin_fnv_hash Group = 0u;
        yordle::data::meta::bin_fnv_hash x10892008 = 0u;
        yordle::data::meta::bin_fnv_hash x80359e95 = 0u;
        yordle::data::meta::bin_fnv_hash x2f575f76 = 0u;
        yordle::data::meta::bin_fnv_hash x6286bb7 = 0u;
        yordle::data::meta::bin_fnv_hash xb6067959 = 0u;
        yordle::data::meta::bin_fnv_hash x14df3d1e = 0u;
        yordle::data::meta::bin_fnv_hash x2c15dfef = 0u;
        std::array<yordle::data::meta::bin_fnv_hash, 3> x8731b20e { 0u, 0u, 0u };
        yordle::data::meta::bin_fnv_hash x5a075a9b = 0u;
        std::array<yordle::data::meta::bin_fnv_hash, 8> x6c959f38 { 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u };
        std::string x10d5509e {};
        yordle::data::meta::bin_fnv_hash x33dfc200 = 0u;
        yordle::data::meta::bin_fnv_hash x736fde6a = 0u;
    };
}
#define YORDLE_META_DEF_xebd18932
#endif
