/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xfdad6e32
#pragma once

#include <memory>
#include <array>

#include <yordle/data/meta/bin_class.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xfdad6e32 : public bin_class {
        explicit xfdad6e32(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 4256001586u;
        }

        yordle::data::meta::bin_fnv_hash Group = 0u;
        yordle::data::meta::bin_fnv_hash Icon = 0u;
        yordle::data::meta::bin_fnv_hash xd8c93d9d = 0u;
        yordle::data::meta::bin_fnv_hash x8384ca73 = 0u;
        yordle::data::meta::bin_fnv_hash xb56b83fd = 0u;
        yordle::data::meta::bin_fnv_hash xc4d542df = 0u;
        yordle::data::meta::bin_fnv_hash xf1608144 = 0u;
        std::array<yordle::data::meta::bin_fnv_hash, 3> xdbc0caa0 { 0u, 0u, 0u };
    };
}
#define YORDLE_META_DEF_xfdad6e32
#endif
