/// <auto-generated>
// THIS FILE IS AUTO GENERATED DO NOT EDIT
#ifndef YORDLE_META_DEF_xfe7449a3
#pragma once

#include <memory>

#include <yordle/data/meta/bin_defs/xacb408c2.hpp>
#include <yordle/data/meta/bin_ref.hpp>
#include <yordle/data/prop/structure_prop.hpp>
#include <yordle/yordle_export.h>

namespace yordle::data::meta {
    struct YORDLE_EXPORT xfe7449a3 : public xacb408c2 {
        explicit xfe7449a3(const std::shared_ptr<yordle::data::prop::structure_prop> &prop);

        bool is_type(uint32_t type) override {
            return type == 4269033891u || xacb408c2::is_type(type);
        }
    };
}
#define YORDLE_META_DEF_xfe7449a3
#endif
